### PR TITLE
Purpose of the United Kingdom

### PR DESCRIPTION
**Pull request by frabcus**
I think *the* main problem with the UK right now is that nobody knows what it is for.

Back round about 1950, a post-war goal of economic wealth through technology, along with longterm peace was made. In many ways we have now achieved that (despite its flaws). What is our goal now?

This is my proposal.

### CODE REVIEW

**Comment by philipjohn** [comment]
There's some kind of human rights index, right? Something like that maybe, coupled with other similar indexes based on poverty, health, education?

**Comment by sanjaypoyzer** [comment]
Are there any other countries which have a mission statement like this? Otherwise we're comparing the UK to a charity (which maybe is a good thing, but it should definitely be noted how unprecedented it is.)

**Comment by frabcus** [comment]
Well, the purpose of the US was originally "the preservation of life, & liberty, & the pursuit of happiness".

**Comment by philipjohn** [comment]
I'm not sure a state is *for* anything, or should be, actually. People increasingly identify in ways that don't honour borders, and the internet makes this easier. We have a much more globalised culture than ever before where states are becoming less and less important to people other than politicians.

**Comment by tmtmtmtm** [comment]
> Well, the purpose of the US was originally "the preservation of life, & liberty, & the pursuit of happiness".

See also: “Liberté, égalité, fraternité”. This also reminds me of Bhutan introducing Gross National Happiness as its primary metric. 

Or, from another angle, the mission of setting up a worldwide caliphate…

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are a [contributor](https://votebot.openpolitics.org.uk/proposals/) to this repository (and not the proposer), you may vote on whether or not it is accepted. 

## How to vote
Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

|vote|symbol|type this|points|
|--|--|--|--|
|Agree|:thumbsup:|`:thumbsup:`|1|
|Abstain|:hand:|`:hand:`|-1|
|Block|:thumbsdown:|`:thumbsdown:`|-1000|

Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 7 days, but will be closed if the proposal is not accepted after 90.

Votes are counted [automatically here](https://votebot.openpolitics.org.uk/proposals/215), and results are set in the merge status checks below.

## Changes

If the proposer makes a change to the proposal, no votes cast before that change will be counted.

**Pull request closed without merging**
