### PR TITLE
Invest in low emission vehicles

### PR DESCRIPTION
**Pull request by BenTrimble**
Changes made to try to make the pledge more in line with achievable end result. The existing technology available does not allow us to eliminate fossil fuels and hence we should look at the steps needed to achieve that first, with a commitment to extend into zero-emissions later.

### CODE REVIEW

**Comment by philipjohn** [comment]
@Floppy Are you happy with this other than having a set date? If so, does it makes sense to :+1: this one and do another PR afterwards?

@BenTrimble Can you click the big button on https://www.clahub.com/agreements/openpolitics/manifesto please so that we can include your contributions?

**Comment by Floppy** [comment]
Yeah, OK. :+1:

**Comment by Floppy** [comment]
Since this was submitted, we've got a date in there for no new fossil fueled vehicles after 2029. This PR should, if we still want it, be updated to reflect that wording, or change it. As the source text has changed, it might be best for @BenTrimble to resubmit this change based on the new words maybe? I suspect he wouldn't be happy with just adding "by 2030" on the end, given this thrust of this change is to remove such talk of deadlines.

**Comment by Floppy** [comment]
I'm moving to :hand: on this, as I think it probably needs redoing based on the current text.

**Comment by Floppy** [comment]
We need @BenTrimble's input on this one, but seeing as the underlying text has changed substantially and this has passed the 90-day merge deadline, I'm going to close this and invite @BenTrimble to propose the update again based on the existing text if he wants to.

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are a [contributor](https://votebot.openpolitics.org.uk/proposals/) to this repository (and not the proposer), you may vote on whether or not it is accepted. 

## How to vote
Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

|vote|symbol|type this|points|
|--|--|--|--|
|Agree|:thumbsup:|`:thumbsup:`|1|
|Abstain|:hand:|`:hand:`|-1|
|Block|:thumbsdown:|`:thumbsdown:`|-1000|

Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 7 days, but will be closed if the proposal is not accepted after 90.

Votes are counted [automatically here](https://votebot.openpolitics.org.uk/proposals/241), and results are set in the merge status checks below.

## Changes

If the proposer makes a change to the proposal, no votes cast before that change will be counted.

**Pull request closed without merging**
