### PR TITLE
Ridesharing and Carpooling

### PR DESCRIPTION
**Pull request by Autumn-Leah**

### CODE REVIEW

**Comment by Xyleneb** [comment]
>Through a series of targeted marketing campaigns and PSA's we would encourage carpooling, especially for parents and those on the same street with a shared workplace, or workplaces in reasonable walking distance of each other.

I take it some 650 MPs will be carpooling to work too?

>Ridesharing would be promoted through The Job Center

"Have you considered doing some ridesharing today?"
"Yeah thanks for that, but we're all unemployed and can't afford to run a car."

Ahh yes, the top-down finger wagging that means well...

The best I could do for the policy is abstain from the vote.

**Comment by Autumn-Leah** [comment]
It's not supposed to be the sole function of the job center, I just see it as an additional thing that those with cars could be encouraged into alongside traditional jobs.

**Comment by philipjohn** [comment]
Could we expand PSA please? Acronyms are nice but cause confusion to those who don't already understand them.

Also not overly keen on mentioning Under directly too, given they are becoming something of a Marmite (yes, i get the irony of using another brand in that sentence ;) ).

Vote: ✅

**Comment by Autumn-Leah** [comment]
Expanded the acronym for you. Uber is just an example, I can put "for example" or "ridesharing services such as Uber" if you like.

**Comment by Autumn-Leah** [comment]
Adjusted it for you

**Comment by philipjohn** [comment]
Thank you!

Vote: ✅

**Comment by Floppy** [comment]
Vote: ✅

**Pull request merged**
