### PR TITLE
Added policy on European Parliament.

### PR DESCRIPTION
**Pull request by iconoclast86**
Campaign for the abolition of the Strasbourg Parliament which meets just 4 days a month. This would save approximately 150-200 million Euros each year.

### CODE REVIEW

**Comment by Floppy** [comment]
:+1: for sure - seems pointless.

**Comment by yellowgopher** [comment]
YES!  I like this one!  Agreed, one location is enough.

**Comment by andrewdwilliams** [comment]
:+1:

**Comment by andrewdwilliams** [comment]
:+1: support

**Comment by Floppy** [comment]
@yellowgopher do a thumbs up icon like so `:+1:` for the robot to count your vote.

**Comment by yellowgopher** [comment]
:+1: 
Didn't think I could vote..!

**Comment by Floppy** [comment]
yep, pretty sure you're a contributor :)

**Comment by yellowgopher** [comment]
I contribute but I thought the rules were you had to have some accepted!  Lol!

**Comment by Floppy** [comment]
you did :)
https://github.com/openpolitics/manifesto/commit/4748632a95d10d0794ea16cb3d04614403e134a6

**Comment by yellowgopher** [comment]
Did I?  Maybe one perhaps.  Have the rules changed?

**Comment by tmtmtmtm** [comment]
Presumably this should be an 'e.g.', not an 'i.e.'? If not then it's changing this policy much more significantly than it might at first appear...

If changing it anyway for that, I'd also suggest changing the "make" to "making", not only because it fits better grammatically, but because otherwise this line in isolation makes it seem like this is something within the UK's power.

(I have lots of other meta-issues about the entire concept here, as this is something the EU Parliament has already voted on, and the issues around it are significantly more complex than this sort of wording implies, but unfortunately I don't have time to engage on this right now.)

**Comment by yellowgopher** [comment]
@tmtmtmtm  is right. I got carried away. It needs to be re-worded to reflect it would be a desire of the government to see that the EU parliament was in one location only. A constant drive to reduce bureaucracy and inefficiency is a good thing but how do we quantify that? Hmmm... more thought needed.

**Comment by philipjohn** [comment]
:+1:

**Comment by Floppy** [comment]
I'll accept this and do the grammar fixes as another PR.

**Comment by Floppy** [comment]
Done, see https://github.com/openpolitics/manifesto/pull/336

**Comment by Floppy** [comment]
pinging here to make the votebot close the vote, as this is merged.

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are a [contributor](https://votebot.openpolitics.org.uk/proposals/) to this repository (and not the proposer), you may vote on whether or not it is accepted. 

## How to vote
Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

|vote|symbol|type this|points|
|--|--|--|--|
|Agree|:thumbsup:|`:thumbsup:`|1|
|Abstain|:hand:|`:hand:`|-1|
|Block|:thumbsdown:|`:thumbsdown:`|-1000|

Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 7 days, but will be closed if the proposal is not accepted after 90.

Votes are counted [automatically here](https://votebot.openpolitics.org.uk/proposals/322), and results are set in the merge status checks below.

## Changes

If the proposer makes a change to the proposal, no votes cast before that change will be counted.

**Pull request merged**
