### PR TITLE
Section on private military contractors

### PR DESCRIPTION
**Pull request by andrewdwilliams**
Added a section on private military and security companies. Said we should establish a regulatory body for them in the UK and also push for an international regulatory body/set of statute. I'm considering adding something about making spending on PMSCs transparent.

### CODE REVIEW

**Comment by Floppy** [comment]
:+1:

**Comment by h2g2bob** [comment]
:+1: I imagine most are secretive and would go offshore if regulated (even if lightly regulated), but that is probably still a positive step.

> adding something about making spending on PMSCs transparent

And forbid the MoD from hiring unregulated PMSCs?

**Comment by andrewdwilliams** [comment]
I know, but then again, it could be good kudos for them if they're clearly on a list of regulated companies that operate ethically. It could see them potentially getting more contractors because of it. So it's not a lose-lose for them. That's also why I put in the bit about working towards an international treaty.

What I was thinking about adding was something about making how much money the government spends on contractors transparent. But that could potentially be a security risk, particularly if they're being used on an active operation.

**Comment by philipjohn** [comment]
:+1:

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are a [contributor](https://votebot.openpolitics.org.uk/proposals/) to this repository (and not the proposer), you may vote on whether or not it is accepted. 

## How to vote
Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

|vote|symbol|type this|points|
|--|--|--|--|
|Agree|:thumbsup:|`:thumbsup:`|1|
|Abstain|:hand:|`:hand:`|-1|
|Block|:thumbsdown:|`:thumbsdown:`|-1000|

Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 7 days, but will be closed if the proposal is not accepted after 90.

Votes are counted [automatically here](https://votebot.openpolitics.org.uk/proposals/370), and results are set in the merge status checks below.

## Changes

If the proposer makes a change to the proposal, no votes cast before that change will be counted.

**Pull request merged**
