### PR TITLE
Adjustment to manifesto introduction

### PR DESCRIPTION
**Pull request by Autumn-Leah**
Added a few more categories that shouldn't be discriminated against, removed society, as adjusting society could be interpreted as a clamp down on freedom of speech, and changed the wording to make it flow properly both as a list and read as a continuous sentence.

### CODE REVIEW

**Comment by philipjohn** [comment]
Vote: ✅

**Comment by Floppy** [comment]
Vote: ✅

**Comment by Autumn-Leah** [comment]
Updated it with a few others that shouldn't lead to discrimination in legislation or in court matters

**Comment by andrewdwilliams** [comment]
Vote: ✅

**Comment by philipjohn** [comment]
Vote: ✅

**Comment by Floppy** [comment]
Vote: ✅

**Pull request merged**
