### PR TITLE
Incentivise electric cars used as grid backup storage

### PR DESCRIPTION
**Pull request by Floppy**
I've tried to explain the whole thing here, so it's a little longer than strictly necessary, but I think it's OK.

### CODE REVIEW

**Comment by stringfellow** [comment]
Vote: ✅

**Comment by philipjohn** [comment]
Vote: ✅

**Comment by philipjohn** [comment]
"The government should" might sound better as "We will"

**Comment by Floppy** [comment]
Thanks @philipjohn, I've updated the language to be more direct as you suggested. @stringfellow you'll need to recast your vote for the new version (lovely to see you, btw) :D

**Comment by andrewdwilliams** [comment]
Vote: ✅

**Comment by Floppy** [comment]
Votebot has marked this as passed, but it actually needs recast votes after my edit, so I'm not merging yet. I've filed a bug on votebot and will fix it.

**Comment by philipjohn** [comment]
Ah, I was ignoring it in the proposals list 'cause it was green :)

Vote: ✅

**Pull request merged**
