### PR TITLE
Remove right to parody

### PR DESCRIPTION
**Pull request by Floppy**
These are now legal, the clauses are just out of date.

### CODE REVIEW

**Comment by philipjohn** [comment]
Vote: ✅

**Comment by tmtmtmtm** [comment]
@floppy do you have a citation for that? The last I knew about this was that the courts had sided with the music industry to overturn the Personal Copies for Private Use Regulations (https://www.barkerbrettell.co.uk/copyright-exemption-for-private-use-regulations-quashed-2/), and I wasn't aware that that had been successfully appealed yet, or that new legislation had been introduced.

**Comment by Floppy** [comment]
Good point, I need a proper source. Honestly I was just going on what's on the ORG website and that they're not campaigning on this any more, but it's not actually clear there either. Pop a downvote on this for now until I can provide.

**Comment by Floppy** [comment]
On parody, the guidance is now on the gov.uk site: https://www.gov.uk/guidance/exceptions-to-copyright#parody-caricature-and-pastiche

Still looking to confirm format-shifting status, but now you mention it, I do vaguely remember some sort of rollback on that, so it might still be relevant.

**Comment by Floppy** [comment]
[The Copyright and Rights in Performances (Personal Copies for Private Use) Regulations 2014](http://www.legislation.gov.uk/uksi/2014/2361/pdfs/uksi_20142361_en.pdf) enabled format-shifting for personal use, but yes, your link above states that it was quashed. I can't find anything after that that states that it's been changed since. So, format shifting still seems to be technically unlawful.

I'll update this PR to reflect that, and update the format shifting link as well. Thanks @tmtmtmtm, you had better information than me :)

**Comment by philipjohn** [comment]
Oh good one checking on that.

Vote: ✅

**Comment by Autumn-Leah** [comment]
Vote: ✅

**Pull request merged**
