### PR TITLE
Transport: allocate road space to bus lanes

### PR DESCRIPTION
**Pull request by h2g2bob**
My suggestion is to encourage frequent service where there is appropriately dense land use ("towns and cities") as this will reduce traffic and congestion. "Allocating road space" will mean taking space away from other traffic. Making bus journeys faster improves both travel time and time waiting for the next bus (it's a double benefit).

Congested roads exist because there's not enough space for all the vehicles (this is true, even with electric cars). I'd like to reward people who are reducing traffic by using public transport.

I think this policy is consistent with other policies in this section, which encourage a shift to less-polluting modes of transport.

I'm influenced by [Human Transit](http://www.humantransit.org/2015/07/mega-explainer-the-ridership-recipe.html) in this suggestion.

### CODE REVIEW

**Comment by andrewdwilliams** [comment]
:+1:

**Comment by PaulJRobinson** [comment]
:+1:

**Comment by Floppy** [comment]
:+1: and we should extend to cycling in a followup as well.

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are a [contributor](https://votebot.openpolitics.org.uk/proposals/) to this repository (and not the proposer), you may vote on whether or not it is accepted. 

## How to vote
Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

|vote|symbol|type this|points|
|--|--|--|--|
|Agree|:thumbsup:|`:thumbsup:`|1|
|Abstain|:hand:|`:hand:`|-1|
|Block|:thumbsdown:|`:thumbsdown:`|-1000|

Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 7 days, but will be closed if the proposal is not accepted after 90.

Votes are counted [automatically here](https://votebot.openpolitics.org.uk/proposals/366), and results are set in the merge status checks below.

## Changes

If the proposer makes a change to the proposal, no votes cast before that change will be counted.

**Pull request merged**
