### PR TITLE
Changes to school uniform regulations

### PR DESCRIPTION
**Pull request by Autumn-Leah**
The only intent of most of my policies is to increase freedom both individually and collectively, I think this policy does this successfully.

### CODE REVIEW

**Comment by Floppy** [comment]
I'm going to abstain on this, as I know my experience of what helps kids learn is absolutely zero, so I can't say whether this is a good thing or not. I'm all for freedom and individual expression of course, but I'm just not an expert here.

**Comment by Autumn-Leah** [comment]
That's fair, I just hope this passes because individual expression and equality was the goal of this policy, whilst maintaining classroom order, for obvious reasons.

**Comment by philipjohn** [comment]
You've managed to take something about which I get very passionate, apparently read my mind, but then actually articulate it in a way that isn't a shouty rant. Kudos :)

Vote: ✅

**Comment by Floppy** [comment]
I think I can now properly abstain...

Vote: 🤐

**Pull request closed without merging**
