### PR TITLE
Don't ban or break encryption

### PR DESCRIPTION
**Pull request by Floppy**
Trying to ban encryption is pointless. This is a statement to that effect, really.

### CODE REVIEW

**Comment by philipjohn** [comment]
Vote: ✅

**Comment by Autumn-Leah** [comment]
Vote: ✅

**Comment by philipjohn** [comment]
Uh-oh Votebot if confused. This had been open for 7 days and has 2 votes. I'm going to merge it.

**Comment by Floppy** [comment]
erk.

**Comment by areteh** [comment]
Vote: ✅

**Pull request merged**
