### PR TITLE
Scrap Vehicle Excise Duty

### PR DESCRIPTION
**Pull request by Floppy**
Put the tax on fuel instead, saving money on admin, and still having the desired effect of taxing emissions.

### CODE REVIEW

**Comment by philipjohn** [comment]
:+1:

**Comment by otfrom** [comment]
but doesn't put a tax on the emissions of creating the vehicle

**Comment by Floppy** [comment]
I don't think VED does that now, and I'd prefer that embodied carbon cost (for *everything*) would be included in a proper carbon pricing regime. After all, under VED, a huge electric vehicle would still be zero-rated, as it's based on exhaust emissions.

**Comment by tmtmtmtm** [comment]
I'd prefer the argument for this was backed up by something stronger than "it seems fairer". This is presumably something that there's already been quite a lot of research into, and that different countries will have deliberately chosen different approaches to. Is there a good summary of the issue somewhere?

**Comment by Floppy** [comment]
Agree the "seems fairer" wording is vague. Is there a general principle of taxing the thing you're measuring directly as opposed to indirectly? What's that called? Direct/indirect is something else...

**Comment by Floppy** [comment]
A summary of "road taxes" from around the world: https://en.wikipedia.org/wiki/Road_tax. Most seem to be based on emissions, but such a tax is nowhere near universal, and some, such as France's, have been abolished and replaced with more direct measures.

**Comment by Floppy** [comment]
I suspect there is a different PR to be made on tax philosophy in general, but I'd prefer not to get into that here.

**Comment by PaulJRobinson** [comment]
:+1:

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are a [contributor](https://votebot.openpolitics.org.uk/proposals/) to this repository (and not the proposer), you may vote on whether or not it is accepted. 

## How to vote
Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

|vote|symbol|type this|points|
|--|--|--|--|
|Agree|:thumbsup:|`:thumbsup:`|1|
|Abstain|:hand:|`:hand:`|-1|
|Block|:thumbsdown:|`:thumbsdown:`|-1000|

Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 7 days, but will be closed if the proposal is not accepted after 90.

Votes are counted [automatically here](https://votebot.openpolitics.org.uk/proposals/267), and results are set in the merge status checks below.

## Changes

If the proposer makes a change to the proposal, no votes cast before that change will be counted.

**Pull request merged**
