### PR TITLE
Open data in science

### PR DESCRIPTION
**Pull request by ghaggart**
See the changes

### CODE REVIEW

**Comment by Floppy** [comment]
👍 on the principle, though I wonder if the wording needs to be slightly more precise to focus on  publicly-funded research? Should commercial research need to be published in the same way? Trials and negative results should, of course, but I'm not sure of the nuances.

**Comment by ghaggart** [comment]
Definitely needs more careful consideration and wording, and specific clarification on public and commercial research requirements. I'll make some changes.

**Comment by Floppy** [comment]
Great - the custom editor doesn't support updating existing PRs, but given your github history I assume you know what you're doing :)

**Comment by philipjohn** [comment]
:+1: commercial research could probably describe the pharmaceutical industry so there is something in applying the same rules to medical research, certainly. Probably a wording thing.

**Comment by Floppy** [comment]
@ghaggart are you still intending to make some changes to this proposal?

**Comment by ghaggart** [comment]
@Floppy  Apologies for the late reply on this, I'll have a look at the wording and make the changes asap.

**Comment by philipjohn** [comment]
This proposal failed because of time :(

I wonder if changes will reset the clock? @Floppy

**Comment by Floppy** [comment]
It won't, but we could merge anyway as technically the thing passed, we just knew @ghaggart was intending to make some changes. We could do those as a separate PR instead. Our future automated system would have merged it. So we should. *merges*

**Comment by Floppy** [comment]
@ghaggart if you still want to make changes to this, then do so in another edit. :)

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are a [contributor](https://votebot.openpolitics.org.uk/proposals/) to this repository (and not the proposer), you may vote on whether or not it is accepted. 

## How to vote
Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

|vote|symbol|type this|points|
|--|--|--|--|
|Agree|:thumbsup:|`:thumbsup:`|1|
|Abstain|:hand:|`:hand:`|-1|
|Block|:thumbsdown:|`:thumbsdown:`|-1000|

Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 7 days, but will be closed if the proposal is not accepted after 90.

Votes are counted [automatically here](https://votebot.openpolitics.org.uk/proposals/410), and results are set in the merge status checks below.

## Changes

If the proposer makes a change to the proposal, no votes cast before that change will be counted.

**Pull request merged**
