### PR TITLE
Expanded religious courts section

### PR DESCRIPTION
**Pull request by andrewdwilliams**
We only really have problems with one type of religious court in this country, so I've expanded the section slightly and included a reference to one of the more prominent anti-Sharia campaigns, from which there is undoubtedly more legislation to draw from in the future.

### CODE REVIEW

**Comment by yellowgopher** [comment]
I'm a :+1: with this one - when in Rome do as the Romans do.

**Comment by philipjohn** [comment]
We shouldn't limit ourselves to Sharia courts, but I don't think this change does, it just adds them as an example. :+1:

**Comment by andrewdwilliams** [comment]
@Floppy Could this be merged now? With the VoteBot down, I don't think there's any other way to do it than just ask.

**Comment by philipjohn** [comment]
All the checks were passing actually, so I've just merged this :)

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are a [contributor](https://votebot.openpolitics.org.uk/proposals/) to this repository (and not the proposer), you may vote on whether or not it is accepted. 

## How to vote
Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

|vote|symbol|type this|points|
|--|--|--|--|
|Agree|:thumbsup:|`:thumbsup:`|1|
|Abstain|:hand:|`:hand:`|-1|
|Block|:thumbsdown:|`:thumbsdown:`|-1000|

Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 7 days, but will be closed if the proposal is not accepted after 90.

Votes are counted [automatically here](https://votebot.openpolitics.org.uk/proposals/348), and results are set in the merge status checks below.

## Changes

If the proposer makes a change to the proposal, no votes cast before that change will be counted.

**Pull request merged**
