### PR TITLE
Amendment to Education Funding and Addition of Curriculum

### PR DESCRIPTION
**Pull request by OliverJackson1**
Amendment to Funding - drawing out the limitless age concept (I have assumed that this was implied by the wording).

Addition of Curriculum and the incorporation of Philosophy to the core curriculum. the aim here is to establish the key principles of society early on within pupils. Moving then to establish greater critical reasoning and theorisation skills. This subject will also help establish methods for dealing with the challenges of life.

### CODE REVIEW

**Comment by andrewdwilliams** [comment]
Not sure about philosophy being a core subject. Why philosophy and not politics, for instance? Also, unfortunately, philosophy may be a bit too high-brow for a lot of kids, especially those pre-sixth form, and the value in teaching the subject might be lost.

**Comment by philipjohn** [comment]
@OliverJackson1 Could you elaborate a bit more on what you expect this will include?

**Comment by OliverJackson1** [comment]
@andrewdwilliams / @philipjohn , yeah of course.

So, the starting point for any social science or pseudo-science is Philosophy (some may consider that debatable but I would strongly disagree with them). From Philosophy we develop Politics, Economics, Sociology etc. So, in turn it makes sense to incorporate it as a curriculum fulcrum.

I envisage (but don't hold me to the details here) beginning with Foundation and Year 1 students (4 - 6) working with some of the key allegories of philosophy - namely, the Allegory of the Cave and the Allegory of the Apples. The first focusing on the importance of finding the true form of something - not just what it may look, feel, smell, etc. The second, focusing on the importance of disseminating all information before decision making.

These classes would be tangible and physical.

Years 2 - 6 would then focus of the key principles of knowledge and understanding. Inductive and Deductive reasoning classes. The categorical imperative, the tautology of existence (cogit ergo sum), what is Rhetoric and the separation of sub-specie durationis and sub specie aeternitatis. That may sound heavy but in practicality isn't.

Secondary school would then be set for the separation to socio/politico/economic avenues. Philosophy itself would continue with a focus on Angst and Alienation (quite vital for that period of life). The existentialists would play a key role in helping students come to terms with lifes issues as well as developing on the foundational understanding they would have built. Topics here would concern Sartrian Bad Faith, Angst, The Uber Mensch, The Importance of History, The Intrinsic Nature of Suffering, The Will to Life, The Power of Communication, The Sublime and The Virtue of Liberty.
To close, Karl Marx stated that the point of philosophy is to change the word (whilst I would argue that it has) the greatest means by which we can achieve this change is to empower the youth with knowledge. This curriculum addition would ensure sound, reasoned, careful but capable thinkers with the critical capacity to understand rhetoric and disseminate lies (statements built on bad truth).
Let me know what you think. As always happy to debate further on this :).

**Comment by philipjohn** [comment]
Thanks, that makes sense. Whilst reading through that I thought to myself that some of that is likely touched on in Religious Education so perhaps we could replace R.E. (I'm no fan, anyway) with Philosophy.

Sure enough, [we already have](http://openpolitics.org.uk/manifesto/education.html#secular-schools) :)

**Comment by Floppy** [comment]
👍 on the ideas, but could do with an edit to make sure it matches up with the section @philipjohn linked to (either editing this new text, or that existing text, whichever makes most sense).

**Comment by philipjohn** [comment]
This proposal has exceeded the time limit, so we'll close it off, but @OliverJackson1 please do think about what could be done to make this proposal more successful, and try again. Thanks!

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are a [contributor](https://votebot.openpolitics.org.uk/proposals/) to this repository (and not the proposer), you may vote on whether or not it is accepted. 

## How to vote
Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

|vote|symbol|type this|points|
|--|--|--|--|
|Agree|:thumbsup:|`:thumbsup:`|1|
|Abstain|:hand:|`:hand:`|-1|
|Block|:thumbsdown:|`:thumbsdown:`|-1000|

Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 7 days, but will be closed if the proposal is not accepted after 90.

Votes are counted [automatically here](https://votebot.openpolitics.org.uk/proposals/397), and results are set in the merge status checks below.

## Changes

If the proposer makes a change to the proposal, no votes cast before that change will be counted.

**Pull request closed without merging**
