### PR TITLE
Resubmission: Equality in Rape Law

### PR DESCRIPTION
**Pull request by Autumn-Leah**
Because the last debate died out due to people not doing their own research properly and raising frivolous wording concerns I've resubmitted this proposal. Top tip, don't just check stuff via your profile, actually go through and see if any of the old debates have updated, I've had too many times where a proposal has been hotly debated, they make a point and vote against, I make a point, and then because they've voted and it doesn't show up on their profile, I never get a response. Anyways, enough of my greivances, here's what you need to look at:

Sexual Offences Act 2003 - htm format: http://legislation.data.gov.uk/ukpga/2003/42/data.htm?wrap=true

Sexual Offences Act 2003 - Rape: http://www.legislation.gov.uk/ukpga/2003/42/section/1

Sexual Offences Act 2003 Explanatory Notes: http://www.legislation.gov.uk/ukpga/2003/42/notes/division/5/1/1

Law students and lawyers saying the same thing I am: http://www.keepcalmtalklaw.co.uk/gendered-legislation-critiquing-the-sexual-offences-act-2003/

Now if people seeing this bother to do their own research or just read the provided sources, you'll see that this is a good policy.

### CODE REVIEW

**Comment by Floppy** [comment]
Thanks for resubmitting, and adding those references @Autumn-Leah. I do need to implement your suggestion of showing people what's been updated since their last visit, too - sorry it's taking a while!

**Comment by Floppy** [comment]
This seems reasonable to me; I'd consider rape to be any forced sexual activity.

Vote: ✅

**Comment by Floppy** [comment]
Oh, one thought: does this not fit better in the Crime & Justice page? I'd say this is more a criminal law thing than a promotion-of-equality thing. I don't mind either way, it just occurred to me is all :)

**Comment by RobertWootton** [comment]
Until I read through the amendments, I did not know what PIV stood for but although I have heard of LGBT, I do not know what the Q+ means in the term LGBTQ+.

**Pull request closed without merging**
