### PR TITLE
added basic hygiene products (toilet paper, etc) to no VAT on tampons

### PR DESCRIPTION
**Pull request by LudovicD**
(other basic hygiene products too) (thinking of toilet paper, soap, shampoo, toothbrush, toothpaste & why not deodorant?)

### CODE REVIEW

**Comment by Floppy** [comment]
So what I wanted to ask here is - are those things currently in the luxury bracket and hence VATable?

**Comment by Floppy** [comment]
Realised the wording here leaves a little to be desired as we're particularly talking about VAT.

**Comment by Floppy** [comment]
Wording in the original, that is.

**Comment by Autumn-Leah** [comment]
Whether it is or isn't currently, it's still a good statement to make, but the original needs to me reworded to be more formal and policy-like.

**Comment by Floppy** [comment]
Vote: ✅

**Comment by philipjohn** [comment]
Vote: ✅

**Comment by Floppy** [comment]
This will be automatically merged shortly; I'll try to remember to follow up with a proposal just tidying up the wording a little and perhaps moving some bits into a footnote.

**Pull request merged**
