### PR TITLE
Support worker owned enterprise

### PR DESCRIPTION
**Pull request by digitalWestie**
Some relevant links:
- http://employeeownership.co.uk/
- http://en.wikipedia.org/wiki/Worker_cooperative
- http://www.radicalroutes.org.uk/publicdownloads/setupaworkerscoop-lowres.pdf

### CODE REVIEW

**Comment by philipjohn** [comment]
My understanding is that co-operatives mostly use the limited by guarantee form of limited company. Is this not suitable?

**Comment by Floppy** [comment]
@digitalWestie how do you mean "we will introduce legislation which is designed with these types of organisation in mind."? Would that be better phrased as "we will create a new corporate structure explicitly designed for these organisations"?

A couple of questions, if that's the case:

1) As Phil says, what do the current structures not allow that co-operatives need? Limited-by-guarantee, CICs, etc.
2) Where in the world does have a proper legal status for co-operatives, and how does it benefit them?

To be clear, I like the idea, we just need to flesh it out a little. :hand: for now.

**Comment by Floppy** [comment]
@digitalWestie are you up for expanding this a little? If not, it will be closed having passed the 90-day deadline, and is now languishing...

To reiterate, I like the idea, but I'm not sure what the legislation that's being proposed actually is, or is intending to fix.

**Comment by digitalWestie** [comment]
Hey, if you're wondering what happened to this I decided it's probably better split out into multiple proposals. Will add when I get the chance.

**Comment by Floppy** [comment]
thanks!

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are a [contributor](https://votebot.openpolitics.org.uk/proposals/) to this repository (and not the proposer), you may vote on whether or not it is accepted. 

## How to vote
Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

|vote|symbol|type this|points|
|--|--|--|--|
|Agree|:thumbsup:|`:thumbsup:`|1|
|Abstain|:hand:|`:hand:`|-1|
|Block|:thumbsdown:|`:thumbsdown:`|-1000|

Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 7 days, but will be closed if the proposal is not accepted after 90.

Votes are counted [automatically here](https://votebot.openpolitics.org.uk/proposals/248), and results are set in the merge status checks below.

## Changes

If the proposer makes a change to the proposal, no votes cast before that change will be counted.

**Pull request closed without merging**
