### PR TITLE
secular Remebrance Day

### PR DESCRIPTION
**Pull request by andrewedmondson**

### CODE REVIEW

**Comment by yellowgopher** [comment]
I'd argue that there are plenty of secular remembrance day events that occur anyway...!  I'm not sure of the law that states remembrance day has to be religious - but please correct me if I am wrong!

**Comment by andrewedmondson** [comment]
The Cenotaph ceremony excludes non-religious. This was imposed by the 
government's consultation panel ... run by religious senior chaplains.

Local ceremonies are mainly religious. They are organised by the British 
Legion, local council and churches, or a combination of these. There is 
no law binding them to a religious ceremony but the religious vested 
interests impose their will on everyone. It is very unpopular.

**Comment by yellowgopher** [comment]
I think we need proof that these services are not popular - our one gets a lot of people (both believers and non-believers).
I believe the only person who has an absolute right to attend the Cenotaph service is the Queen.  The rest are organised by precedence or local agreement/arrangement.  So, on that basis, it doesn't HAVE to be religious but, if those organising it want it to be then...
Now, if there are issues with those who arrange these services, then why do we not have many non-religious groups setting up their own services?  I help organise a service in my village and we invite every and any group to be part of it but, more often than not, it is the churches and the local council that do the work.  Everyone else just expects it to happen - and then complain when it doesn't go right!!!

**Comment by andrewedmondson** [comment]
The point is that Remebrance ceremonies should be secular and not 
dominated by any particular religion or belief group.

Religious groups may wish to have their own additional services but they 
should not be imposed on others.

At Chichester, people leave in their droves after the wreath laying 
because they don't want to attend the very lengthy religious service.

I don't want the national anthem played either, as it mentions God.

**Comment by yellowgopher** [comment]
So set up your own ceremonies!

**Comment by andrewedmondson** [comment]
That's not the point. It should be the responsibility of the local 
council to ensure that such an important ceremony be conducted inclusively.

I don't want to attend a Humanist ceremony. I did so at Chichester to 
make a point. I want to be included with everyone else.

On 14/04/2015 17:00, yellowgopher wrote:
>
> So set up your own ceremonies!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/openpolitics/manifesto/pull/330#issuecomment-92932715>.
>

-- 
Andrew Edmondson

079 3450 8671
West Sussex Humanists <http://www.westsussexhumanists.org.uk>
BHA logo <http://www.humanism.org.uk/>

**Comment by yellowgopher** [comment]
You are welcome... I am fairly certain no one was there to turn you away!
Councils can organise them now, and they do. 
Us church goers want to feel included too :-( Lol!

**Comment by andrewedmondson** [comment]
You may be most welcoming but the truth is that many people are put off 
attending a religious ceremony. You won't be aware of them. A secular 
ceremony includes everyone.

On 14/04/2015 17:09, yellowgopher wrote:
>
> You are welcome... I am fairly certain no one was there to turn you away!
> Councils can organise them now, and they do.
> Us church goers want to feel included too :-( Lol!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/openpolitics/manifesto/pull/330#issuecomment-92937373>.
>

-- 
Andrew Edmondson

079 3450 8671
West Sussex Humanists <http://www.westsussexhumanists.org.uk>
BHA logo <http://www.humanism.org.uk/>

**Comment by yellowgopher** [comment]
Where's the proof?
I think people look beyond religion for remembrance services.

**Comment by andrewedmondson** [comment]
Proof is not required. You know that many people are not religious and 
yet you are expecting them to attend a religious ceremony to commemorate 
a non-religious event.

The same argument applies to Council prayers. Every councillor may be 
religious and want to pray at the meeting. However, the meeting is for a 
secular purpose. How many potential councillors or members of the public 
are put off by this? I don't know. But even if none of them were, the 
principle is the same.

Separation of church and state applies to national and local government.

And as I said, local government should control important national 
ceremonies like Remembrance Day. It's part of social cohesion. Leave it 
up to the local church, British Legion or local councillors, and you get 
what we have now.

On 14/04/2015 17:17, yellowgopher wrote:
>
> Where's the proof?
> I think people look beyond religion for remembrance services.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/openpolitics/manifesto/pull/330#issuecomment-92945460>.
>

-- 
Andrew Edmondson

079 3450 8671
West Sussex Humanists <http://www.westsussexhumanists.org.uk>
BHA logo <http://www.humanism.org.uk/>

**Comment by philipjohn** [comment]
:+1: 

Remembrance ceremonies are largely dominated by Christian ceremonies and traditions, including religious observance. Just look at the religious leaders invited to attend the cenotaph.

**Comment by PaulJRobinson** [comment]
I think there should be much more provision for secular Remembrance services, yes. :+1:

**Comment by iconoclast86** [comment]
:hand:

**Comment by Floppy** [comment]
I agree as well; any event that is organised by a branch of government should be secular (not necessarily atheist!) in nature. :+1:

I will do a secondary PR to change some of the wording slightly to reflect that, but the principle is good.

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are a [contributor](https://votebot.openpolitics.org.uk/proposals/) to this repository (and not the proposer), you may vote on whether or not it is accepted. 

## How to vote
Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

|vote|symbol|type this|points|
|--|--|--|--|
|Agree|:thumbsup:|`:thumbsup:`|1|
|Abstain|:hand:|`:hand:`|-1|
|Block|:thumbsdown:|`:thumbsdown:`|-1000|

Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 7 days, but will be closed if the proposal is not accepted after 90.

Votes are counted [automatically here](https://votebot.openpolitics.org.uk/proposals/330), and results are set in the merge status checks below.

## Changes

If the proposer makes a change to the proposal, no votes cast before that change will be counted.

**Pull request merged**
