### PR TITLE
No party leader can stand as an MP

### PR DESCRIPTION
**Pull request by simonneb**
Allows party leaders to focus on the role of leading their party and, if successfully elected, the role of PM. Constituents get a proper representative in the House of Commons also.

### CODE REVIEW

**Comment by Floppy** [comment]
This is in line with existing ideas of separating legislature and executive, and it could start with this. Might need adjusting to fit together with that policy, but I'm in favour of the idea.

Should it be "wants to become" though? Maybe just trigger byelection after leadership contests decide a new leader?

Interestingly, this would prevent me (any many other founders of small parties) ever standing for election again - should there be something to qualify this in major parties only?

**Comment by Xyleneb** [comment]
If your party thinks that they can do both, then why not let them try to do both?
Better representation is what's in it for me apparently, but I kinda like how they're expected to prove their worth by being electable somewhere. I can't see there being much to gain from forbidding it.

**Comment by Autumn-Leah** [comment]
I don't see the issue with a party leader also representing constituents, since the constituents did infact vote for said leader. Them being leader doesn't erase that.

Vote: ❎

**Comment by simonneb** [comment]
all good points,this needs some more finessing. i will retract and come back to it later.

**Pull request closed without merging**
