### PR TITLE
City of London Reform Policies 2

### PR DESCRIPTION
**Pull request by andrewdwilliams**
Second try, this time in democracy as opposed to society. Several policies at once about radical reform of the City of London, because, believe me, radical reform is necessary. Follows on from #347. Policies like abolishing the City of London Police can also be placed under Crime and Justice.

### CODE REVIEW

**Comment by philipjohn** [comment]
:+1: 

Ignore everything in the changes except the "City of London" section - the rest is a bug of our Manifesto editor.

**Comment by andrewdwilliams** [comment]
Bump. @tmtmtmtm @Floppy @h2g2bob Thoughts?

**Comment by Floppy** [comment]
Oh, yes, I'm in. :+1:

**Comment by Floppy** [comment]
I'll sort out the conflicts and merge this one in. For now, as the project has been very quiet since the election, I'm ignoring the 90-day cutoff if discussion is becoming active again.

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are a [contributor](https://votebot.openpolitics.org.uk/proposals/) to this repository (and not the proposer), you may vote on whether or not it is accepted. 

## How to vote
Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

|vote|symbol|type this|points|
|--|--|--|--|
|Agree|:thumbsup:|`:thumbsup:`|1|
|Abstain|:hand:|`:hand:`|-1|
|Block|:thumbsdown:|`:thumbsdown:`|-1000|

Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 7 days, but will be closed if the proposal is not accepted after 90.

Votes are counted [automatically here](https://votebot.openpolitics.org.uk/proposals/360), and results are set in the merge status checks below.

## Changes

If the proposer makes a change to the proposal, no votes cast before that change will be counted.

**Pull request merged**
