### PR TITLE
Sex worker rights, brothel regulation, prevention of human trafficking

### PR DESCRIPTION
**Pull request by Autumn-Leah**
If I were to add a description here I'd end up restating the whole policy

### CODE REVIEW

**Comment by philipjohn** [comment]
Vote: ✅

**Comment by Floppy** [comment]
Is there a campaign we can link to that backs up the policy? I don't feel qualified currently to pass judgement on whether or not it's a good idea, because I know nothing of that community and the deeper background.

**Comment by Autumn-Leah** [comment]
https://en.wikipedia.org/wiki/Pornography_in_the_United_Kingdom#Current_situation
https://en.wikipedia.org/wiki/Prostitution_in_the_United_Kingdom#Reform_of_prostitution_laws
https://en.wikipedia.org/wiki/Prostitution_in_the_United_Kingdom#Current_legal_status

this is a good TL;DR

**Comment by Floppy** [comment]
Thanks. Would be good if we can link to some of the ECP recommendations, but I can't actually find any on their site. Hmm.

Vote: ✅

**Comment by Xyleneb** [comment]
I don't think it's a good idea. European countries have tried it (the state licensed brothels thing) and it's ended up creating less of a "safe space" and more of a target for traffickers to gravitate towards. The system we have as it stands is good, if not the best then certainly amongst them.

**Comment by Autumn-Leah** [comment]
The system we have as it stands is awful. Sex workers don't get institutionalised protection like a brothel would have to provide, they're widely discriminated against in both society and in criminal matters, and if anything saying "it'll be a target for traffickers" is the least sensible thing to say without providing any evidence. If you're that worried about trafficking I'd be find with editing the policy to make the government run and police guarded but I figured that'd spark outcries of "think of the children" and "the government are perpetuating sexual immorality" and other forms of meaningless and baseless appeals to emotion. That usually wouldn't bother me, but chances are it could make us unelectable, but we have to do *something* in favour of sex workers.

**Comment by philipjohn** [comment]
@Xyleneb Are you able to point to any sources on that so we can see what's happening in countries that have decided to legalise and regulate?

**Comment by Xyleneb** [comment]
>The system we have as it stands is awful. Sex workers don't get institutionalised protection like a brothel would have to provide, they're widely discriminated against in both society and in criminal matters, and if anything saying "it'll be a target for traffickers" is the least sensible thing to say without providing any evidence. If you're that worried about trafficking I'd be fine with editing the policy to make them government run and police guarded but I figured that'd spark outcries of "think of the children" and "the government are perpetuating sexual immorality" and other forms of meaningless and baseless appeals to emotion. That usually wouldn't bother me, but chances are it could make us unelectable, but we have to do something in favour of sex workers.

Our cities are the size of other countries, spanning population densities of 4,000 people per square kilometer (for example, greater manchester I think is comparable to lithuania). Yet our support for sex workers is amongst the most efficient, most liberal, most focused on the job than nearly every other nation on the planet. If you're ashamed of that then it's because you have high standards (and I don't blame you). What I think we can do for sex workers is replace solicitation bans with 'solicitation licensing'. Leeds tried something similar (a solicitation amnesty) with moderate improvements across the board: http://archive.is/P0BJ2 also there is this similar article concerning dutch 'streetwalking zones': http://archive.is/bXGmW

Brothels are a bigger problem than that though in terms of NIMBYs and in terms of interfering with income and personal security. You can have specialized police patrolling the brothels all you want, but workers and clients alike have to travel to and from there. Initiatives that mean well, even when they're designed to take the workers into account can end up interfering with what is usually to them a vital means of income.

>Are you able to point to any sources on that so we can see what's happening in countries that have decided to legalise and regulate?

I did look for stuff specifically relating to brothels, this was all I could find though: http://link.springer.com/article/10.1007%2Fs10611-013-9512-4

I can tell you "what I've heard" as well:
Negative stories about the Dutch system, mixed stories about the German system, and positive stories coming from New Zealand. Of note; New Zealand has a much smaller population density.

**Comment by Autumn-Leah** [comment]
That suggeston of a relaxing of solicitation law still does nothing for social or legal discrimination and institutionalised protection from non-sexual and sexual violence.

**Comment by Xyleneb** [comment]
>the suggestion of a relaxing of solicitation law still does nothing for social or legal discrimination
How many employers, nevermind brothels, just regular employers of workers.. How many of those provide adequate social and legal support for their employees?

Not many do. In spite of the fact that many of them are legally mandated to provide that support.

Also you're proposing that licensed brothels will legitimize or normalize the industry in the eyes of the public. I'm not sure that's happened in the Netherlands, though.

**Comment by Autumn-Leah** [comment]
> How many employers, nevermind brothels, just regular employers of workers.. How many of those provide adequate social and legal support for their employees?

> Not many do. In spite of the fact that many of them are legally mandated to provide that support.

This just means enforcement of the laws need to get better, not that it's a bad idea.

> Also you're proposing that licensed brothels will legitimize or normalize the industry in the eyes of the public. I'm not sure that's happened in the Netherlands, though.

Along with the outreach campaigns I think it's better than nothing on the cultural front, which is what we have now. What's going on in the Netherlands and can you source it?

**Comment by Xyleneb** [comment]
>This just means enforcement of the laws need to get better, not that it's a bad idea.

The Dutch and the Germans have both legalised brothels, and have reasonable law enforcement to back it up. Yet it still hasn't stopped a bunch of eastern europeans being funnelled through these industries.

>Along with the outreach campaigns I think it's better than nothing on the cultural front, which is what we have now. What's going on in the Netherlands and can you source it?

I'd be surprised if "I'm just off to mcdonalds" and "I'm just off to the brothel" will ever be held in the same cultural equivalency. But, if you want to look into it, there are plenty of (anecdotal) articles of interviews between the press and the sex workers in the netherlands. You end up having to google things like "netherlands prostitute interview" though. Most of them say things like "they were promised a job without being told exactly what the nature of what it was". Which is embedded in the nature of these businesses unfortunately.

I think you're underestimating or not considering the NIMBYs as well, which leads to them punishing you come voting time.

**Comment by Autumn-Leah** [comment]
> The Dutch and the Germans have both legalised brothels, and have reasonable law enforcement to back it up. Yet it still hasn't stopped a bunch of eastern europeans being funnelled through these industries.

Evidence?

> But, if you want to look into it, there are plenty of (anecdotal) articles of interviews between the press and the sex workers in the netherlands.

Who will be undoubtedly self selected. The press like drama, if a sex worker is having issues with a recently passed policy, they're gonna jump on it like a cat on freshly cooked cod.

**Comment by Xyleneb** [comment]
>Evidence?

From the third link I left here: "The prostitution business retains many characteristics of an illegitimate market and the legalization and regulation of the prostitution sector has not driven out organized crime. On the contrary, fighting sex trafficking using the criminal justice system may even be harder in the legalized prostitution sector."

>Who will be undoubtedly self selected. The press like drama, if a sex worker is having issues with a recently passed policy, they're gonna jump on it like a cat on freshly cooked cod.

The Dutch and German systems have been crafted over a great many years, I think only the German "stop-offs system" is recent (if you're wondering what that is, it's like a public drive-in sex work & wash facility, with bins that handle dirty needles and stuff). Also from what little I looked at it (I think this policy is at least 5 years old and I looked at it equally "long ago") there were some good things to be said about them. They work. Modest successes again, but they do allegedly work. I think the reason they work is because they're not run with a pimp or a madam trying to make a profit. The police and social workers run the joint. The workers get help with their addictions and they keep their money.

>What do you mean by this?

Not In My Back Yarders. Would *you* want a brothel outside your house?

The problem is not so much the sex workers as the auxilliary businesses that sprout up around them.

Anyway, I've said my bit. You could change the bill with the recommendations I've given and I'd vote in favour. But if I can't convince you or floppy et al not to bank on this working then you might as well go for it. The argument for a change in policy will have to be made at a later date.

**Comment by Autumn-Leah** [comment]
@Xyleneb, I meant how am I underestimating the NIMBYs, I know what it stands for.

**Comment by Floppy** [comment]
This is currently passing, so it'll be merged. @xyleneb, maybe it would be a good idea to do a second iteration with your recommendations so we can vote on them specifically?

Vote: ✅

**Comment by Autumn-Leah** [comment]
@Floppy good idea, looking at it again after 2 days, I think I may make a few adjustments myself.

**Pull request merged**
