### PR TITLE
Council Tax

### PR DESCRIPTION
**Pull request by merrows**
Council Tax is now higher than at any time since the 14th century.

### CODE REVIEW

**Comment by philipjohn** [comment]
Thanks for the contribution @merrows ! I feel like this could be beefed up a bit more - what would you suggest we do to reform council tax?

**Comment by merrows** [comment]
A manifesto statements needs to high level and brief to allow for implementation without being overly restrictive (due to the prospect of law/politics changing). 
  
 Presently the relevant law is as follows - 
  The Council Tax Reduction Schemes (Default Scheme) (England) Regulations 2012  This law gives local councils the rights to raise money as they see fit locally. Many councils (mainly Tory) used this new law to push tax burdens to the poorest people and most of the previous protections were removed. That meant even unemployed people were forced to pay council tax of serve a prison term. Additional to this is that the offence of culpable neglect was given a new interpretation of buying food. 
  
 Previously the offence was applied to people who had money and refused to pay tax. But following 2012, the new interpretation was made by local government that poor people should use foodbanks and use money previously used to buy food to pay tax.
  
 Locally in Southend these changes meant 10,000 people were prosecuted (in a population of 90,000) and nationally several million have been prosecuted. If they all were jailed, the UK prison population would increase by 20 times.
  
 To include so much detail in a manifesto is impossible.
  
 The best solution is to open the wording up for debate. But the political decision is as a political group/party do you think tax should be progressive or flat.
  
 A progressive tax will consider an ability to pay. A flat tax will not. 
  
 With a flat tax system (pushed for by conservatives) someone will be forced to donate to the Crown a fixed sum of money either as a actual amount or a percentage, eg everyone pays 30% or everyone pays 30K. If your income is only 20K you still pay 30K in tax. It means you have to sell goods or borrow to pay tax and then use foodbanks. Failure to comply would mean a prison term. If a percentage is applied, someone with an income of 5000 pays 30% and someone with an income of 5 million also pays 30%. 
  
 A progressive system will have variable rates according to someone's ability to pay. 
  
 Possible more detailed wording.
  

 Tax should be fair by nature. The population may not be unduly or unfairly taxed. People below the official poverty line as defined by the Government should be exempt from taxation. 
  
  

----------------------------------------

**Comment by philipjohn** [comment]
There's some great detail there. It sounds like what you're getting at is a local income tax. Perhaps proposing that more specifically might work better?

Also, note that there is already a policy to [replace council tax with a land value tax](http://openpolitics.org.uk/manifesto/economy.html#land-value-tax), so that would need to be taken into account/updated.

Or maybe just a change is needed to the LVT proposal? See the [original discussion about introducing LVT](https://github.com/openpolitics/manifesto/pull/250).

**Comment by merrows** [comment]
I had not seen the LVT. I think that would be an ideal replacement for the dreaded council tax. Can't see the Tories liking a tax on land values!
  
 On a more general point, I think lowering taxes is essential to reduce the burden already placed on the private sector. Of course, the very public issue of tax avoidance allowing the super rich to completely avoid tax raises a set of issues which even the Tories have finally recognised. Nothing is stopping someone just registering the land ownership to a company in the BVI or somewhere like that and then claiming they are exempt.
  
  
  

----------------------------------------

**Comment by philipjohn** [comment]
Oh excellent! :smiley:

**Comment by merrows** [comment]
I added some suggestions in the legal part. There is a growing body of opinion that the Court needs to be modernised. One key aspect of this is that the Government presently has limited control over it from a legal standpoint. 
  
  
  
  

----------------------------------------

**Comment by merrows** [comment]
I am unsure of your system, so I just emailed you again - I added a few suggestions in the law part. I think generally more of a US style of law is needed which provides a core protection under constitutional law. 
  
  

----------------------------------------

**Comment by philipjohn** [comment]
Yep, looks like those are #402 and #403 😃

**Comment by merrows** [comment]
I am not sure about the degree of penetration you have into political markets. I think the issue of diversity and representation especially relating to minorities is important today. 
  
 If you have any real prospects of influence, I would be interested to do more within your group.
  
 I live in Westcliff and locally the are a number of issues. 
  
 The politicians have in effect created a environment which is controlled by a few people. Julian in Labour basically runs it and if fall out with him then you are out, and Martin Terry was a controller of the independents (but that seems to be changing). The Tories seems hard to ascertain - it is not that clear who runs them, as they never seem to be make anything clear. They tend to make vague statements and then expect departments to have all the power. 
  
 The outcome of this type of politics is that whole areas of geography are ignored - soaring crime rates, poverty, corruption are now all big issues. Corruption especially now is an issue. There is also a growing dominance of the corporate sector with huge retail parks taking trade from small shops and dozens of the express stores run by corporations. 
  
 Homelessness is a very widespread issue and beggars are seen throughout key shopping areas. 
  
  
  
  
  

----------------------------------------

**Comment by Floppy** [comment]
Hi @merrows - this isn't the right place for general discussion, but if you're interested in doing more and finding out more what we're about, come and have a chat in our forum at http://discourse.somethingnew.org.uk. See you there :)

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are a [contributor](https://votebot.openpolitics.org.uk/proposals/) to this repository (and not the proposer), you may vote on whether or not it is accepted. 

## How to vote
Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

|vote|symbol|type this|points|
|--|--|--|--|
|Agree|:thumbsup:|`:thumbsup:`|1|
|Abstain|:hand:|`:hand:`|-1|
|Block|:thumbsdown:|`:thumbsdown:`|-1000|

Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 7 days, but will be closed if the proposal is not accepted after 90.

Votes are counted [automatically here](https://votebot.openpolitics.org.uk/proposals/394), and results are set in the merge status checks below.

## Changes

If the proposer makes a change to the proposal, no votes cast before that change will be counted.

**Pull request closed without merging**
