### PR TITLE
legalise Humanist marriage

### PR DESCRIPTION
**Pull request by andrewedmondson**

### CODE REVIEW

**Comment by yellowgopher** [comment]
I think this is part of a wider debate to legalise marriages for any groups/religions (again we shouldn't specifically name where we can avoid it).  Proviso that they are registered in some way so it doesn't become a complete free-for-all that cannot be audited/traced!

**Comment by andrewedmondson** [comment]
Legalising Humanist weddings is a specific issue that Downing Street 
blocked despite 95% of those consulted wanting them. So I think it is 
valid.

**Comment by yellowgopher** [comment]
Widen it out - allow any groups to marry - why focus on just one group?

**Comment by Floppy** [comment]
Agreed, we can probably widen the wording here and include humanist and others as examples. Would that work?

**Comment by andrewedmondson** [comment]
Marriage is a legal contract that must be overseen by an official. Are 
you saying that anyone should be able to officiate?

**Comment by andrewedmondson** [comment]
Yes that would do. But there is a reason for mentioning Humanism, i.e. 
the 95% of those consulted in favour.

**Comment by yellowgopher** [comment]
I think I said any group wishing to officiate should be registered/vetted in some way.  I am happy for examples to be mentioned.
Lol!  Just thought.  We could have an independent committee that reviews groups that can apply to officiate their own weddings.  Welcome to the new world of quangos!

**Comment by Floppy** [comment]
How are those groups currently vetted? Is it just civil registrars and religious organisations only at the moment?

**Comment by andrewedmondson** [comment]
Catholic weddings are not legal. But they have a special dispensation. 
Two registrars hang around in the back of the church for the happy 
couple to be married proper.


On 14/04/2015 16:14, yellowgopher wrote:
>
> I think I said any group wishing to officiate should be 
> registered/vetted in some way. I am happy for examples to be mentioned.
> Lol! Just thought. We could have an independent committee that reviews 
> groups that can apply to officiate their own weddings. Welcome to the 
> new world of quangos!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/openpolitics/manifesto/pull/331#issuecomment-92898354>.
>

-- 
Andrew Edmondson

079 3450 8671
West Sussex Humanists <http://www.westsussexhumanists.org.uk>
BHA logo <http://www.humanism.org.uk/>

**Comment by andrewedmondson** [comment]
Looks like Catholic marriages are legal. My mistake. Someone told me 
they weren't. Here's Wikipedia:

 From the Marriage Act 1753 
<http://en.wikipedia.org/wiki/Marriage_Act_1753><http://en.wikipedia.org/wiki/Marriage_Act_1753> 
until 1837, only marriages conducted by the Church of England, Quakers 
<http://en.wikipedia.org/wiki/Quakers><http://en.wikipedia.org/wiki/Quakers>, 
or under Jewish 
<http://en.wikipedia.org/wiki/Jew><http://en.wikipedia.org/wiki/Jew> 
law, were recognised in England and Wales 
<http://en.wikipedia.org/wiki/England_and_Wales><http://en.wikipedia.org/wiki/England_and_Wales>. 
This was changed by the Marriage Act 1836 
<http://en.wikipedia.org/wiki/Marriage_Act_1836><http://en.wikipedia.org/wiki/Marriage_Act_1836> 
which, in addition to introducing civil marriage 
<http://en.wikipedia.org/wiki/Civil_marriage><http://en.wikipedia.org/wiki/Civil_marriage>, 
also allowed ministers of other faiths (Nonconformists 
<http://en.wikipedia.org/wiki/Nonconformist><http://en.wikipedia.org/wiki/Nonconformist> 
and Roman Catholics 
<http://en.wikipedia.org/wiki/Roman_Catholic><http://en.wikipedia.org/wiki/Roman_Catholic>) 
to act as registrars.



On 14/04/2015 16:15, James Smith wrote:
>
> How are those groups currently vetted? Is it just civil registrars and 
> religious organisations only at the moment?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/openpolitics/manifesto/pull/331#issuecomment-92899733>.
>

-- 
Andrew Edmondson

079 3450 8671
West Sussex Humanists <http://www.westsussexhumanists.org.uk>
BHA logo <http://www.humanism.org.uk/>

**Comment by yellowgopher** [comment]
I think they have to apply for a license so I guess they are vetted in some way!

**Comment by yellowgopher** [comment]
Can this be made more generic - i.e. allow any groups/organisations to apply for a license to carry out marriage ceremonies.  I think I would be (generally) accepting of this!  ;-)

So, what do I do here guys, I am sort of accepting of this proposal but with a few modifications.  Do I block (like people have tended to do to me... LOL) or do I just wait and see...?

**Comment by andrewedmondson** [comment]
What would be the criteria for giving the license?

On 15/04/2015 12:32, yellowgopher wrote:
>
> Can this be made more generic - i.e. allow any groups/organisations to 
> apply for a license to carry out marriage ceremonies. I think I would 
> be (generally) accepting of this! ;-)
>
> So, what do I do here guys, I am sort of accepting of this proposal 
> but with a few modifications. Do I block (like people have tended to 
> do to me... LOL) or do I just wait and see...?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/openpolitics/manifesto/pull/331#issuecomment-93338502>.
>

-- 
Andrew Edmondson

079 3450 8671
West Sussex Humanists <http://www.westsussexhumanists.org.uk>
BHA logo <http://www.humanism.org.uk/>

**Comment by yellowgopher** [comment]
What are the criteria now?

**Comment by philipjohn** [comment]
I agree with the proposal wholeheartedly but the whole debate here seems kinda bizarre - why does the state have to sanction marriages? Why is it the state's business whether or not we marry, to who, and by whom?

Why don't we just 'liberalise' marriage?

**Comment by andrewedmondson** [comment]
Because a marriage is a legal contract.

**Comment by philipjohn** [comment]
> Because a marriage is a legal contract.

Why do we need a legal contract to confirm our love for another?

**Comment by andrewedmondson** [comment]
Many people have weddings without getting married.

Marriage is a protection for both parties and any children they might 
have. It has many implications, e.g. tax, inheritance.

Before you scrap legal marriage, you need to look at the implications to 
society.



On 19/04/2015 21:28, philipjohn wrote:
>
>     Because a marriage is a legal contract.
>
> Why do we need a legal contract to confirm our love for another?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/openpolitics/manifesto/pull/331#issuecomment-94310686>.
>

-- 
Andrew Edmondson

079 3450 8671
West Sussex Humanists <http://www.westsussexhumanists.org.uk>
BHA logo <http://www.humanism.org.uk/>

**Comment by PaulJRobinson** [comment]
Whilst I'm tempted by @philipjohn's libertarian argument that "who the hell is the state to say whether or not my marriage is legit" we have to accept that marriage does have implications for the legal status of each party. We're not here (on this proposal at least) to discuss the rights and wrongs of whether or not marriage is/should be a legal contract - at the moment it is. And I think anyone from any group or body or religion should be able to get a licence to marry people. Like other commenters I'm not in favour of specifying 'Humanist' or 'Catholic' or anyone else. Let's keep it generic and open.

**Comment by philipjohn** [comment]
> It has many implications, e.g. tax, inheritance.

> marriage does have implications for the legal status of each party

*Because* the state makes it so.

> We're not here (on this proposal at least) to discuss the rights and wrongs of whether or not marriage is/should be a legal contract.

I'd contest that - this proposal is suggesting adding to a situation where the state is imposing conditions on people based on tradition. We can either add to that, or reject that as illiberal. I'm suggesting we should reject this proposal and instead do something far more liberal and radical.

**Comment by Floppy** [comment]
Can I suggest something here? There is clear support and no real reason to not make humanist marriage legal. We are falling into the same trap here that the government did that by aiming for the perfect redefinition of who can perform marriages, they deny the good and easy fix. I think we can accept this, and then work on a wider redefinition later. :+1: from me on that basis.

**Comment by yellowgopher** [comment]
Yep, on balance, I agree. :+1: Hopefully it can be redefined into a more "all emcompassing" policy later.

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are a [contributor](https://votebot.openpolitics.org.uk/proposals/) to this repository (and not the proposer), you may vote on whether or not it is accepted. 

## How to vote
Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

|vote|symbol|type this|points|
|--|--|--|--|
|Agree|:thumbsup:|`:thumbsup:`|1|
|Abstain|:hand:|`:hand:`|-1|
|Block|:thumbsdown:|`:thumbsdown:`|-1000|

Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 7 days, but will be closed if the proposal is not accepted after 90.

Votes are counted [automatically here](https://votebot.openpolitics.org.uk/proposals/331), and results are set in the merge status checks below.

## Changes

If the proposer makes a change to the proposal, no votes cast before that change will be counted.

**Pull request merged**
