### PR TITLE
Restrict UK benefits for recent immigrants

### PR DESCRIPTION
**Pull request by Bjorks**

### CODE REVIEW

**Comment by Floppy** [comment]
I'm not sure that buying into the narrative of false problems helps us. In a bit of "argument ad absurdum" or whatever it's called, we could take a strong stance against alien invasion from Mars, but it wouldn't add anything useful.

There are plenty of parties joining UKIP's narrative; I don't think we need to do that here. :-1: from me purely on the basis of trying to avoid lending credibility to illusory problems. Perhaps that's naïve.

**Comment by Bjorks** [comment]
You can see that the idea I have mooted is now mainstream and it is not A UKIP policy. It's fair to restrict recent eu immigrant access to uk benefits for a time to prevent abuse. It's frustrating that the response to my idea at the time was slam dunked as a right wing absurd idea - because it isn't.

**Comment by Floppy** [comment]
Sorry if you feel it was slam dunked for being a right-wing idea, that wasn't my intention, certainly, and I don't think I implied it - apologies if I did. I was simply trying to discuss whether it was a problem that actually needed solving, that's all. All comments are meant constructively in the spirit of open debate.

The link above (http://www.housing-rights.info/habitual-residence-test.php) discusses what restrictions on benefits for new migrants already exist - are you proposing more than that in terms of minimum period of residence?

Once again though (and again, constructively), I'd say that simply because an idea is mainstream does not make it a real issue.

**Comment by Floppy** [comment]
Closing this one, as we're over the 90-day limit with no further movement. Feel free to resubmit if you want to reopen the debate!

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are a [contributor](https://votebot.openpolitics.org.uk/proposals/) to this repository (and not the proposer), you may vote on whether or not it is accepted. 

## How to vote
Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

|vote|symbol|type this|points|
|--|--|--|--|
|Agree|:thumbsup:|`:thumbsup:`|1|
|Abstain|:hand:|`:hand:`|-1|
|Block|:thumbsdown:|`:thumbsdown:`|-1000|

Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 7 days, but will be closed if the proposal is not accepted after 90.

Votes are counted [automatically here](https://votebot.openpolitics.org.uk/proposals/233), and results are set in the merge status checks below.

## Changes

If the proposer makes a change to the proposal, no votes cast before that change will be counted.

**Pull request closed without merging**
