### PR TITLE
More confident wording, and slight addition

### PR DESCRIPTION
**Pull request by philipjohn**
This changes the wording a bit to be more confident and also demonstrates one of the nasty things we'll get rid of.

### CODE REVIEW

**Comment by Floppy** [comment]
:+1:

**Comment by Xyleneb** [comment]
I think the constitutional reforms on the books at the moment are too deep-cutting, such that they will scare the public and reduce cross-party support. But this particular amendment isn't too bad :thumbsup:

**Comment by andrewdwilliams** [comment]
:+1: also @Xyleneb if you want to open an issue on constitutional reforms that you aren't too fond on, I'm happy to get involved in that discussion.

**Comment by Xyleneb** [comment]
>also @Xyleneb if you want to open an issue on constitutional reforms that you aren't too fond on, I'm happy to get involved in that discussion.

Ok I'll see what I wrote down a couple years ago and compare it to what's on the books. Constitutional reforms may have already (finally) happened in the time since though and made my scribbles a bit irrelevant.

**Pull request merged**
