### PR TITLE
Various education proposals

### PR DESCRIPTION
**Pull request by yellowgopher**
Funding.  Move to pupil based funding approach.
Local Schools.  Remove Secular Schools and add in Local Schools - approach to allow communities to develop the schools they wish to see and legislation to ensure schools are developed in the way the community want them to be.
School Governance.  Added in governing body representation from Local Schools.  Advise student president should be a co-opted (non-voting) member on governing body to avoid any legal issues surrounding liability etc.

### CODE REVIEW

**Comment by philipjohn** [comment]
I really don't think we should remove any of that secular schools section at all - can you help me understand your rationale for removing that please?

I'm also unconvinced for the reasoning for expanding the free schools and academies program. Free schools are [already providing places that aren't needed](http://www.theguardian.com/education/2014/dec/27/free-schools-failure-attract-pupils-crisis-labour), diverting state funding from areas that have a real need for more school places. Could you evidence the change for that as well please?

**Comment by Floppy** [comment]
Could we separate this into separate proposals as well? There are a number of things which we could get in more easily separately, I think. I will do this when I get time, unless someone else gets there first.

**Comment by yellowgopher** [comment]
Yep, ok.  You will have to forgive me – I’m learning the process – will attempt to just suggest one idea for each proposal moving forward!

**Comment by Floppy** [comment]
No problem at all, thanks very much for contributing! All suggestions are intended to be constructive, so I hope you're finding the experience bearable :)

**Comment by yellowgopher** [comment]
Of course!  I am very happy to be put right!  It’s good that the debate can be had… :)

**Comment by PaulJRobinson** [comment]
Some good stuff here. Agree it needs to be broken into smaller proposals to make it voteable.

**Comment by yellowgopher** [comment]
Right, sorry for the delay in doing this.  Have split each item out.  Happy to debate!

**Comment by yellowgopher** [comment]
LOL!  I seem to have lost all my changes from last week!  Where have they gone?  What did I do wrong?

**Comment by Jypsijen** [comment]
Include curriculum options

**Comment by Floppy** [comment]
Hi @Jypsijen! Best way to get involved is to just start hitting the edit button on one of the pages under http://openpolitics.org.uk/manifesto and add whatever you feel strongly about! It should guide you through. Incidentally, if you're moving to Churt, you will have a candidate standing on this manifesto in the election, assuming you get there in time :)

**Comment by yellowgopher** [comment]
Right, think I know where I went wrong - so now definitely split out!  I guess this can now be closed off?

**Comment by Floppy** [comment]
great, yes. Thanks! :)

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are a [contributor](https://votebot.openpolitics.org.uk/proposals/) to this repository (and not the proposer), you may vote on whether or not it is accepted. 

## How to vote
Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

|vote|symbol|type this|points|
|--|--|--|--|
|Agree|:thumbsup:|`:thumbsup:`|1|
|Abstain|:hand:|`:hand:`|-1|
|Block|:thumbsdown:|`:thumbsdown:`|-1000|

Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 7 days, but will be closed if the proposal is not accepted after 90.

Votes are counted [automatically here](https://votebot.openpolitics.org.uk/proposals/261), and results are set in the merge status checks below.

## Changes

If the proposer makes a change to the proposal, no votes cast before that change will be counted.

**Pull request closed without merging**
