### PR TITLE
No Cash for Access

### PR DESCRIPTION
**Pull request by Xyleneb**
I hope this will be a worthwhile policy.

### CODE REVIEW

**Comment by philipjohn** [comment]
:+1: if it's not already?

**Comment by Xyleneb** [comment]
>if it's not already?
It could prove to be fairly unenforceable or "limp-wristed", because political parties regularly take donations and in criminal proceedings the burden of proof is "beyond doubt".

**Comment by Floppy** [comment]
👍 definitely worth being explicit on it :)

**Comment by andrewdwilliams** [comment]
:+1: always good to be explicit

**Pull request merged**
