### PR TITLE
Accountability of elected representatives

### PR DESCRIPTION
**Pull request by Autumn-Leah**
If you've pissed off 30% of people in your constituency to the point that they're willing to sign a petition against you continuing your role, you're probably doing a terrible job, though I'm up for debating the exact numbers.

### CODE REVIEW

**Comment by Xyleneb** [comment]
I think it's worth giving a constitutional protection or two a try.

Vote: :white_check_mark:

You can always debate the numbers later. I could see a few other issues with it:
Politicians that do unpopular things might otherwise redeem themselves. Legislation like this is weak unless you list penalties for not adhering. Petitions, particularly electronic ones are susceptible to forgery.

The second one is probably the most critical. The rest are debates you could probably have as the need arose.

**Comment by simonneb** [comment]
I guess there is a risk if the % is too low that you could get caught in a continual cycle of elections with two sides vetoing each others candidates constantly. Con and Lab both got 40% of the GE vote. maybe a threshold above 50% would be better?

:zipper_mouth_face:

**Comment by philipjohn** [comment]
Vote: ✅

**Comment by Floppy** [comment]
I agree, but we already have a statement on recall on the elections page. This is better and has more detail, but we need to match them up. See https://openpolitics.org.uk/manifesto/elections.html#recall-of-representatives

**Pull request merged**
