### PR TITLE
Update contribution rules

### PR DESCRIPTION
**Pull request by Floppy**
This changes the contribution rules in a couple of important ways, and improves the layout and wording of the rest of the guide. This is based on experience of the system over the last year or so, and a desire to make things move more quickly.

Changes to voting:

1. Only two existing contributors are needed to pass something. This is no longer based on a percentage of existing contributors. We have enough active members that incompatible ideas will be blocked before being merged.
2. Reduce minimum open vote time to a week. Two weeks is long enough for things to grind to a halt, one week should increase momentum. In my experience, consensus forms quickly or not at all. A week is enough.
3. Changes will be closed after 3 months if they're not merged, to keep the backlog clean and remove the interference from other old PRs hanging around.
4. Changes will be automatically merged on passing by the script so that admins can't sit on approved changes if they're not 100% happy with them. Block or pass.

We should also be encouraging blockers to counter with their own proposal, or if blocking for reasons of "this isn't detailed enough", to allow the change and build on it in future PRs.

This PR will be merged using the existing system, which means we need 5 yes votes to pass it.

### CODE REVIEW

**Comment by Floppy** [comment]
Pinging @PaulJRobinson @philipjohn @digitalWestie @tmtmtmtm @yellowgopher @rufflemuffin @BenTrimble @frabcus

As our most recent contributors, you guys are most likely to have opinions on this change, and we need your votes :)

**Comment by tmtmtmtm** [comment]
> "We should also be encouraging blockers to counter with their own proposal, or if blocking for reasons of "this isn't detailed enough", to allow the change and build on it in future PRs

I disagree with this: I thought the aim was to avoid policy based purely on ideology? Where no justification whatsoever is provided for a policy, for example, it should *always* be acceptable to say "this needs more information". 

(The version in the PR itself is somewhat better as it refers to "partial *improvements*". (Emphasis mine))

**Comment by Floppy** [comment]
Yes, take the version in the PR as the important one, but I see what you mean there. I really want to say that if we know something is basically good, but would benefit from expansion, we encourage adoption and improvement in subsequent PRs. Iteration over big bang. Does the proposed text do that, ignoring my bastardisation of it in the description, do you think?

**Comment by tmtmtmtm** [comment]
I think the text in the PR itself is OK; but it would be better if applied in parallel with something for #71

**Comment by tmtmtmtm** [comment]
> If the script detects that a change has been passed, it will be merged automatically

I suspect there should be at least some delay between the final 'yes' vote, and the auto-merge.

**Comment by philipjohn** [comment]
Firstly, +10 manifesto points for mentioning #71 (there's no badge/prize/whatever, sorry)

I thought briefly about whether we could do something around that. We would perhaps have to rely on the voters to be blocking something that isn't evidenced well (within reason) though.

> I suspect there should be at least some delay between the final 'yes' vote, and the auto-merge.

My interpretation is that a change would get merged after one week if it's passing the criteria. Are you suggesting that if, for example, the required votes happen on day 7, the merged should be delayed by X amount of time. I.e. "merge after 7 days if last vote was less than X ago"

**Comment by tmtmtmtm** [comment]
yes — or even later. I'm thinking here of a scenario where, after 7 days, there has only been one yes vote. Then, a week later (say) there's a second yes vote — at which point (by my reading of this), the change will get merged straightaway. I'd like to see even a 24-hour delay or so here, to allow people time to react to it. Yes, everyone should have been paying constant attention, and all that, but still...

**Comment by philipjohn** [comment]
> Yes, everyone should have been paying constant attention

Ha, it's all too easy to glance at a PR and then forget about it though, so it does make sense.

24 hours sounds good. I wonder if we could rig up the option for folks to be notified the moment a PR is 24hrs away from being merged.

**Comment by Floppy** [comment]
OK, yeah, fair enough. We could have the auto-merge have a secondary delay, though of course a manual merge could happen quicker. Do we want to have a minimum delay before merge, or would it be OK to do immediately on passing if a human does it?

**Comment by Floppy** [comment]
OK, I've updated the text to include a 24 hour delay after passing before auto-merge, and to make abstentions cancel an agreement. I think we will need to pass this under the proposed rules rather than the existing ones though, otherwise we'll stall completely.

**Comment by philipjohn** [comment]
:+1:

**Comment by Floppy** [comment]
@tmtmtmtm do you think this is OK now?

**Comment by tmtmtmtm** [comment]
Hmm. I suspect that someone looking at it fresh will likely be very confused as to why the 'hand' is a -1 count, and the '-1' is a halt...

**Comment by Floppy** [comment]
That's true, but unless we integrate to a more complex voting system, that's probably the best we can do. Unless we change block to something like :x:, perhaps.

**Comment by tmtmtmtm** [comment]
By 'more complex', you mean for the voter? Or for the code of the votebot? It's certainly not ideal to reverse the meanings, but if we *were* to do so, then now is likely to be better than at any time in the future. Making '-1' actually *mean* -1, and then taking 'hand' or 'X' to mean stop seems like it could avoid significant confusion later, and (with suitable handwaving) could be handled with date conditionals in the code for a while.

**Comment by Floppy** [comment]
I meant something like Loomio. I don't mind complex code in the votebot. I'd rather have a new set of symbols to avoid confusion though, especially when reading back. Do you think we could proceed with the current symbols to get the rules in place, and change the symbols as a separate PR?

**Comment by tmtmtmtm** [comment]
Ah, gotcha. That's a good point about being able to read historic PRs, so a slightly hesitant :+1: for now from me[1]. It would be good if we could produce a list of changes that will be affected by this, before merging though, so that people have a flurry of activity on ones that people have forgotten about.



[1] Aside from the oddness of the back-to-front signals, I'm also a little concerned that to "make things move more quickly" is potentially a step in the wrong direction. But I'm not sure how much of that is simply to do with mismatched expectations as to what a process like this *should* (IMO) be, and my thoughts on this aren't quite coherent enough yet to really express them in any detail. But I can live with that for now :)

**Comment by digitalWestie** [comment]
Seems legit :+1:

**Comment by PaulJRobinson** [comment]
:+1:

**Comment by philipjohn** [comment]
Pinging @yellowgopher @rufflemuffin @BenTrimble @frabcus as we just need another vote or two to get this in (if you agree)!

**Comment by yellowgopher** [comment]
OK, sounds reasonable to me. Need to get my head around this. Can I vote? Thought I wasn't eligible yet...!

**Comment by yellowgopher** [comment]
OK, sounds reasonable to me. Need to get my head around this. Can I vote? Thought I wasn't eligible yet...!

**Comment by philipjohn** [comment]
@yellowgopher My mistake, looks like you don't have an accepted proposal yet :(

**Comment by Floppy** [comment]
We have 4 votes out of 5 needed for this, but the fact we can't get another one to just shows how necessary it is. I'm going to be controversial and merge this with the 4 votes we have now, given that we've had a good debate and there is no opposition that we can get people to express. Will do so in a few hours, so you have chance to object to my blatant subversion of democracy.

**Comment by Floppy** [comment]
@mikera I thought you'd left us forever :smile:, but if you're around, I'd love to get your vote on this proposal to change the voting rules. We're slowing down a bit here, and need to re-inject some agility and energy!

**Comment by mikera** [comment]
:+1: I generally think getting changes in faster and iterating is a good idea.

**Comment by Floppy** [comment]
BOOM. And we're done. Thanks @mikera.

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are a [contributor](https://votebot.openpolitics.org.uk/proposals/) to this repository (and not the proposer), you may vote on whether or not it is accepted. 

## How to vote
Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

|vote|symbol|type this|points|
|--|--|--|--|
|Agree|:thumbsup:|`:thumbsup:`|1|
|Abstain|:hand:|`:hand:`|-1|
|Block|:thumbsdown:|`:thumbsdown:`|-1000|

Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 7 days, but will be closed if the proposal is not accepted after 90.

Votes are counted [automatically here](https://votebot.openpolitics.org.uk/proposals/270), and results are set in the merge status checks below.

## Changes

If the proposer makes a change to the proposal, no votes cast before that change will be counted.

**Pull request merged**
