### PR TITLE
Move Parliament out of the Palace of Westminster

### LINKED ISSUE #253: Move Parliament out of London
Need to write a proposal to move Parliament somewhere more northerly.<br><br>
via Email<br>
December 12, 2014 at 08:51PM

### PR DESCRIPTION
**Pull request by Floppy**
Resolves #253

### CODE REVIEW

**Comment by philipjohn** [comment]
Hell yes :+1:

**Comment by tmtmtmtm** [comment]
This one needs much more expansion, in terms of (a) why it should move at all, rather than simply repairing Westminster. In what way is Westminster "unsuited for the open and transparent operation of a modern democracy"? (b) why it should move out of London, and what the wider implications are of so doing (e.g. is the goal to create multiple capital cities, à la South Africa, or would other centres of government also move?); and (c) what the criteria for the new location should be.

**Comment by tmtmtmtm** [comment]
It's also worth looking at other countries who have moved their Parliament. The most recent one I know of is Georgia — who are now, only a few years later, looking at moving it back to Tbilisi again. It's a heavily politicised issue there, but there are undoubtedly useful lessons to be learned from it.

**Comment by PaulJRobinson** [comment]
I'm certainly in favour of a new building. But it's not just Parliament that is in Westminster. It's also the heart of Government. All the various ministries would need moving out of Whitehall as well - thousands of civil servants would need relocation compensation or redundancy. It would be a huge undertaking. The current repair project is likely to see Parliament relocated for 5 years, but I suspect it will be somewhere near Whitehall for the reason I set out above. :-1:

**Comment by philipjohn** [comment]
> All the various ministries would need moving out of Whitehall as well.

Yeah, and? ;)

**Comment by Floppy** [comment]
Perhaps I can split this up into a "new building" proposal and a "up north" proposal.

**Comment by Floppy** [comment]
I've tried to address the questions and concerns here. This no longer states where the new facility should be, just that one is required.

**Comment by Floppy** [comment]
Although, in response to @PaulJRobinson, much of the work of government is already spread around the country - it's by no means all in Westminster.

**Comment by philipjohn** [comment]
:+1:

**Comment by Floppy** [comment]
@frabcus you were in favour of this before I wrote the actual proposal - fancy adding your vote here?

**Comment by frabcus** [comment]
:+1:

**Comment by frabcus** [comment]
This is OK, and I've voted for it, but it is a bit dull now!

I agree that moving to, say, Manchester raises questions about central departments. I'd argue we should split Parliament from the administration. That then raises practical questions on how to do that in practice (ones that inevitably lead to thoughts of a presidential system, which nobody really wants or needs).

So needs much more thought on how exactly it would work.

**Comment by Floppy** [comment]
Yep, there are lots more questions to follow on from this one. Thanks for the vote! Now we just need @PaulJRobinson to agree to the simpler version, and we can move on.

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are a [contributor](https://votebot.openpolitics.org.uk/proposals/) to this repository (and not the proposer), you may vote on whether or not it is accepted. 

## How to vote
Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

|vote|symbol|type this|points|
|--|--|--|--|
|Agree|:thumbsup:|`:thumbsup:`|1|
|Abstain|:hand:|`:hand:`|-1|
|Block|:thumbsdown:|`:thumbsdown:`|-1000|

Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 7 days, but will be closed if the proposal is not accepted after 90.

Votes are counted [automatically here](https://votebot.openpolitics.org.uk/proposals/266), and results are set in the merge status checks below.

## Changes

If the proposer makes a change to the proposal, no votes cast before that change will be counted.

**Pull request closed without merging**
