### PR TITLE
Altered the R.E. section

### PR DESCRIPTION
**Pull request by Oeokosko**
See no need to even consider it in school - parents can and will organise R.E. themselves.

### CODE REVIEW

**Comment by tkvad** [comment]
I agree with Oeokosko, this is matter for individuals, not something for government to get involved with

**Comment by philipjohn** [comment]
:+1:

**Comment by Floppy** [comment]
:+1: from me also, I think specific religious instruction is best kept outside school.

**Comment by Floppy** [comment]
@Oeokosko thanks for this! Sorry the merge has stalled for so long; after the election everyone was very tired, I think, and we've been away a while :)

I'll merge this in, but can I get you to please agree to the CLA at http://www.clahub.com/agreements/openpolitics/manifesto? Thanks :D

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are a [contributor](https://votebot.openpolitics.org.uk/proposals/) to this repository (and not the proposer), you may vote on whether or not it is accepted. 

## How to vote
Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

|vote|symbol|type this|points|
|--|--|--|--|
|Agree|:thumbsup:|`:thumbsup:`|1|
|Abstain|:hand:|`:hand:`|-1|
|Block|:thumbsdown:|`:thumbsdown:`|-1000|

Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 7 days, but will be closed if the proposal is not accepted after 90.

Votes are counted [automatically here](https://votebot.openpolitics.org.uk/proposals/357), and results are set in the merge status checks below.

## Changes

If the proposer makes a change to the proposal, no votes cast before that change will be counted.

**Pull request merged**
