### PR TITLE
secular chaplaincy in the NHS

### PR DESCRIPTION
**Pull request by andrewedmondson**

### CODE REVIEW

**Comment by yellowgopher** [comment]
What are the privileges for religious chaplains?

**Comment by andrewedmondson** [comment]
They run the NHS chaplaincy. They are paid. They control eveything.

**Comment by yellowgopher** [comment]
Not true.
I know of many chaplains who are not paid!  A large number are voluntary.
And some who are paid but do not get anything like a "living wage".
It's a calling.  I have more sympathy for a chaplaincy service that doesn't over-represent particular faith groups but the NHS direction is to recruit in proportion to the make up of the local population - perhaps we should make this a legal requirement.

**Comment by andrewedmondson** [comment]
I didn't say they were all paid. The only ones that are paid are 
religious ones.

I agree that it is a calling. I have hosted talks by 3 chaplains over 
the years. The ppint is the religious control.

A recent development in the NHS is the chaplaincy service now being 
required to offer appropriate chaplaincy for all people. That's not 
going to happen until they pay non-religious chaplains.

Most NHS patients are unaware that there could be such a thing as a 
non-religious chaplain. They are not advertised.

The system is stacked in favour of religious chaplains.

In the armed forces it is worse.

And in prisons, well ...

On 14/04/2015 16:11, yellowgopher wrote:
>
> Not true.
> I know of many chaplains who are not paid! A large number are voluntary.
> And some who are paid but do not get anything like a "living wage".
> It's a calling. I have more sympathy for a chaplaincy service that 
> doesn't over-represent particular faith groups but the NHS direction 
> is to recruit in proportion to the make up of the local population - 
> perhaps we should make this a legal requirement.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/openpolitics/manifesto/pull/327#issuecomment-92896798>.
>

-- 
Andrew Edmondson

079 3450 8671
West Sussex Humanists <http://www.westsussexhumanists.org.uk>
BHA logo <http://www.humanism.org.uk/>

**Comment by yellowgopher** [comment]
Happy to tighten up the rules around employing chaplains specifying they need to be in proportion to the current beliefs of local populations.  But that would be an individual Hospital Trust matter to implement - and bear in mind the guidance is already there so people would have a case now if they felt it was unfair.

**Comment by philipjohn** [comment]
We should be getting rid of the chaplaincy service, not trying to shoe-horn it into a secular society.

**Comment by andrewedmondson** [comment]
That decision must be based on it's value. Do you know how valuable it 
is? I don't.

**Comment by iconoclast86** [comment]
:hand:

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are a [contributor](https://votebot.openpolitics.org.uk/proposals/) to this repository (and not the proposer), you may vote on whether or not it is accepted. 

## How to vote
Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

|vote|symbol|type this|points|
|--|--|--|--|
|Agree|:thumbsup:|`:thumbsup:`|1|
|Abstain|:hand:|`:hand:`|-1|
|Block|:thumbsdown:|`:thumbsdown:`|-1000|

Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 7 days, but will be closed if the proposal is not accepted after 90.

Votes are counted [automatically here](https://votebot.openpolitics.org.uk/proposals/327), and results are set in the merge status checks below.

## Changes

If the proposer makes a change to the proposal, no votes cast before that change will be counted.

**Pull request closed without merging**
