### PR TITLE
Fix footnotes in print versions

### PR DESCRIPTION
**Pull request by Floppy**
In print, URLs in footnotes don't get expanded. I've tweaked the structure of footnotes that are only links to show the URL explicitly, so that in print the reference can all be seen properly.

I've also updated some footnotes to point to more-primary sources, and included dates and sources where possible.

No policy changes.

### CODE REVIEW

**Comment by philipjohn** [comment]
Vote: ✅

**Comment by Floppy** [comment]
SO MANY COMMITS. The current view doesn't work very well if there are lots of commits on the same branch with a lot of files. Sorry about that.

**Comment by philipjohn** [comment]
Vote: ✅

**Comment by philipjohn** [comment]
Thought: how is Vote of handling votes when new commits are made?

**Comment by Floppy** [comment]
@philipjohn same as the old rules - upvotes must be reapplied. We keep downvotes. Basically maximum safety to avoid meaningless edits being used to wipe out blocks :)

**Comment by Autumn-Leah** [comment]
Vote: ✅

**Comment by andrewdwilliams** [comment]
Vote: ✅

**Pull request merged**
