### PR TITLE
Update and Amendment to Society

### PR DESCRIPTION
**Pull request by OliverJackson1**
Amended some of the spelling in the 'Never-ending' section, as well as adding a concept piece on the offering of an hours reduction vs a pay increase.

Also, amended the Egalitarianism section, to have an Egalitarianism section that doesn't ensure all humans have equal social standing is a bit off.

### CODE REVIEW

**Comment by andrewdwilliams** [comment]
:+1:

**Comment by philipjohn** [comment]
:hand: I like the egalitarianism bit but I'm not convinced government should be micromanaging something like pay reviews.

@OliverJackson1 Also bit of feedback: try and limit changes to just one thing. Trying debate two changes at a time is difficult :) so we risk having both fail when one might really pass.

**Comment by OliverJackson1** [comment]
@philipjohn good point, had a couple of things to contribute and didn't want to lose them. 

Not sure what you mean on the pay review micro-management, could you clarify? I'm offering an alternative to increasing pay, stating that businesses through legislation should offer either reduced hours or increased pay. The employee can then decide what to do. Outside of the Bill, there's no interference from state,

**Comment by philipjohn** [comment]
We perhaps need to clarify what is meant by "pay cycle" here, and what actually happens at the end of that? My assumption was that this meant the common practice of doing annual pay reviews.

My reluctance is based on pay reviews being something that not all employers do, and each employer does them differently. In order to introduce this we'd have to effectively legislate that businesses will have to do some sort of review in order to make the offer of increased pay/reduced hours.

Perhaps you could explain how you envisage this working in practice?

**Comment by Floppy** [comment]
👍 but I think separating the working conditions bit into a separate PR might be the best idea here. I have proposals on changes to pay, conditions, working week etc, coming soon as well, so I'll adjust this to suit when those come in if it has passed.

**Comment by philipjohn** [comment]
This proposal has exceeded the time limit, so we'll close it off, but @OliverJackson1 please do think about what could be done to make this proposal more successful, and try again. Thanks!

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are a [contributor](https://votebot.openpolitics.org.uk/proposals/) to this repository (and not the proposer), you may vote on whether or not it is accepted. 

## How to vote
Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

|vote|symbol|type this|points|
|--|--|--|--|
|Agree|:thumbsup:|`:thumbsup:`|1|
|Abstain|:hand:|`:hand:`|-1|
|Block|:thumbsdown:|`:thumbsdown:`|-1000|

Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 7 days, but will be closed if the proposal is not accepted after 90.

Votes are counted [automatically here](https://votebot.openpolitics.org.uk/proposals/399), and results are set in the merge status checks below.

## Changes

If the proposer makes a change to the proposal, no votes cast before that change will be counted.

**Pull request closed without merging**
