### PR TITLE
Modernising Law

### PR DESCRIPTION
**Pull request by merrows**
The Court is part of a common law which already allows the Court to suspend statute (this was done for example with the Merchant Shipping Act). But the Court follows judicial positivism which prevents the Court from actively challenging the will of Parliament. Judicial Activism is used in the USA and used to prevent unconstitutional laws from being passed. The laws are "stuck done" when they fail to meet constitutional standards (eg burning of the flag is legal despite numerous attempts by the Congress to make it illegal). 

These new powers as proposed will be an important step to formalising Separation of Powers and giving the Court power to hold any person to account on a matter of law.

The matter of the lower criminal court is one in which most people do not appear before judges. Magistrates are typically teachers, doctors, community figures, but not legally trained. We propose making the Court able to pass a judgment only by the decision of a judge. Some Magistrates are judges but this is not that common. 

The point of legal representation, is that under the current system people are not entitled to any legal representation. For example for council tax cases. This should be changed. The Crown has ample resources and the defendant cannot possibly stand up to the Crown without assistance.

### CODE REVIEW

**Comment by andrewdwilliams** [comment]
I am no legal scholar. However, I do understand that in the UK we have an uncodified constitution, as in it is not written down in one single authoritative document. In the US, however, they have a codified constitution - the US Constitution. This single authoritative constitution is judiciable, as in, judges can use the constitution, as it is a higher source of law, and strike down other laws if they decide they are 'unconstitutional'. This is what you mean by 'judicial activist principles'. I am telling you this is inapplicable to the UK, as we have no higher law, and no single constitutional document. Also, in the UK, we have parliamentary sovereignty, meaning Parliament is the supreme legislative authority and it can overrule the courts, making this kind of 'judicial activism' impossible.

As I say, I am no legal scholar, but I disagree with the view that each magistrates' court should have a judge sitting. I do not know the history of magistrates' courts, but I can tell you one thing - judges, in this country, are in short supply. The supply is so short that within a few years, it is possible that much of the Supreme Court will be vacant, with few candidates to replace them. This is because it takes many years to train barristers (and solicitors), and only very few of them are suitable to become judges, or willing to become judges. The magistrates system works as it is. Magistrates are volunteers, but often well educated volunteers, who are assisted in court by trained legal advisers. It would be not only very costly to employ actual judges to sit in (every!) magistrates' court, but also unlikely, as it would be impossible to appoint that many. Therefore, I disagree with the idea that "The Magistrates Court must have a judge sitting."

I note your final point: "All defendants in a criminal case will be entitled to legal representation without cost subject to their own finances." As far as I understand, this situation does not arise as it is - is that not what legal aid is for?

**Comment by merrows** [comment]
Well this is a learning curve for me. I did not understand how little someone would know and be interested in these higher minded issues:
"meaning Parliament is the supreme legislative authority and it can overrule the courts, making this kind of 'judicial activism' impossible." This is just completely wrong, and demonstrates some a basic misunderstanding, I really wonder why you are even interested in politics. 

If you want to know something about this, google "merchant shipping act 1988 suspended".

I will not subscribe now to these threads. 

I do not intend to try educate you, but you obviously do not understand law. Law is defined in the Court and the question of superior law does exist - google Sunderland v Thoburn. Also EU law is superior to all English law but that is due to the ECA.  

I think the basic issue you have is you think law is some kind of set of rules which Parliament writes and then the Court enforces. If you google Rule of Law you will hopefully understand it more. 

About the other points, Legal Aid was cut back years ago and now it is only available under certain circumstances. 

The points about the lower criminal court and shortage of judges really is not a valid argument. Many law graduates cannot even find any work except paralegals and there is a huge body of skill waiting to be used. There would be a cost change but justice is not measured in cost terms.

**Comment by andrewdwilliams** [comment]
You know, you could practice not being so bitter before you post things.

Yes, I know about the Factortame case. I know that EU law overrides British law. But we are not talking about EU law at all in this context. Regardless, as someone well versed in "these higher minded issues", you are no doubt aware that Parliament, as it is sovereign (and it is) can repeal the European Communities Act 1972 and we would leave the EU. And then, EU law would not be superior to UK law. So, the point still stands. Parliament is sovereign. Full stop. Any constitutional scholar would agree.

Anyway, you are talking about judicial activism, and British judges striking down British laws, which is nothing to do with the EU. You still did not address the point that we have no written constitution, and so it is impossible for laws to be declared 'unconstitutional'.

My problem, apparently, is that I think "the law is some kind of set of rules which Parliament writes and then the Court enforces." Well, statute law is written by Parliament. The courts do enforce this, and when necessary, interpret it. I don't see how the rule of law fits into it. If you could be so kind, you could enlighten me as to what I'm actually missing.

"The points about the lower criminal court and shortage of judges really is not a valid argument. Many law graduates cannot even find any work except paralegals and there is a huge body of skill waiting to be used. There would be a cost change but justice is not measured in cost terms." Before I even attempt to counter-argue over that statement, you haven't actually set out an argument to do away with the current system, so, as they say, the burden of proof is on you. As I pointed out, whilst magistrates are not legally trained, they have legally trained advisers, and the system works well as it is currently.

**Comment by philipjohn** [comment]
@merrows Keep debates civil please.

**Comment by merrows** [comment]
Keep your comments LEGAL. 
  
  
  

----------------------------------------

**Comment by merrows** [comment]
You need to check up on laws of sedition, and also relevant Acts such as the Treason and Felony Act. You are commenting about me and civility but YOU need to look at the legality of the comments I saw.
  
 You need to keep views of civility to yourself (in fact just trying to impose such views on someone is uncivil), and confine your views to what the law allows. The entire point of law is that it creates fairness in society - something you clearly do not support. 
  
  
  
  
  

----------------------------------------

**Comment by philipjohn** [comment]
Noting here that I have blocked @merrows from contributing to the Manifesto. While we welcome all viewpoints and healthy debate, the comments from @merrows here and in #402 are personal and overly confrontational. They do not contribute healthily to the debate and aren't acceptable.

**Comment by andrewdwilliams** [comment]
In which case, I'll give this a :-1:

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are a [contributor](https://votebot.openpolitics.org.uk/proposals/) to this repository (and not the proposer), you may vote on whether or not it is accepted. 

## How to vote
Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

|vote|symbol|type this|points|
|--|--|--|--|
|Agree|:thumbsup:|`:thumbsup:`|1|
|Abstain|:hand:|`:hand:`|-1|
|Block|:thumbsdown:|`:thumbsdown:`|-1000|

Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 7 days, but will be closed if the proposal is not accepted after 90.

Votes are counted [automatically here](https://votebot.openpolitics.org.uk/proposals/403), and results are set in the merge status checks below.

## Changes

If the proposer makes a change to the proposal, no votes cast before that change will be counted.

**Pull request closed without merging**
