### PR TITLE
EU Policies added

### PR DESCRIPTION
**Pull request by andrewdwilliams**
Added one about ensuring our membership is cost neutral - we get out what we put in, not necessarily just straight up money but through investment, development, etc.

Also added one about the possibility of leaving the EU and if we did, joining the EFTA.

### CODE REVIEW

**Comment by mikera** [comment]
Can we separate into two separate PRs? They seem like different issues to me, both worthy of a good debate

**Comment by Floppy** [comment]
Yes, I think that would be a good idea.

**Comment by yellowgopher** [comment]
I'm a Euro Sceptic but I think any membership of international organisations like the EU doesn't HAVE to be cost neutral - it should be about sharing ideas and resources for the greater good and, because we have inequality, some people/countries have to accept they might pay more.  Now I can see that "greater good" could equate to a value but I am concerned, as soon as you put a figure on such things, it only serves to turn people against the idea ("it costs THAT much!?!").  

Second idea - if we leave to try and join the EFTA - is sound.

**Comment by philipjohn** [comment]
Cost neutrality sounds like a purely quantitative goal that ignores the actual benefits.

**Comment by mikera** [comment]
I don't think cost neutrality should be an explicit objective, but there I would support something about "all member states sharing fairly in terms of overall benefits and costs". 

If there is to be a redistributive element (i.e. richer nations being greater net contributors) then I think that the level of this redistribution should be explicitly agreed (e.g. 2% of GDP from each country pooled and re-allocated according to population size would have a modest redistributive effect).

If you don't do this, then you end up with a bunch of "back door" redistribution happening through various channels (CAP, Structural fund, Cohesion fund etc.) which is driven by political / bureaucratic agendas isn't really transparent or fair.

**Comment by andrewdwilliams** [comment]
So we agree that joining the EFTA is sound, but cost effective is not. I'll exclude cost effective and edit this to reflect that later today.

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are a [contributor](https://votebot.openpolitics.org.uk/proposals/) to this repository (and not the proposer), you may vote on whether or not it is accepted. 

## How to vote
Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

|vote|symbol|type this|points|
|--|--|--|--|
|Agree|:thumbsup:|`:thumbsup:`|1|
|Abstain|:hand:|`:hand:`|-1|
|Block|:thumbsdown:|`:thumbsdown:`|-1000|

Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 7 days, but will be closed if the proposal is not accepted after 90.

Votes are counted [automatically here](https://votebot.openpolitics.org.uk/proposals/350), and results are set in the merge status checks below.

## Changes

If the proposer makes a change to the proposal, no votes cast before that change will be counted.

**Pull request closed without merging**
