### PR TITLE
Added section about credit default swaps and another about credit rating agencies.

### PR DESCRIPTION
**Pull request by andrewdwilliams**
I've added some initial thoughts on the two subjects, and want to see if we can develop more cohesive policies based on my initial statements.

### CODE REVIEW

**Comment by philipjohn** [comment]
Thanks for the interesting contribution! It'd be great if we could have a little more detail on what problem this proposal aims to solve and how your proposal would solve that problem.

**Comment by Floppy** [comment]
Likewise, I think this is probably a good thing, but I don't know enough about either to decide. Any detail on the problems being solved would be great.

**Comment by andrewdwilliams** [comment]
Okey-dokey.

I'm going to say that I pulled the two policy ideas from a book I'm reading, The Debt Generation by David Malone. I know quite a bit about credit default swaps, but not what a clearing house is, and I have some idea of what credit rating agencies do, but not how to reform them. So, give me a couple days and I'll formulate some real proposals.

What I do know is that ESMA is doing a lot of good work on regulating Credit Rating Agencies. Basically, what we need to do is reduce over-reliance on credit ratings while at the same time improving the quality of the rating process. 

I think we should start by making agencies legally liable for their decisions. However, as I said, I'll do a bit of research into the various proposals for reform and get back to you.

**Comment by andrewdwilliams** [comment]
It might be worth reading a few of these bits and bobs about Credit Rating Agencies. I'll scour them for some policy ideas.

[What the Ratings Agencies really do. Liars Lexicon – Support Uplift] (http://www.golemxiv.co.uk/2011/07/what-the-ratings-agencies-really-do-liars-lexicon-support-uplift/)
[Credit Rating Agency Performance Needs Improvement] (http://www.accountingweb.com/article/credit-rating-agency-performance-needs-improvement/220749)
[Credit rating agencies: The current system and how it can be improved] (http://journalistsresource.org/studies/economics/banks/credit-rating-agencies-overview#)
[Stricter rules for credit rating agencies to enter into force] (http://europa.eu/rapid/press-release_IP-13-555_en.htm)
[Credit Rating Agencies: Alternative Compensation Models for Nationally Recognized Statistical Rating Organizations] (http://www.gao.gov/assets/590/587773.pdf)

**Comment by andrewdwilliams** [comment]
My ideas for a Credit Rating Agencies policy:

We aim to reduce over-reliance on credit ratings whilst at the same time improving the quality of the rating process.

We will establish a monitoring body to examine the work of Ratings Agencies.

We will force Credit Rating Agencies to be more transparent about their work and their ratings.

We will open up the market for competition with Credit Rating Agencies, as well as introduce a ban on expansion for the “Big Three,” Standard and Poor's, Moody's and Fitch. We should also have a public or non-profit Credit Rating Agency.

We will also make Ratings Agencies legally liable for their actions.

**Comment by philipjohn** [comment]
Sounds good - probably best to close this one and spin up a new proposal
with that in.

**Comment by andrewdwilliams** [comment]
Agreed.

**Comment by Floppy** [comment]
Sorry, missed this. @andrewdwilliams, just make a new edit on the site with your updated version, and we'll close this one off if it's superceded. I'll link them together in the comments so we can follow the history.

**Comment by Floppy** [comment]
Or, if you want, you can edit this change directly at https://github.com/openpolitics/manifesto/pull/282/files - click the pencil icon in the top right corner of the file viewer area.

**Comment by andrewdwilliams** [comment]
This can be disregarded now, I have proposed a new one focusing solely on credit ratings agencies.

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are a [contributor](https://votebot.openpolitics.org.uk/proposals/) to this repository (and not the proposer), you may vote on whether or not it is accepted. 

## How to vote
Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

|vote|symbol|type this|points|
|--|--|--|--|
|Agree|:thumbsup:|`:thumbsup:`|1|
|Abstain|:hand:|`:hand:`|-1|
|Block|:thumbsdown:|`:thumbsdown:`|-1000|

Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 7 days, but will be closed if the proposal is not accepted after 90.

Votes are counted [automatically here](https://votebot.openpolitics.org.uk/proposals/282), and results are set in the merge status checks below.

## Changes

If the proposer makes a change to the proposal, no votes cast before that change will be counted.

**Pull request closed without merging**
