### PR TITLE
Added clauses about behavioural advertising

### PR DESCRIPTION
**Pull request by amcewen**
Paraphrased but basically added the set of recommended regulations from Maciej Ceglowski's "Notes on an Emergency" talk at re:publica

### CODE REVIEW

**Comment by Floppy** [comment]
Vote: ✅

**Comment by areteh** [comment]
:white_check_mark:

**Comment by areteh** [comment]
Possibly could take this further:
- 14 day limit instead of 30 and/or
- Customer can remove all data collected about them before the force expiry date

**Comment by Autumn-Leah** [comment]
I agree with @areteh but I'll put this through and edit after if you wont.

Vote: ✅

**Pull request merged**
