### PR TITLE
secular chaplaincy and rehab in prisons

### PR DESCRIPTION
**Pull request by andrewedmondson**

### CODE REVIEW

**Comment by philipjohn** [comment]
There shouldn't be a chaplaincy service at all, IMO. :hand:

**Comment by andrewedmondson** [comment]
I've hosted talks from several chaplains who claim that it is a valuable 
service. Perhaps it could be entirely voluntary and secular?

**Comment by yellowgopher** [comment]
Chaplaincy is valuable for a lot of people. As I have pointed out before there is guidance issued that advises chaplains reflect the beliefs of the areas they work in. It is up to individual Trusts to take that into account. I would, perhaps, make that a legal requirement. As for pay, well, there is already a mixture of voluntary and paid positions. If a local Trust wants to pay, why is that a bad thing?

**Comment by philipjohn** [comment]
State resources should not be used for the special treatment of any religions. If a particular faith group wants to provide chaplaincy services it should be provided entirely out of their own resources, just as with any other interest group. That's equal and fair.

**Comment by andrewedmondson** [comment]
Yes that is one acceptable approach. Another is to fund a secular 
chaplaincy service.

**Comment by philipjohn** [comment]
Secular chaplains don't exist. The non-religious equivalent to a chaplain would be a psychiatrist, so let's give people the counselling they need on the health service, without the influence of religion, or let them go outside the health service to their religion if they wish.

**Comment by andrewedmondson** [comment]
Secular does not mean non-religious.

A secular chaplaincy would be one that does not privilege a particular 
religion or belief.

Non-religious chaplains certainly do exist. Some are even paid, e.g. in 
ome universities.

A psychiatrist is not a chaplain. They are concerned with mental health 
rather than a friendly listening ear.

If a person is very ill and they are religious, they might want a 
relgious chaplain. If they are not religious, they might want to talk to 
someone who is not religious.



On 19/04/2015 21:32, philipjohn wrote:
>
> Secular chaplains don't exist. The non-religious equivalent to a 
> chaplain would be a psychiatrist, so let's give people the counselling 
> they need on the health service, without the influence of religion, or 
> let them go outside the health service to their religion if they wish.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/openpolitics/manifesto/pull/328#issuecomment-94310833>.
>

-- 
Andrew Edmondson

079 3450 8671
West Sussex Humanists <http://www.westsussexhumanists.org.uk>
BHA logo <http://www.humanism.org.uk/>

**Comment by iconoclast86** [comment]
:hand:

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are a [contributor](https://votebot.openpolitics.org.uk/proposals/) to this repository (and not the proposer), you may vote on whether or not it is accepted. 

## How to vote
Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

|vote|symbol|type this|points|
|--|--|--|--|
|Agree|:thumbsup:|`:thumbsup:`|1|
|Abstain|:hand:|`:hand:`|-1|
|Block|:thumbsdown:|`:thumbsdown:`|-1000|

Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 7 days, but will be closed if the proposal is not accepted after 90.

Votes are counted [automatically here](https://votebot.openpolitics.org.uk/proposals/328), and results are set in the merge status checks below.

## Changes

If the proposer makes a change to the proposal, no votes cast before that change will be counted.

**Pull request closed without merging**
