### PR TITLE
End speaker democratic deficit

### PR DESCRIPTION
**Pull request by philipjohn**
Puts an end to the democratic deficit whereby constituents whose MP is the speaker are not adequately served and do not have the usual choice during elections.

### CODE REVIEW

**Comment by Floppy** [comment]
Vote: ✅

**Comment by davidmiller** [comment]
`they will be jobs advertised, filled and salaried just like any other.` according to received wisdom, most jobs are not advertised.

Even if that's not true, wouldn't this still be a weirdly passive aggressive tone to take in a manifesto?

**Comment by philipjohn** [comment]
It probably is passive aggressive but that's because I'm angry ;) Personally, I'm not too bothered about that but I'm also open to changing the wording if you think it really needs it?

**Comment by Autumn-Leah** [comment]
I'd change

>We will end the practice of the speaker's constituents being denied representation and a lack of choice in elections. The positions of speaker and deputy speaker will not be filled by MPs, they will be jobs advertised, filled and salaried just like any other.

to 

>We will end the practice of the speaker's constituents being denied representation and a lack of choice in elections. The positions of speaker and deputy speaker will not be filled by MPs, they will be jobs advertised, filled and salaried just like any other, as the alternative would be a continuous exception in the premise of this country's democracy.

Just to make it sound less angry and most justifiable, but I'm not stopping it.

Vote: ✅

**Pull request merged**
