### PR TITLE
Adjustment to arms policy

### PR DESCRIPTION
**Pull request by Autumn-Leah**

### CODE REVIEW

**Comment by Polygon48k** [comment]
should be "The United Kingdom of Great Britain and Northern Ireland", I have never seen that acronym and it yields no google results so I would drop and, as it is only used twice use the full name of The United Kingdom of Great Britain and Northern Ireland.

**Comment by Polygon48k** [comment]
:negative_squared_cross_mark:

**Comment by Floppy** [comment]
Yeah, that's an odd acronym :)

I'd support a change to UK-built though, rather than British.

**Comment by Floppy** [comment]
Forgot to vote, reasoning above :)

Vote: ❎

**Comment by philipjohn** [comment]
What they ^ said :)

Vote: ❎

**Pull request closed without merging**
