### PR TITLE
Need for Debate

### PR DESCRIPTION
**Pull request by merrows**
The right to die is a highly contentious issue. It definitely crosses into religious issues. There are also numerous aspects which make this "right" open to abuse. There are countless cases (esp. for teenagers) in which people have been encouraged to die by their peers. Currently these cases have been prosecuted. In one case now a friend texted someone dozens of times talking them into dying (which they finally did).

### CODE REVIEW

**Comment by andrewdwilliams** [comment]
The right to die is not the same as committing suicide. The right to die is related to euthanasia - the act of assisted suicide, which, if ever implemented, would be subject to strict restrictions and regulations of who could do it and under what circumstances. We also don't include personal opinions in that way in the manifesto. :-1:

**Comment by merrows** [comment]
I just included my own view as a means to generate discussion. The right to die and suicide are closely related. In the recent Bill which failed in the Commons, the wording was as follows - 
 _Subject to the consent of the High Court (Family Division) pursuant to
subsection (2), a person who is terminally ill may request and lawfully be
provided with assistance to end his or her own life._

Under the proposal dubbed the right to die bill, the person may end their OWN life. That is suicide. The difference is the person is helped to commit suicide by giving them poisons so they can kill themselves. If you are going to comment on something as important as this, you need to know SOMETHING about the subject. Under right to die proposals the person kills themselves. That is suicide. 

Religion does I think have a firm view on this, and any policy needs to reflect religious views. Billions of people are religious and this issue is an important one. To simply ignore some aspects is fundamentally ignoring key factors. This either shows an unwillingness to respect views held by billions of people or an ignorance of them.

Gordon Brown himself when speaking on this matter said the danger of a right to die was that people could be pressured into dying. He said at the despatch box on that basis he opposed such measures.

**Comment by andrewdwilliams** [comment]
Taking the wording you quote there:

> Subject to the consent of the High Court (Family Division) pursuant to subsection (2), a person who is terminally ill may request and lawfully be provided with assistance to end his or her own life.

This says that after the consent of the High Court is given (which would be a relatively lengthy process), a person who is "terminally ill", and only terminally ill, may request and be provided with assistance to end their life. This assistance would not take the form of the handing over of poison for them to use on themselves in their own time. This assistance would likely involve visiting a clinic, lying on a bed, and being given tablets or a drink that would kill them. It is very much assisted, and definitely not something that is done in their own time, in their own home. As I say, if such assisted suicide existed in the UK, as it does in places like Switzerland, it subject to strict restrictions and regulations of who could do it and under what circumstances.

You are wrong to say that bill allows people to take their own life. It allows only assisted suicide, and it does not allow it on impulse, only after consent is given by the High Court. Religion does have views on this subject, or more specifically it has views on suicide. I'm not particularly concerned what they are, but if you wish to research them, feel free. Of course, theoretically, people can be pressured into euthanasia, but frankly, it would be very, very difficult under the terms of that bill you quoted.

**Comment by philipjohn** [comment]
@merrows Thanks for joining in. There isn't really a mechanism to just comment on the manifesto at the moment. If you'd like to propose a change to this section of the manifesto reflect your views, that would be something we can debate on.

> If you are going to comment on something as important as this, you need to know SOMETHING about the subject.

We expect all contributors to be civil. Please keep your points focused on the policy, not the person.

**Comment by merrows** [comment]
You need to take your own advice. If you are writing statements which are completely false and stating them as fact that is a kind of fraud. If you think that is civil then your values are fairly mixed up. 
  
 I expect ALL people to act in a manner which conforms to law. Something which you are clearly incapable of doing. Is that clear to you?
  
  
  

----------------------------------------

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are a [contributor](https://votebot.openpolitics.org.uk/proposals/) to this repository (and not the proposer), you may vote on whether or not it is accepted. 

## How to vote
Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

|vote|symbol|type this|points|
|--|--|--|--|
|Agree|:thumbsup:|`:thumbsup:`|1|
|Abstain|:hand:|`:hand:`|-1|
|Block|:thumbsdown:|`:thumbsdown:`|-1000|

Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 7 days, but will be closed if the proposal is not accepted after 90.

Votes are counted [automatically here](https://votebot.openpolitics.org.uk/proposals/402), and results are set in the merge status checks below.

## Changes

If the proposer makes a change to the proposal, no votes cast before that change will be counted.

**Pull request closed without merging**
