### PR TITLE
Discrimination in Physical Education

### PR DESCRIPTION
**Pull request by Autumn-Leah**

### CODE REVIEW

**Comment by Autumn-Leah** [comment]
I can remove the bracketing thing in order to get this passed, as the discrimination is the core policy, I just consider the bracketing a good alternative as in some cases separation *may* be needed, but certainly not to the extent that it's practised now.

**Comment by Autumn-Leah** [comment]
This'll be shifted over to the new section if that proposal passes so you may have to vote on a few of my proposals twice : D

...sorry about that

**Comment by Xyleneb** [comment]
With this, how do you hope to not ruin football for the men and athletics for the women?

**Comment by Autumn-Leah** [comment]
By "ruin" it, what affect would you expect this legislation to have? Lots of schools already co-ed with sports but it's not mandatory, I had, mostly, co-ed PE/Sports/whatever they call it now.

**Comment by Xyleneb** [comment]
>By "ruin" it, what affect would you expect this legislation to have?

There will be mandatory gender quotas for football (girls want to take part) but there will be no such quotas for ballet (boys do not).

All of the "safe space" "just for girls class" kind of crap would have to come to an end. They would have to take TKD class with a bunch of "intimidating" men.

Athletics anywhere near towards the professional end of the sport will have men dominating the races. It's got to be frustrating to do a sport where you're topping out at 5th, 6th place every time you run.

Gender segregation might be "unprogressive" but it's kept the majority of the people happy and doing what they want to do.

**Comment by Autumn-Leah** [comment]
> There will be mandatory gender quotas for football (girls want to take part) but there will be no such quotas for ballet (boys do not).

ok ok ok lemme break this down. The mandatory gender quotas would only affect the mix of the preexisting classes, not the classes themselves. PE/PSHE/Sports/PhysEd isn't voluntary atm, it's just split by gender at the moment. Gender quotas will never exist in the lower education system because that's just not how it works. Also, good job reinforcing gender roles right there buddy, boys do ballet, girls play football, vice versa. Kids largely don't give a shit until they're influenced into these views.

> All of the "safe space" "just for girls class" kind of crap would have to come to an end.

Uh, good!

> They would have to take TKD class with a bunch of "intimidating" men.

The fuck is a TKD class? Also there won't be men there for the most part, there will be boys and girls, not men and women. These rules apply to secondary schools and lower because that's what the mandatory PE/PSHE/Sports/PhysEd curriculum is applied to under current legislation. I wouldn't call a little kid intimidating.

> Athletics anywhere near towards the professional end of the sport will have men dominating the races. It's got to be frustrating to do a sport where you're topping out at 5th, 6th place every time you run.

PE/PSHE/Sports/PhysEd isn't meant for competitive practice, that's what after-school clubs are for, which this policy doesn't deal with. Gender segregation in competitive practice is something I have no issue with. Most people aren't going to be at the top of the "professional end of the sport", it's a school class, not the training ground for Usain Bolt.

> Gender segregation might be "unprogressive" but it's kept the majority of the people happy and doing what they want to do.

If you're going to make snarky remarks about politics then you might wanna know your shit first because the wording gives me the impression that had you known, you'd not have said it. Try looking up the basis of progressivism, not the common definition based on radfems and The Young Turks and their "progressivism" but the actual political theory one.

> but it's kept the majority of the people happy

What about the minority of people? When you keep a majority happy it means the minority either doesn't care or doesn't like whatever you happen to be doing.

**Comment by Xyleneb** [comment]
>Gender quotas will never exist in the lower education system because that's just not how it works.

That is how it worked in my own primary school, regarding football. You can't just not pick any girls for your team, there is no "I" in team!

>Also, good job reinforcing gender roles right there buddy, boys do ballet, girls play football, vice versa. Kids largely don't give a shit until they're influenced into these views.

My primary school had mandatory dance classes too. How many boys do you think wanted to be there? Do you think I wanted to be there? The teachers try their best but there's little you can do when the material you're working with is wholly unpopular with half the class. These impressions that you get from society happen very early, possibly before you turn up there.

>The fuck is a TKD class?

Ohh come on you're gonna pull me on the use of acronyms now? 'TKD' is an olympic sport. 'PIV' is not.

>Also there won't be men there for the most part, there will be boys and girls, not men and women. These rules apply to secondary schools and lower because that's what the mandatory PE curriculum is applied to under current legislation. I wouldn't call a little kid intimidating.

I usually wouldn't either. But there are some who would, some of them children, and a lot of them parents imposing their own personal hang-ups on their children. I like to imagine it being ok for Biff to hit Kiff in TKD... But I remember how unreasonable parents get over this sort of stuff, such that any contact sport would probably go by the wayside. The schools are scared to death of sexual assault too, not so much the crime but the accusation of it. 

>Most people aren't going to be at the top of the "professional end of the sport", it's a school class, not the training ground for Usain Bolt.

Well today I couldn't run to my own front gate, but in yesteryear pretty much the whole group of boys would leave the majority of the girls behind. I don't blame them in the slightest for not being able to run, it's just not very fun for them when they're left in the dust. We were a little too young back then to have the mentorship kind of attitude that would have probably helped.

>If you're going to make snarky remarks about politics then you might wanna know your shit first because the wording gives me the impression that had you known, you'd not have said it. Try looking up the basis of progressivism, not the common definition based on radfems and The Young Turks and their "progressivism" but the actual political theory one.

Well I am sorry if I have offended politics in any way. Can I just ask you though: what is your idea of "progressivism"? I mean I know the former is "the more you earn, the more you pay" and the latter has something to do with trigger warnings, but what is it to you?

**Comment by philipjohn** [comment]
Folks, keep it civil please.

I'm not convinced we need the bracketing thing. I agree with the principle here though.

Vote: ✅

**Comment by Autumn-Leah** [comment]
> That is how it worked in my own primary school, regarding football. You can't just not pick any girls for your team, there is no "I" in team!

My mistake, I thought you meant at an official level, not just informal rules within a given class. This policy is about rules at the school policy level, not on the level of personal preference for the kids. You can have a girls team and a boys team, that's fine, provided they're both playing the same match.

> My primary school had mandatory dance classes too. How many boys do you think wanted to be there? Do you think I wanted to be there? The teachers try their best but there's little you can do when the material you're working with is wholly unpopular with half the class. These impressions that you get from society happen very early, possibly before you turn up there.

I hardly see how this is a counter argument to the policy. Under current law schools are *supposed* to provide the same lessons for everyone, so you'd have the dance class regardless unless the school was breaking the law. It would only ensure that you have a mix of people in the class rather than just boys or girls.

> Ohh come on you're gonna pull me on the use of acronyms now? 'TKD' is an olympic sport. 'PIV' is not.

It wasn't intentional, I legitimately didn't know what it stood for. I do now. My bad.

> I usually wouldn't either. But there are some who would, some of them children, and a lot of them parents imposing their own personal hang-ups on their children. I like to imagine it being ok for Biff to hit Kiff in TKD... But I remember how unreasonable parents get over this sort of stuff, such that any contact sport would probably go by the wayside. The schools are scared to death of sexual assault too, not so much the crime but the accusation of it. 

When it comes down to it, the parents job is to facilitate education, not to prevent it, so I don't see how this is a bad thing about the policy. Parents will complain, too bad for the parents, they aren't the main concern in a child's education.

> Well today I couldn't run to my own front gate, but in yesteryear pretty much the whole group of boys would leave the majority of the girls behind. I don't blame them in the slightest for not being able to run, it's just not very fun for them when they're left in the dust. We were a little too young back then to have the mentorship kind of attitude that would have probably helped.

So do you think I should add something to the policy about allowing the kids to self segregate themselves should they feel that they aren't able to compete or that it would improve their education or somesuch exception? I mean, that would be open to abuse by the admin if it wasn't strictly enforced, and it would necessarily impose majoritarian democracy, so I don't know how I'd feel about that.

> This is not what I meant to happen. I wanted to know, genuinely, what progressivism means to you.

It doesn't mean much to me past its actual meaning given that I'm not a progressive :D

**Comment by Floppy** [comment]
Yep, fine by me - grouping by ability is reasonable, by gender is pointless. The two *may* correlate in certain areas (purely because biology), but that's emergent, not decided up front.

Incidentally, @xyleneb and @autumn-leah, I love your energy and proposals, it's great to see, and I hugely appreciate your input and the fact that you keep working together to reach consensus! You do seem to want to have a larger conversation and debate somewhere, but these debates probably aren't the best place for that, simply because of the focused nature of the proposals. HOWEVER, the Something New forum at https://discourse.somethingnew.org.uk perhaps *is*, so you're most welcome to go ahead and start up a meta-discussion there, maybe? :)

Vote: ✅

**Pull request merged**
