### PR TITLE
Introduced Community Engagement into Society.  Added points about weekend surgeries and hustings.

### PR DESCRIPTION
**Pull request by GarethShapiro**

### CODE REVIEW

**Comment by GarethShapiro** [comment]
Many, I would even suspect most, people cannot attend a surgery which runs from 6pm - 7pm on a weeknight.  

Hustings are a traditional and, if you consider the televised version Question Time, popular format whereby the public can scrutinise the thoughts and attitudes of those they elect.  Ward councillors should be prepared to talk in public regularly about their activities, in the company of their contemporaries.  This is also a very efficient way for the public to understand how their own issues and ideas sit relative to others' in the community and also to hold what could be seen as a "Group Surgery" reaching more people in less time.

**Comment by Floppy** [comment]
:+1: nice ideas both

**Comment by Floppy** [comment]
Only concern is that currently there's no duty on anyone to run hustings, even during election time, but that is being proposed as an addition in #272 already, so that's fine.

**Comment by tmtmtmtm** [comment]
Maybe my understanding of "hustings" is off slightly, but the explanation given in the comment above is different from what I expected from the text. I support the general idea, but would like to see it expanded there.

**Comment by Floppy** [comment]
The electoral commission guidance states: "A hustings event is a meeting where election candidates or
parties debate policies and answer questions from the audience"

http://www.electoralcommission.org.uk/__data/assets/pdf_file/0007/105946/sp-hustings-rp-npc-ca.pdf

Does that make sense with what you read/understood?

**Comment by tmtmtmtm** [comment]
Yes — i.e. that it's in the context of an election. Which isn't what's being proposed here.

**Comment by Floppy** [comment]
So I read it as that hustings shouldn't be only during election time, and that regular debates with all local parties should be held. Perhaps @GarethShapiro can clarify his meaning.

**Comment by tmtmtmtm** [comment]
@Floppy — that's what I took the original proposal to be, but the clarification here made it sound like this was more of an event for the elected councillors to talk about what they're doing, face questioning etc

**Comment by Floppy** [comment]
Ah, I see, yes. Let's get @GarethShapiro to clarify which he means, and if it's not a general all-party debate thing, then we should change the word "hustings" to something else.

**Comment by GarethShapiro** [comment]
I specifically meant that these public meeting should be all the time, not just in the run up to elections.  I've used the wrong term "hunting" which needs to be changed. 

Any suggestions?

"public debates"
"public forum"

**Comment by tmtmtmtm** [comment]
I think one of the key questions is who gets to participate (in terms of presenting / answering questions). Is this for the elected representatives? Or including people who ran as candidates and lost, etc?

**Comment by GarethShapiro** [comment]
Chair
-------

I recently went to one locally which was specifically focussed on green issues.  It was chaired by a C class executive of a well known NGO.  While clearly in favour of the better green policies he was very otherwise very good at keeping the whole thing on track and the audience engaged.

It way be a bit much to expect good chairpeople (is that a word?) in every community but then again is this not patronising?  Not sure but this is probably key to how popular these things might be.

Who are our community elders these days?

Panel
--------

An elected councillor and one member from each of the other parties who lives locally.

**Comment by PaulJRobinson** [comment]
:+1:

**Comment by Floppy** [comment]
:+1:

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are a [contributor](https://votebot.openpolitics.org.uk/proposals/) to this repository (and not the proposer), you may vote on whether or not it is accepted. 

## How to vote
Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

|vote|symbol|type this|points|
|--|--|--|--|
|Agree|:thumbsup:|`:thumbsup:`|1|
|Abstain|:hand:|`:hand:`|-1|
|Block|:thumbsdown:|`:thumbsdown:`|-1000|

Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 7 days, but will be closed if the proposal is not accepted after 90.

Votes are counted [automatically here](https://votebot.openpolitics.org.uk/proposals/288), and results are set in the merge status checks below.

## Changes

If the proposer makes a change to the proposal, no votes cast before that change will be counted.

**Pull request merged**
