### PR TITLE
Amendment to Drug Wording

### PR DESCRIPTION
**Pull request by OliverJackson1**
Amendment from Legalisation to Decriminalisation. Then a few more words on what we'd do and the desired outcome.

### CODE REVIEW

**Comment by philipjohn** [comment]
I like this. One issue: it's not clear what "fines for improper use" means. Do you envisage there being roll is about where drugs can be used, and if so, what do those look like?

**Comment by OliverJackson1** [comment]
@philipjohn, yeah, fines would be given for a number of usage breeches. This is the method being used in Portugal and is proving very effective. Essentially, you develop clear user spots (shops, clinics etc) and then use pejorative measures to limit usage in public places such as parks. Its that subtle difference between legalisation and managed decriminalisation. 

Obviously, the level of managament is different depending on the drug in question. Does that clarify?

**Comment by philipjohn** [comment]
It does, thanks! I'm wondering how we can get that succinctly into the Manifesto so that others will get the idea first time. Not sure... need some thought.

**Comment by Floppy** [comment]
👍 from me and can edit later for clarity.

Incidentally, that sort of method is presumably the same for alcohol, tobacco, etc now? We have fines for "improper use" in public places, right?

**Comment by philipjohn** [comment]
:+1: to reflect my earlier support

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are a [contributor](https://votebot.openpolitics.org.uk/proposals/) to this repository (and not the proposer), you may vote on whether or not it is accepted. 

## How to vote
Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

|vote|symbol|type this|points|
|--|--|--|--|
|Agree|:thumbsup:|`:thumbsup:`|1|
|Abstain|:hand:|`:hand:`|-1|
|Block|:thumbsdown:|`:thumbsdown:`|-1000|

Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 7 days, but will be closed if the proposal is not accepted after 90.

Votes are counted [automatically here](https://votebot.openpolitics.org.uk/proposals/396), and results are set in the merge status checks below.

## Changes

If the proposer makes a change to the proposal, no votes cast before that change will be counted.

**Pull request merged**
