### PR TITLE
Implement a robin hood tax

### PR DESCRIPTION
**Pull request by Floppy**

### CODE REVIEW

**Comment by philipjohn** [comment]
@Floppy Mind if I tweak this, if you're struggling to find the time?

**Comment by Floppy** [comment]
Oh, god, yes, go ahead. Or, I'll do it as soon as I get a minute or two.

**Comment by philipjohn** [comment]
Done! It's a :+1: from me.

@PaulJRobinson Could you add your vote again please?

@mikera @tmtmtmtm Keen to get your votes now on this proposal

**Comment by Floppy** [comment]
lovely

**Comment by tmtmtmtm** [comment]
I'm still finding the wording a little confusing, as it's not completely clear whether the two sentences are meant to be saying essentially the same thing, or whether it's two overlapping, yet distinct, proposals.

There's also a slight ambiguity as to what it means to "join" the tax: is the proposal to implement it:

1. no matter what anyone else does
2. as long as at least *some* other EU states do
3. simultaneously with a Eurozone-wide implementation
4. only if the entire EU does?

I'd happily vote yes on 3 and 4; the first two I'm a little more uncertain about. 

I'd also be open to a wording that says we'd help work towards a unanimous implementation, but would consider any lesser plan carefully.

**Comment by philipjohn** [comment]
Sounds like you have a far better handle on this than we do @tmtmtmtm :) So in the interests of collaboration, do you fancy drafting some wording that you think adequately does the job? We'll have a consensus then too :)

**Comment by Floppy** [comment]
@tmtmtmtm I've had another crack at the wording in an attempt to answer your question. See what you think.

**Comment by Floppy** [comment]
@mikera the EU FTT is apparently designed not to impact the "real" economy. Worth having a read of the wikipedia writeup, see if it addresses your concerns.

**Comment by tmtmtmtm** [comment]
The new version looks good to me. :+1:

**Comment by philipjohn** [comment]
:+1:

**Comment by Floppy** [comment]
Sorry guys, still tweaking; added a point about global system. Can you vote again?

**Comment by Floppy** [comment]
I'm done now :)

**Comment by philipjohn** [comment]
No :p :+1:

**Comment by tmtmtmtm** [comment]
I'm a little hesitant on the new additional wording, I'm afraid — at least without further elaboration. What's the idea here?

**Comment by Floppy** [comment]
basically any system will work better the more widely it's implemented, so as well as joining the EU one, we'd want to push for a global deal.

**Comment by tmtmtmtm** [comment]
It may just be the wording but "work to create a global system to prevent avoidance" seems quite strong. We've already seen how difficult it is to even get an EU-wide version agreed — what sorts of actions are you proposing to take against countries who don't implement such a tax?

**Comment by Floppy** [comment]
Tried to improve the wording again around the global FTT regime. Basically I'm trying to say that we'd join the EU FTT system, but with the understanding that to work properly in a globalised economic system, the tax needs to be global.

**Comment by tmtmtmtm** [comment]
I'm a strong believer in meddling in other countries' affairs as little as possible, and I'm distrustful of most attempts to create a global regime for anything. But I'd be OK with wording like "We would also work with international organisations to broaden such a regime beyond the EU".

**Comment by Floppy** [comment]
Ah, that's better. Thanks, I was just looking for decent wording :)

**Comment by Floppy** [comment]
done

**Comment by philipjohn** [comment]
:+1:

**Comment by tmtmtmtm** [comment]
:+1: from me then too :)

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are a [contributor](https://votebot.openpolitics.org.uk/proposals/) to this repository (and not the proposer), you may vote on whether or not it is accepted. 

## How to vote
Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

|vote|symbol|type this|points|
|--|--|--|--|
|Agree|:thumbsup:|`:thumbsup:`|1|
|Abstain|:hand:|`:hand:`|-1|
|Block|:thumbsdown:|`:thumbsdown:`|-1000|

Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 7 days, but will be closed if the proposal is not accepted after 90.

Votes are counted [automatically here](https://votebot.openpolitics.org.uk/proposals/221), and results are set in the merge status checks below.

## Changes

If the proposer makes a change to the proposal, no votes cast before that change will be counted.

**Pull request merged**
