### PR TITLE
Generalise the equality section

### PR DESCRIPTION
**Pull request by Floppy**
As I suggested when this page was created, I think for now until we have a lot more there and a split is necessary, this page can cover equality in general, rather than just gender.

### CODE REVIEW

**Comment by philipjohn** [comment]
Vote: ✅

**Comment by Autumn-Leah** [comment]
I was going to transfer a lot of stuff over but I'm very busy atm. I think the page should be kept.

Vote: ❎

**Comment by Polygon48k** [comment]
Vote: ✅

**Comment by Floppy** [comment]
Happy to do the moves if you can point to the bits you wanted to move @autumn-leah?

**Pull request closed without merging**
