### PR TITLE
Education funding changes

### PR DESCRIPTION
**Pull request by yellowgopher**
Split from previous proposed update.  

Move towards an individual pupil funding approach.

### CODE REVIEW

**Comment by philipjohn** [comment]
This sounds good. I have a concern about how quick "the system" will be able to respond to changes in individual circumstances, and the admin overhead such a system will require. That's all implementation detail though - this vision sounds good, so I support it.

For now I'm a :hand: though. You'll get my vote if this bit goes ;) : 
> These funds will be valid as payment towards private education.

**Comment by yellowgopher** [comment]
So why against using these funds for private education/tuition/support?  Many people already hire private tutors to support study etc?

**Comment by philipjohn** [comment]
Private study as an *addition* to a state-funded, secular education is entirely acceptable, if parents wish to do that, but that's individual choice and they can fund it themselves.

**Comment by PaulJRobinson** [comment]
"These funds will be valid towards private education". So is this a proposal for so called 'school vouchers'? i.e. parents can take the money spent on their children's education by the state and use that at an independent school of their choice, and then top it up with their own cash? Because that won't actually help poorer children get into independent schools. It will just inflate the fees from what they are now, to 'plus the addition of the voucher'.

**Comment by yellowgopher** [comment]
There is the argument that private school fees are paid in addition to taxes that fund state school education (there is no rebate if state schools are not used but the funding is there and can be used for other children).  And, as for the inflation of fees for private schools, private schools already do a lot of work to reduce fees for poorer children, have to maintain a charity status by proving they are working for charitable aims and it may even result in an increase in private provision.  However, on balance, I will remove this to get the change through.

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are a [contributor](https://votebot.openpolitics.org.uk/proposals/) to this repository (and not the proposer), you may vote on whether or not it is accepted. 

## How to vote
Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

|vote|symbol|type this|points|
|--|--|--|--|
|Agree|:thumbsup:|`:thumbsup:`|1|
|Abstain|:hand:|`:hand:`|-1|
|Block|:thumbsdown:|`:thumbsdown:`|-1000|

Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 7 days, but will be closed if the proposal is not accepted after 90.

Votes are counted [automatically here](https://votebot.openpolitics.org.uk/proposals/309), and results are set in the merge status checks below.

## Changes

If the proposer makes a change to the proposal, no votes cast before that change will be counted.

**Pull request closed without merging**
