### PR TITLE
Enforce living wage

### PR DESCRIPTION
**Pull request by philipjohn**
An idea to enforce the minimum living wage.

### CODE REVIEW

**Comment by Floppy** [comment]
I'm still :+1: on this btw, although it may be superfluous. No harm in including it.

**Comment by PaulJRobinson** [comment]
I like the idea of harsh penalties for failing to pay LW. But this proposal is a little over the top though isn't it? 100% of profits? 100% of salary? It's not a proportional punishment. Could we amend to something that doesn't sound quite so extreme. It just doesn't sound like we've even thought about it an appropriate punishment.

 Also there's no ability to scale the punishment up depending on the gravity of the offence, or any aggravating circumstances (such as committing a previous similar offence). If one worker in an organisation of 10,000 people is denied LW then the penalty is huge, but it's the same punishment if they deny LW to 5,000 of their workers, or if they've been fined three years in a row for doing the same thing. :-1:

**Comment by philipjohn** [comment]
> It's not a proportional punishment.

Maybe. But here's the reality: income inequality is getting worse. More and more people are slipping below the poverty line. More and more people are having to get what work they can which often means low paid, insecure contracts. Meanwhile, profits at some of the biggest firms are rising, shareholders pockets are being lined ever more thickly.

This proposal provides in law a moral basis for shareholder accountability over workers pay. As a shareholder you should not be profiting from the underpayment of workers. It doesn't matter whether that's one worker or thousands - the crime is the same. Note that the exact wording is "up to" 100% - not exactly 100% in every case.

I'd be willing to add something here to the effect that the fine would be used to a) back-pay workers who haven't received the LW and b) used in the short-term grants scheme to help employees move up to the living wage.

**Comment by Floppy** [comment]
Happy with "up to", yes. And adding those uses of the fine to tie into other policies is a nice idea.

**Comment by philipjohn** [comment]
I've updated to add a bit about using the fines, and also to tweak the wording to say minimum wage given that IS the minimum wage.

**Comment by Floppy** [comment]
:+1: 

Your thoughts, @PaulJRobinson?

**Comment by digitalWestie** [comment]
:+1: yes to this

**Comment by philipjohn** [comment]
@PaulJRobinson What do you think about the change above chap?

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are a [contributor](https://votebot.openpolitics.org.uk/proposals/) to this repository (and not the proposer), you may vote on whether or not it is accepted. 

## How to vote
Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

|vote|symbol|type this|points|
|--|--|--|--|
|Agree|:thumbsup:|`:thumbsup:`|1|
|Abstain|:hand:|`:hand:`|-1|
|Block|:thumbsdown:|`:thumbsdown:`|-1000|

Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 7 days, but will be closed if the proposal is not accepted after 90.

Votes are counted [automatically here](https://votebot.openpolitics.org.uk/proposals/257), and results are set in the merge status checks below.

## Changes

If the proposer makes a change to the proposal, no votes cast before that change will be counted.

**Pull request closed without merging**
