### PR TITLE
National Investment Bank

### PR DESCRIPTION
**Pull request by Floppy**
Taking what I wrote at #442 and putting it into a proposal. It turns out this is very similar to a policy proposed by Corbyn, but that was not on purpose. I'm primarily basing the idea on the Environmental Audit Committee's 2012 report about what the Green Investment Bank should be - ie this https://www.publications.parliament.uk/pa/cm201011/cmselect/cmenvaud/505/505.pdf. If we're happy with this, we can incorporate how we would use the NIB into our already existing policies.

### CODE REVIEW

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are a [contributor](https://votebot.openpolitics.org.uk/users/) to this repository (and not the proposer), you may vote on whether or not it is accepted. 

## How to vote
Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

|vote|symbol|type this|points|
|--|--|--|--|
|Agree|:thumbsup:|`:thumbsup:`|1|
|Abstain|:hand:|`:hand:`|-1|
|Block|:thumbsdown:|`:thumbsdown:`|-1000|

Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 7 days, but will be closed if the proposal is not accepted after 90.

Votes are counted [automatically here](https://votebot.openpolitics.org.uk/proposals/443), and results are set in the merge status checks below.

## Changes

If the proposer makes a change to the proposal, no votes cast before that change will be counted.

**Comment by andrewdwilliams** [comment]
@Floppy For some reason this has registered as you proposing this? Not sure why.

**Comment by Floppy** [comment]
oh, what the f...

right, I'll fix that. Damn. That would explain why I didn't get an email though - did you?

**Comment by andrewdwilliams** [comment]
I did, yes. You can close this if you want and I'll open it again. I may have initiated this clicking through from the somethingnew.org.uk manifesto bit, so that might be something to do with it?

**Comment by Floppy** [comment]
I think we should close this anyway, before anyone votes on it, as it's gone in wrong. I'll fix the code, test, and get you to resubmit. Sorry for the inconvenience!

**Comment by Floppy** [comment]
@andrewdwilliams I think I've fixed the bug now, can you retry this proposal?

**Comment by Floppy** [comment]
@andrewdwilliams you managed to find another bug we'd not hit before. I've fixed it now (again), so please have another go :)

This is all incredibly useful, I assure you! (sorry, though)

**Pull request closed without merging**
