### PR TITLE
Amendment to Poverty

### PR DESCRIPTION
**Pull request by OliverJackson1**
New section called 'burden of childcare' focusing on the long-term goal of free provision.

Also a note of opposition against the proposed amendment to the current Childcare Voucher scheme and a statement on the desire to increase the savable limit to £500. In reality (although, not sure how this would be administered and hate bureaucracy) the voucher limit should be the month cost of childcare. Will keep thinking on how to do that but not sure, any ideas anyone?

### CODE REVIEW

**Comment by andrewdwilliams** [comment]
:+1: I'm happy as long as we don't force this as a sudden increase, which your pull request does not.

**Comment by philipjohn** [comment]
Oh @OliverJackson1 this is great - I've been thinking of exactly this!

The first paragraph is great. On the second paragraph, because it talks about the proposed amendment it risks becoming out of date very quickly. I suggest we remove that for now and, if the government amendment passes, propose in the manifesto that we repeal that change.

Finally, I think the last bit about the tax might conflict with our [income tax policy](http://openpolitics.org.uk/manifesto/economy.html#income-tax).

**Comment by OliverJackson1** [comment]
@andrewdwilliams I would envisage that we would look to undertake this over the course of a parliament. Would you be comfortable with that? Or would that be too fast? 5 years feels about right (two increases with 2 years of embedding for each) but obviously open to comment.

@philipjohn I've amended the second paragraph to remove the proposed change (although I actually think that they passed the bill enforcing the change and have been fighting a legal challenge from a childcare voucher provider). I think they are considering implementation in January 2017.

In terms of the second part of your query I think that I've been vague here, I don't mean a change to income tax (exactly how it reads so hugely confusing :D) I'm talking more about where current limitations are. So for a basic rate tax payer, they don't start paying tax until £243 of their Gross Pay is deducted for Childcare Vouchers. It should read as an increased reprieve from tax not an increase in tax. Does that make sense and would it be worth a re-write?

**Comment by philipjohn** [comment]
Great edit, thanks!

You've explained well and I now understand it's not changing the income tax thresholds :) It's just how the taxable amount interacts with childcare vouchers - gotcha :+1:

**Comment by Floppy** [comment]
👍

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are a [contributor](https://votebot.openpolitics.org.uk/proposals/) to this repository (and not the proposer), you may vote on whether or not it is accepted. 

## How to vote
Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

|vote|symbol|type this|points|
|--|--|--|--|
|Agree|:thumbsup:|`:thumbsup:`|1|
|Abstain|:hand:|`:hand:`|-1|
|Block|:thumbsdown:|`:thumbsdown:`|-1000|

Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 7 days, but will be closed if the proposal is not accepted after 90.

Votes are counted [automatically here](https://votebot.openpolitics.org.uk/proposals/401), and results are set in the merge status checks below.

## Changes

If the proposer makes a change to the proposal, no votes cast before that change will be counted.

**Pull request merged**
