### PR TITLE
modified 50% non-religious

### PR DESCRIPTION
**Pull request by andrewedmondson**

### CODE REVIEW

**Comment by Floppy** [comment]
Seems legit - nice referenced update, thanks :+1:

**Comment by yellowgopher** [comment]
Based on 1000 people out of 65million...!  And that still represents 50% who have a different view.  Some balance people, please!

**Comment by Floppy** [comment]
Interesting: latest British social attitudes survey has CofE at 17.5%, with 48.9% saying "no religion". The rest is made up of other denominations. Not an argument that we're all atheists, but a decent case against special treatment for the CofE. 

I understand the BSA survey is drawn from is a pretty well-sampled selection of around 3300 people.

http://www.bsa.natcen.ac.uk/media/38945/bsa32_fullreport.pdf

**Comment by andrewedmondson** [comment]
No it is based on 1905 people interviewed.

http://www.brin.ac.uk/news/2015/easter-religion-and-other-news/

**Comment by yellowgopher** [comment]
Gallop had a similar result on 1000 people - http://wingia.com/en/news/losing_our_religion_two_thirds_of_people_still_claim_to_be_religious/290/
I think I said I was happy for CofE to be disestablished anyway :-)

**Comment by philipjohn** [comment]
:+1:

**Comment by PaulJRobinson** [comment]
:+1:

**Comment by Floppy** [comment]
We seem to be happy with this, without any blocks. The numbers are sourced, and if there are good sources for changing the number to a better estimate, it can happen in another PR. Merging.

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are a [contributor](https://votebot.openpolitics.org.uk/proposals/) to this repository (and not the proposer), you may vote on whether or not it is accepted. 

## How to vote
Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

|vote|symbol|type this|points|
|--|--|--|--|
|Agree|:thumbsup:|`:thumbsup:`|1|
|Abstain|:hand:|`:hand:`|-1|
|Block|:thumbsdown:|`:thumbsdown:`|-1000|

Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 7 days, but will be closed if the proposal is not accepted after 90.

Votes are counted [automatically here](https://votebot.openpolitics.org.uk/proposals/326), and results are set in the merge status checks below.

## Changes

If the proposer makes a change to the proposal, no votes cast before that change will be counted.

**Pull request merged**
