### PR TITLE
DRIP Repeal

### PR DESCRIPTION
**Pull request by andrewdwilliams**
Follows on from Issue #339

### CODE REVIEW

**Comment by Floppy** [comment]
I'm in 👍

**Comment by philipjohn** [comment]
:+1:

**Comment by OliverJackson1** [comment]
The right to privacy is the cornerstone of Liberty and Freedom. It is the foundation upon which we build our society. Legislation like this seeks to subvert this and the power of the people. I get so freakin' mad when I read about it! I get even madder(er) when people tell me they don't mind because they have nothing to fear. :+1:

**Comment by glynnchaldecott** [comment]
👍

**Comment by philipjohn** [comment]
@OliverJackson1 Looks like we might need you to [sign the CLA](http://www.clahub.com/agreements/openpolitics/manifesto) so that you can effectively contribute :)

**Comment by philipjohn** [comment]
@glynnchaldecott I think we need you to sign the CLA for your vote to count: http://www.clahub.com/agreements/openpolitics/manifesto

Looks like this has passed regardless, so merging

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are a [contributor](https://votebot.openpolitics.org.uk/proposals/) to this repository (and not the proposer), you may vote on whether or not it is accepted. 

## How to vote
Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

|vote|symbol|type this|points|
|--|--|--|--|
|Agree|:thumbsup:|`:thumbsup:`|1|
|Abstain|:hand:|`:hand:`|-1|
|Block|:thumbsdown:|`:thumbsdown:`|-1000|

Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 7 days, but will be closed if the proposal is not accepted after 90.

Votes are counted [automatically here](https://votebot.openpolitics.org.uk/proposals/388), and results are set in the merge status checks below.

## Changes

If the proposer makes a change to the proposal, no votes cast before that change will be counted.

**Pull request merged**
