### PR TITLE
Added new sub section on International Development in Foreign Policy

### PR DESCRIPTION
**Pull request by DaveBloke**
Water and Sanitation ensure that fewer children die of preventable diseases.  The reduction in child mortality his leads to a drop in birth rates (see www.gapminder.org esp Don't Panic by Hans Rosling).  Half the beds in developing country health facilities contain people suffering from diseases caused by poor water and sanitation.  Also millions of school days a year are lost due to diarrhoeal diseases.  Underpin spending on health and education facilities with safe water and sanitation to make them more efficient.

Statistics from www.wateraid.org

### CODE REVIEW

**Comment by Floppy** [comment]
:+1:

**Comment by philipjohn** [comment]
:+1:

**Comment by tmtmtmtm** [comment]
:-1: 

I'm certainly not opposed to doing more in this area, but this proposal calls for reducing the amount of aid delivered to other projects by approximately £1b a year — whilst providing no details of which projects should be cut, or why they are clearly less important.

**Comment by Floppy** [comment]
My assumption here is that much of our aid budget goes on military aid, which we would reduce. Is that right @DaveBloke? Would it be possible to add a little explanation of what would be reduced to the change? You can edit it at https://github.com/DaveBloke/manifesto/edit/20150212205034/manifesto/foreign_policy.md to do that...

**Comment by tmtmtmtm** [comment]
> My assumption here is that much of our aid budget goes on military aid, which we would reduce

Have you a source for that? After the recent commitment that increased aid funding generally, there was some talk of a small amount of the new money possibly being allocated to the MoD for "security, demobilisation and peacekeeping" missions, but as I understand it, that would be an entirely new thing, as currently none of the budget can be used like that. I'm also not sure if that was actually approved, as there was quite a lot of pushback against it[1]. I certainly can't see anything on the [DFID Tracker](http://devtracker.dfid.gov.uk/) that could be classed as military aid.

However, even if an extra £1bn suddenly became available, a stronger case needs to be made as to why that should all be allocated specifically to water projects at the expense of all the other aid areas.



[1] If it *was* approved, I'm certainly amenable to something that undoes that again.

**Comment by Floppy** [comment]
No, not at all, that was just an assumption on my part, as I said. Is there a breakdown of where the money goes on in DFID data that we could look at? There were some ID hackdays that must have done some analysis on this as well...

**Comment by tmtmtmtm** [comment]
Yes — the link in my previous comment has lots of data: [DFID Tracker](http://devtracker.dfid.gov.uk/) 

Unfortunately the "by sector" breakdown is less than helpful, as almost 40% of the spending is uncategorised, but you can drill down into it and see all the individual projects.

**Comment by Floppy** [comment]
Ah, sorry, I was reading on email, didn't see the link. Thanks :)

**Comment by philipjohn** [comment]
The DFID tracker is useful in many ways. Do we want a policy that ensures aid is directed to the people on the ground, delivering the basics for them to build on?

If so, I'd suggest we should question the following sectors: Budget, Business, Finance, Government, Industry, Multisector, Trade, Unallocated.

Together these make up 50.5%, but it's unclear what they are funding. What is "Government" funding for example? Or "Industry"?

Should 16.95% of India's aid be spent on Government? Or the 27.91% on South Africa?

Certainly, at 1.82% of the aid budget, Water projects get a very small amount of funding and yet 500,000 children die every year due to lack of unsafe water sources[^1].

So I think there is evidence that a higher proportion needs to be spent on water in aid funding, and I don't think it's fair to completely block this proposal because of it.

Perhaps the proposal could be tweaked to remove the 10% target, and leave the specificity to implementation. Or a more general rebalancing of foreign aid goals to health, water, environment? What do you think @DaveBloke ?

Remember: the manifesto is a "wish list" not an exact 5-year plan.

1. [Water Aid](http://www.wateraid.org/uk/what-we-do/the-crisis/water)

**Comment by DaveBloke** [comment]
Hi there,

 

I’m new to the joys of GitHub, but hope that this works!

 

The UK is currently committed to spend 0.7% of Gross National Income on International Development.  This is the target figure approved by the UN and the UK is one of only a few to currently meet it.  There was recently cross-party support to a bill to enshrine this figure in Law in order to bind the new Parliament.  It passed in the Commons but I’m not sure of how it has subsequently progressed in the Lords, and whether it has yet received Royal Assent. 

 

The outline of current UK spending by the Department of International Development is summarised in the recent press item attached.

 

The International Development budget has nothing to do with defence spending.

 

The way that much of the DFID spending is allocated is to support specific projects.  For example last year WaterAid ran an project called ‘To be a girl’ to support water and sanitation projects in Ethiopia in which the WaterAid funds raised were matched pound for pound by DFID, with a specific UK Aid logo being attached to the projects.  Google ‘WaterAid To be a girl’ and ‘WaterAid The Big Dig’ to see what kind of thing is done.  I recall that at Christmas 2013 DFID was similarly doubling all cash raised from donations to Oxfam shops.  This is an example of way they work -  using known an approved agencies to spend the money wisely. 

 

Because much of the spending is allocated in fixed amounts to certain cash and time limited projects redirecting the balance of the funding towards water and sanitation will not cut off money to current international projects.  The point of increasing the proportion spent on water and sanitation within the current figure is to make the money that is spent on health and education more efficient.  It’s no good building a school for 500 pupils if many of them are off sick with diarrhoeal diseases caused by unsafe water and poor sanitation.  Also half the beds in the health facilities of developing countries contain people with illnesses associated with unsafe water and poor sanitation.  This economic argument is, of course, in addition to the humanitarian argument about saving lives.

 

The argument that ‘Countries should do it for themselves’ overlooks just how recently the UK has moved from appalling water and sanitation conditions.  Victorian London was an open cess pit.  My home town of Farnham in Surrey only got a fully operating sewage works 111 years ago!  Developing contrives need training and a bit of funding to help themselves to catch us up.

 

Take a look at a page of sourced statistics at http://www.wateraid.org/uk/what-we-do/the-crisis/statistics 

 

Yes, I am a WaterAid volunteer, but why should that stop me aiming to get a sensible Party to try and adopt sensible policies?

 

 

Dave

**Comment by Floppy** [comment]
Thanks for all that info @DaveBloke, and thanks for coming back :)

Be assured that all discussion here is constructive, and it's *great* to have people who care passionately about certain issues proposing them for inclusion, so no problem there!

I think the only issue that we see is the setting of the percentage of aid going to water, and what is reduced to compensate. @philipjohn's suggestions of the areas that could be reduced seem reasonable, though it's guesswork really. Do WaterAid have any info on that that you could link us to?

**Comment by DaveBloke** [comment]
Hi there,

 

If the specific target of 10% on water and sanitation by the end of the Parliament is a deal breaker then it seems fine by me to drop it, but keep hold of the idea of an increased proportion of the 0.7% on water and sanitation.

 

As all the discussion has been on the DFID spending I assume that everyone is happy with the proposal that the UK back the ideal of a dedicated target on water and sanitation in the UN Sustainable Development Goals for 2015-2030 being agreed in the autumn.

 

Dave

**Comment by Floppy** [comment]
I'm certainly fine with that.

**Comment by DaveBloke** [comment]
Hi there,

 

The discussion is right in that water and sanitation spending is low, and difficult to disaggregate.  The figure of 1.8 of the DFID budget agrees with what I have been told by WaterAid.  A quick search on www.wateraid.org found this briefing paper:

 

file:///C:/Users/Dave/Downloads/sanitation-dfid.pdf <file:///C:\Users\Dave\Downloads\sanitation-dfid.pdf> 

 

 

 

Dave

**Comment by PaulJRobinson** [comment]
:+1: I like this proposal. Good work Dave.

**Comment by tmtmtmtm** [comment]
> I think there is evidence that a higher proportion needs to be spent on water in aid funding, and I don't think it's fair to completely block this proposal because of it.
> Remember: the manifesto is a "wish list" not an exact 5-year plan.

If we look deeply at all the aid areas (and even more so if we have someone lobbying on each), I'm sure we'll very quickly agree that many of them would benefit greatly from significant extra funding. But simply plucking a figure of 10% of spending out of the air, without any reference to how or why, is not a good way to set policy. The manifesto needs to at least be *vaguely* realistic — otherwise why not just say "Eradicate all preventable diseases worldwide?" 

As I said, my objection here isn't that this is an unimportant area. It's that as currently written this proposal says: "Decrease all other international aid spending by ~£1bn per year, and allocate that money to water related projects instead". I very strongly believe that that's not even a sensible wish, and even if we already had the hand/-1 split, this would still be a -1 from me.

**Comment by tmtmtmtm** [comment]
@DaveBloke : that briefing paper didn't attach properly — it's just a reference to `file:///C:/Users/Dave/Downloads/sanitation-dfid.pdf`

**Comment by tmtmtmtm** [comment]
I've added https://github.com/openpolitics/manifesto/pull/281 separately for the core issue of maintaining the commitment to allocate 0.7% of GNI to Aid, and keeping that distinct from military spending. That can give proposals like this a cleaner base from which to expand.

**Comment by DaveBloke** [comment]
Hi tony Bowden,

An earlier comment I sent pointed out that dfid funding went to time and expenditure limited projects, so no current project would be cut off part way through.  

My point about the economic argument is basically that current education and health spending is being partly wasted as children miss school through illness caused by unsafe water and sanitation.  The most recent estimate I saw was in the region of xxx per year.  

If people were not getting sick from poor water and sanitation the 50% of hospital beds being occupied by people suffering from disease caused by poor water would be available to treat other illnesses.

This is not about extra funding but about current funding more efficient.

Dave

**Comment by DaveBloke** [comment]
Sorry about the dodgy link.

 

Try this and go to the second item down

 

http://www.wateraid.org/uk/google-search?query=dfid+spending

 

 

Dave

**Comment by DaveBloke** [comment]
Hi Tony,

 

What about the support for a stand alone target for water and sanitation in the UN Sustainable Development Targets 2015-2030?

 

Dave

**Comment by Floppy** [comment]
@DaveBloke the 0.7% target has been passed and added separately to this - could we please get you to resubmit your proposal based on the current wording on the site?

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are a [contributor](https://votebot.openpolitics.org.uk/proposals/) to this repository (and not the proposer), you may vote on whether or not it is accepted. 

## How to vote
Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

|vote|symbol|type this|points|
|--|--|--|--|
|Agree|:thumbsup:|`:thumbsup:`|1|
|Abstain|:hand:|`:hand:`|-1|
|Block|:thumbsdown:|`:thumbsdown:`|-1000|

Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 7 days, but will be closed if the proposal is not accepted after 90.

Votes are counted [automatically here](https://votebot.openpolitics.org.uk/proposals/278), and results are set in the merge status checks below.

## Changes

If the proposer makes a change to the proposal, no votes cast before that change will be counted.

**Pull request closed without merging**
