### PR TITLE
Adding abstain voting

### PR DESCRIPTION
**Pull request by Floppy**
The votebot now supports abstentions, so they need adding here as well as an addition to the voting rules. I've enabled them in the bot already as this is really a non-issue, but if there is a problem with allowing this, I'll roll it back.

### CODE REVIEW

**Comment by Xyleneb** [comment]
I usually just abstain by dodging the vote like Diane Abbott. What's the difference?

**Comment by Autumn-Leah** [comment]
I'm tempted to abstain from this as a joke, but I won't :D Good work re: the abstain vote.

Vote: ✅

**Comment by Floppy** [comment]
@xyleneb if someone didn't vote we don't know if they didn't get round to it, or meant not to. It's not compulsory at all, but a way of saying "I'm not voting". A bit like a "none of the above" in elections.

**Comment by Autumn-Leah** [comment]
@Floppy Speaking of the abstain vote, you might want to add it to the vote count system on the proposals page since abstain votes don't have a column yet

**Comment by Floppy** [comment]
I was wondering about that, whether it will add anything or just add more clutter to those lists. I'll see what it looks like.

**Comment by philipjohn** [comment]
Vote: ✅

**Pull request merged**
