### PR TITLE
Added new section about relocating parliament

### PR DESCRIPTION
**Pull request by jt-nti**

### CODE REVIEW

**Comment by Floppy** [comment]
I'm all for this - I could have sworn we had something in here already, but I can't find it. Perhaps it never got through before.

Vote: ✅

**Comment by philipjohn** [comment]
Vote: ✅

**Comment by Floppy** [comment]
Sorry @jt-nti, this should have automatically merged by now, but I broke something. I thought I'd fixed it Sunday night, but apparently not. Bear with me :)

**Comment by Floppy** [comment]
Vote: ✅

**Comment by Abilashs003** [comment]
yes

**Pull request merged**
