### PR TITLE
Student unions

### PR DESCRIPTION
**Pull request by Autumn-Leah**

### CODE REVIEW

**Comment by Floppy** [comment]
Vote: ✅

**Comment by andrewdwilliams** [comment]
Surely 'strike action' taken unilaterally by a bunch of secondary school students could easily be manipulated as a way to skive off school? It sounds just like something I would have done a couple years ago, I can tell you that.

**Comment by Autumn-Leah** [comment]
And why should that mean that they shouldn't be allowed to? The same query could be levelled at uni students, or college students. When it comes down to it, if you want to skive, you're going to skive, and if you're not allowed to skive, you'll be messing about in class, regardless, disruption will happen, so I figure it's better to increase their freedoms and take the risk or disruption or skiving when the risk is already being taken by having them there in the first place minus the freedoms.

**Comment by Autumn-Leah** [comment]
If you can think of a reasonable preventative measure to stop this *within the union* (since letting school admin do it means you're neutering their ability to take action) that would apply to secondary school students then I'm all ears. I'd like to edit the policy to fit your complaint but nothing is coming to mind.

**Comment by philipjohn** [comment]
Could you help me understand this by explaining a little more about current rules around student unions at the moment, in the context of this proposal, and how this proposal would change that?

**Comment by Xyleneb** [comment]
In my view: the rule(s) is(are) fine, but the enforcement is not.

Schools will find any excuse to sanction you. Students will find any excuse to avoid being sanctioned. Countless arguments have stemmed from it, and in my view it would be better to explain what ought to happen to the schools/students who engage in it.

It's incredibly unclear to parents/school admin as it stands. It could do with improving.

Another thing is that; enforcement of the rules (should somebody break them) is seldom restorative. How is fining some parents going to help anyone to attend class?

**Comment by Autumn-Leah** [comment]
@phillipjohn There currently is no legislation regarding student unions below university level.

I'm not a legal professional but if I [go](https://en.wikipedia.org/wiki/Student_unionism_in_the_United_Kingdom#Law_relating_to_students.27_unions) down [the](https://en.wikipedia.org/wiki/Education_Act_1994) rabbit [hole](http://www.legislation.gov.uk/ukpga/1994/30/part/II), my interpretation of this law is that it deals with uni student unions only and that it makes no statements regarding unions at any other level. This legislation gives the governing body (the university) direct control over the students union, which, if the goal of a union is to change the practices of the institution they are in (like every trade union ever), means that the unions power is only as much as they are given, meaning it's a glorified school council, albeit *slightly* harder to disband given the NUS.

This proposal would remove governing body control over the unions and their actions (provided their actions fit in with other legislation of course, such as laws against defamation and slander, they can't go round saying that the head of the school is a murderer without consequences or anything) and promote union formation in institutions that don't have them, and would thus constitute a grander push towards the reformation of institutions towards the rights and needs of the students, rather than simply letting them be screwed over by people who are fine in their jobs whether the students are happy and able to learn or not, provided they put on a nice one-day show for Ofsted or whatever other government body is doing it now.

**Comment by Autumn-Leah** [comment]
@Xyleneb This is likely entirely my fault but I'm lost in regards to your comment, how does that relate to the policy proposal?

**Comment by Autumn-Leah** [comment]
@Xyleneb This is likely entirely my fault but I'm lost in regards to your comment, how does that relate to the policy proposal?

**Comment by Autumn-Leah** [comment]
> http://www.itv.com/news/tyne-tees/2017-03-11/protest-after-north-yorkshire-school-limits-toilet-breaks-to-just-two-a-day/

Example A of why we need student unions, they just protested without one.

**Comment by philipjohn** [comment]
Thanks! That's really useful. Any chance we could tweak this bit?:

> and participants will be immune from school sanctions unless another offence has been commited against the school rules and/or policy other than the temporary truancy of strike action or the disrespect to staff created passively through civil disobedience. 

I'm worried it sounds like students will get away with murder :) Perhaps something like this instead?:

> Student union action will be protected, ensuring students aren't unfairly penalised or sanctioned for engaging in protest activity.

**Comment by Xyleneb** [comment]
>This is likely entirely my fault but I'm lost in regards to your comment, how does that relate to the policy proposal?

Take this for example: "participants will be immune from school sanctions unless another offence has been commited against the school rules.."

Now how long do you believe it will take before the school claims "your trouserlegs are 1 inch too short/long"? They will find any excuse to treat you poorly. What happens to the students or to the schools who do these sorts of things in bad faith?

You haven't really addressed the question of how this will be enforced. Which is important because enforcement is where all of the aggrievances set in. Address the enforcement and you've got something that'll be worthwhile.

**Comment by Autumn-Leah** [comment]
@phillipjohn All that does is make it more vague, in reality, it'd have to be the policy I wrote out for it to be effective. Just because it doesn't sound nice, it doesn't mean that students get to do whatever they like.

My specific issues with you being vague:

> Student union action will be protected

This tells nobody what out policy is. As someone who reads a lot about politics, and has read a hell of a lot of political party manifestos, people making vague positives statements like "we will fight to make sure everyone gets paid what they deserve" or somesuch meaningless shit, really pisses me off. Not an issue with your proposal individually, just an ongoing issue with political manifestos.

> , ensuring students aren't unfairly penalised or sanctioned

Who decides what fair and unfair is? With this section alone you open a whole philosophical can of metaphorical worms that could really screw students over.

> for engaging in protest activity

Who decides what "protest activity" is and what "engaging" in it means? If I go to a class and don't do my work because I can't be bothered or I just don't want to, would that come under the establishments definition of "protest activity"? Who knows? Because once you give the people in power the ability to fuck with definitions that affect you personally, 99% of the time you get screwed when offering any kind of resistance unless you literally get the whole school/workplace/whatever. 1 scab in the whole place and they regain their ability to mess with you. That's not an exaggeration, since they can mess with you via the scab now since there's likely people in your strike who personally know and like the scab.

> activity

I know you didn't mean it like this but screw it, since I'm picking apart your wording lets beat the horse corpse. Activity sounds more like a paper mache club than a student union strike. It would also screw with students because if the schools decide to define "strike activity" as a strike that the school allows, the union now has no power unless they do it anyway, at which point they have less support because the view would be spread amongst students that it has to be school sanctioned.

*Any legislation in this area needs to be unambiguous and unambiguously pro student. If they are subjected to a system of governance mandated by the government, then they **must** have the tools they need to defend their rights and enforce the manifestation of their needs, but this does not mean that they get to run rampant with their **wants** *

**Comment by Autumn-Leah** [comment]
@Xyleneb Given the comment I just responded to, irony noted. What would you suggest I change it too? Obviously violence is out of the question but what if someone blocked the school entrance and you needed to shove them out of the way. That could be considered it. We ***need*** a way around this issue because as I stated in my last comment

> Any legislation in this area needs to be unambiguous and unambiguously pro student.

but I can't think of a way to word it at the moment. All I know is how *not* to word it.

**Comment by Autumn-Leah** [comment]
@Xyleneb Either way, thanks for the clarification.

**Comment by philipjohn** [comment]
It's important to remember that a manifesto isn't the acts of Parliament it wants to create. Things like the specifics of what constitutes protest activity are the very things that will take up multiple paragraphs in an act - we can't do that here, it's just not feasible.

The manifesto is to state our *aims*, and our vision of *what* we want, not the detail of *how* we'll get it. For example;

> Who decides what fair and unfair is?

The government that implements this manifesto will decide. They will go through the process of working with a bunch of legal experts to draft a bill that meats the aims of the manifesto. That may well happen after some sort of consultation with universities, students and others on what *they* think is unfair as well as what constitutes protest activity.

> Any legislation in this area needs to be unambiguous and unambiguously pro student.

Any legislation on any area needs to be reasonable and measured, not biased to any one particular party. It would otherwise be unfair, and that'd open it up to legal challenges.

> Because once you give the people in power the ability to fuck with definitions that affect you personally,

The definitions have to be contained within the acts of Parliament, so they have to be written by those in power - that's farely fundamental to how legislation works, and has to work.

The aim here is fine, but the wording needs to be more measured. Happy to work with you on that and turn my vote into a yes.

Vote: ❎

**Comment by Xyleneb** [comment]
>The aim here is fine, but the wording needs to be more measured. Happy to work with you on that and turn my vote into a yes.

Well, the problem is that unions are a mechanism in which to hold schools and businesses to account. Those schools and businesses already have their own, separate mechanisms to hold their employees, or students, or "internal customers" to account. It'll prove difficult to balance the wording here in view of that.

>It's important to remember that a manifesto isn't the acts of Parliament it wants to create. Things like the specifics of what constitutes protest activity are the very things that will take up multiple paragraphs in an act - we can't do that here, it's just not feasible.

If you do not detail what constitutes protest activity, then you leave the door open for you to backtrack or demasculate the policy once you get into office. It means that when voting day looms, I look at your party and see a bunch of fluff that is non-committal.

If our manifesto ends up longer than anybody elses, the way I see it, in a way it'll be us doing our job properly.

My issue with this submission concerns enforcement. If you don't detail the enforcement then the rules will be toothless. Rules which cannot be enforced are a waste of parchment. My concern about this not only includes this submission, but my own 'Cash for Access' policy (which passed the vote) and floppy's submission on political canvassing, to name three... I'm asking myself what's the point having it on the books if I can't enforce it?

**Comment by Autumn-Leah** [comment]
Because @Xyleneb said what I was just about to before I refreshed the page, I'm just going to point out a few things.

> The government that implements this manifesto will decide.

Letting the political and philosophical equivalent of toddlers decide what fair and unfair punishment is is exactly why Snowden is still chilling (possibly quite literally) in Russia, Assange is still stuck an embassy surrounded by police, and Guantanamo even existed in the first place. If you want to turn our manifesto into fluff and leave the important philosophical, political, and practical decisions to a hypothetical bunch of old, rich, "daddy-didn't-give-me-a-pony-so-I-cried" morons in a future parliament then you have way more trust in government than I do and I hope room 101 treats you well.

> That may well happen after some sort of consultation with universities, students and others on what they think is unfair as well as what constitutes protest activity.

Yeah, I know, government is always great at representing the opinions of the populous and consulting them! ...[oh](https://www.theguardian.com/commentisfree/2017/feb/13/whistleblowers-official-secrets-act-law-commission)...ignore that, that example of lopsided consultation hasn't got anything to do with the current point about how governments don't do consultations properly.

> Any legislation on any area needs to be reasonable and measured, not biased to any one particular party. It would otherwise be unfair, and that'd open it up to legal challenges.

You don't need to and shouldn't be unbiased here. Schools already have accountability mechanisms for the student, they're called school rules and laws. Students have nothing. The *entire* purpose of this policy is to equalise the power imbalance **so the teachers and admin can't just get away with doing whatever they like.** ***Do you even understand the purpose of a trade union? It's fixing the power imbalance between employer and employee. The entire party platform is built on accountability, openness and non discrimination.***

Given all of the above, you can keep your downvote if you like, but you've lost all respect of mine.

**Comment by philipjohn** [comment]
> Letting the political and philosophical equivalent of toddlers decide

I'm really confused by this. Any government that is going to implement the words you and I write into this manifesto will surely believe in this manifesto, no? Otherwise, who are we writing this for? For ourselves, for a laugh?

It may be that you're disillusioned and I'm guessing that's why you're here. But if this manifesto gets to the point where a government is implementing it, I'm not sure tarring that government with the same brush as current or previous governments makes much sense - to me, that's suggesting that any future government that gets elected standing on the OpenPolitics Manifesto is already untrustworthy. If that's so, let's just stop now and not waste any more time.

 > Yeah, I know, government is always great at representing the opinions of the populous and consulting them!

Yep, governments are and have not been good at actually consulting. One of the many reasons we write this manifesto. Do you think that if some people stood on this manifesto and made it into government they would just turn around and do the same thing as current and previous governments? If so, why are you writing this for them if you know they are going to just ignore it anyway?

> The entire purpose of this policy is to equalise the power imbalance so the teachers and admin can't just get away with doing whatever they like.

Great! Then let's make sure the policy is equal. Let's make sure it addresses the current deficiencies without giving too much power to either interest group. Otherwise, we're just going to be instantly alienating the interest group we're biased against, and inviting upon any government implementing this the kind of legal changes that'll end up forcing a change in the law we might not like.

**Comment by philipjohn** [comment]
> If our manifesto ends up longer than anybody elses, the way I see it, in a way it'll be us doing our job properly.

Nobody will read it ;)

**Comment by Autumn-Leah** [comment]
Respect somewhat restored @philipjohn

Moving on from that, how are we going to change the policy so that teachers can't just say "lol ur skirt's to high stop the strike ya prole"? @Xyleneb

@philipjohn What objection do you have other than it might be worded in such a manner that "it sounds like students will get away with murder" which isn't really a problem of the policy, just with your interpretation of the policy? Because your version of the same policy is just fluff that's put at the mercy of some future hypothetical people and explains nothing about what we'd actually do, if I saw that on election day, I'd vote PPUK instead.

**Comment by Xyleneb** [comment]
>Nobody will read it ;)

Each page may have over 250 policies on there, by the end of what I consider to be this experiment. But ad-hoc organising will form a somewhat rational structure. People will jump to the sections that most concern them. And unlike Hilary Clinton's 58 policies on Healthcare, e.g. "we will try to be kind to the elderly" (that failed to get her elected...) ours will be a hell of a lot more precise and committal. Hopefully a lot more populist as well. I know you don't rate populism, but I do. Real populism though, not that phony populism that merely eats bacon sandwiches (or attempts to).

**Comment by Autumn-Leah** [comment]
Is this balanced enough for you guys? @Xyleneb @phillipjohn

**Comment by philipjohn** [comment]
Very thorough 🙂

Vote: ✅

**Comment by philipjohn** [comment]
This has technically passed now, but let's give @andrewdwilliams some time to take a look at the update.

**Comment by Xyleneb** [comment]
The point on proportionate self-defence gets a little too deep into it.
There's a spelling error around 43.4, ctrl + f "legistlation".

>Very thorough

Every so often, you get a submission that is not just an old idea repeated (like most of mine) but one that took original thought and hand-chiselled grammar to put that thought into words.

These are the policies to be proud of.

It's redundant now but I thought I ought to: :white_check_mark:

**Comment by Floppy** [comment]
I love that I can disappear for a few days, come back to a huge thread with contentious aspects and worried that I have to make peace between everyone, and then find at the bottom that the consensus process has worked, and everyone is happy. Makes me smile. Thanks everyone for working together through the controversial stuff :)

That said, I find the way it's currently written quite hard to read, so I might submit a simplifying edit when I'm less tired just to make it easier ;)

Anyway, it's passed

**Pull request merged**
