### PR TITLE
Resubmission: Changes to School Uniform Regulations

### PR DESCRIPTION
**Pull request by Autumn-Leah**

### CODE REVIEW

**Comment by Xyleneb** [comment]
Per the 3rd-to-last post I gave in issue #515;

Can you re-word this to account for the abolition of uniforms?

**Comment by Autumn-Leah** [comment]
@Xyleneb I don't see how I can do that cleanly given the wording but if you can edit that in and reply with that version then I've no objections to changing it and trying to pass a version that accounts for that

**Comment by philipjohn** [comment]
Vote: ✅

**Comment by Floppy** [comment]
We'll have to see which merges first and then adjust whichever remains open to fit. Conflicts often happen with longer-lived proposals, that's why we kill them after 90 days :)



Vote: ✅

**Pull request merged**
