### PR TITLE
Replacing the CoC and it's Concession of Rights

### PR DESCRIPTION
**Pull request by Xyleneb**
How to explain this.txt

Last time I was here I left in a huff because I held the view that contributing here is akin to signing all of your rights away. You can view that debate in issue #514 if you want. Essentially, my view on that hasn't changed and to me it appears to be a similar sort of situation to a Great Britain pre-magna carta. I don't like it very much.

I'd been thinking what to do about it:
I could fork the project. I think it would be useful somewhat, exactly how much I'm not sure. Nevertheless it's most certainly hard to do. It gives you some appreciation for the scale of the work that's already been put in.

I could have submitted an immediate repeal bill to request 514. Given that this was already voted for favourably and already sort-of on the books, it seemed to me to be counter-productive.

I could submit the alternative GNOME code of conduct. It gives you vague notions of what you are or aren't free to do, which is better than explicitly yielding those rights just to input anything into the project. But as an improvement, it's not much of one. It contains the sort of rules befitting a small project that exists just to keep things in check. If you have grandiose ambitions for the project or foresee it having millions of contributors, then you're going to need to get serious about it.

Which is what I've tried to do. I should point out that there should be a clause saying that this is not a legally-binding document, because it's got a lot of legalese in it. I try to avoid it (the simpler the words, the better) but it's hard to define these concepts outside of it.

Anyway... the last option is to submit an entirely new Code of Conduct. Great idea! Except that I'm struggling to write it. Constitutions are better as group projects. I like the scrutiny. So... this is why I'm submitting it, and this is why I'm submitting it unfinished. The reason I'm submitting it as a pull request, regardless of any vote outcome is because I don't want it to languish in the Issues/Ideas page. I want people to see it and to build on it.

I hope that explanation makes sense and I hope it eventually comes to something.

### CODE REVIEW

**Comment by philipjohn** [comment]
> complaints bureau

What is the complaints bureau?

> complaints jury

What is the complaints jury? Who is on it? How are they selected?

> Complaints addressed to party leadership

Open Politics is not a party.

> It must never be the responsibility of party leadership to determine whether conduct is acceptable or not within the public realm, or in any other place.

Again, not a party, but also as everything to do with the manifesto *is in the public realm* this sentence would render this entire CoC toothless.

> a representative will be called upon

Who will choose the representative, from where, and how will they be assessed for their suitability?

**Comment by Xyleneb** [comment]
>What is the complaints bureau?

I thought of having two juries: one to determine whether a complaint is actionable, and another to determine what action should be taken if any.

I didn't know what to call them, so... complaints bureau/complaints jury. You could call them higher and lower jury, jury 1 & 2, or some better name that hasn't come to me. The reason for two of them is to maintain impartiality between initial judgement and 'sentencing'. You could appeal either one possibly.

>Who is on it? How are they selected?

Availability, then random selection from those available.

Ohh and another reason for two juries: You could have the bureau set the trial date to a time when more people are typically available, and then re-run the random selection so that the jury is more representative of the total.

>Open Politics is not a party.

Something New is the only party I know of whose aim is to implement this right now. But when you have more parties, 'party leadership' would apply to each of them respectively. Or can you think of a way to word it that makes sense in some other context? Such as a union? Or 'leaderless party'?

>Again, not a party, but also as everything to do with the manifesto is in the public realm this sentence would render this entire CoC toothless.

I put that in to write them out of these decisions on proper conduct. Their job is to just press the ban button. They don't pass sentencing, ever.

I've noticed this is a problem because I've inadvertently made it impossible for them to sit on the jury. Which is fine if you've got enough people (and you don't mind leaders being treated differently on account of their position) but not if you can't form a jury as the most active members are all involved in some leadership capacity.

>Who will choose the representative, from where, and how will they be assessed for their suitability?

I hadn't put much thought into that. I was thinking again of availability and random selection, but suitability for the task then would be a lucky dip. Perhaps you should have to volunteer forward. Perhaps you get to pick from the 'available' roster. The idea anyway stems from helping people who struggle to elocute events or what was said or why they did things. In real legal cases the representation is there to study and then interpret the law. Which I was hoping would not be necessary (hence no judge either) as these rules are not designed to govern the nuances of wider society, they're just there to settle disputes with the greatest degree of restraint and impartiality that we can afford to do.

**Comment by Autumn-Leah** [comment]
Ok, I like this idea alot. But honestly, you need to rewrite the whole thing, it's messy, inefficient, and leaves way too many holes open. This is your version:

> Brief
This code of conduct aims to detail the nature of improper conduct and explain how the complaints process works.
**Who can file a complaint?*"
All have the right to file a complaint regardless of position or status.
**Who handles the complaint?**
You will be asked upon the submission of a complaint who you wish to address it to. If a dispute cannot be settled between the relevant parties, then you must address a complaint to the complaints bureau. A complaints jury will determine whether or not your submitted complaint is valid and actionable. Complaints addressed to party leadership regarding other members will be automatically forwarded to the complaints bureau.
**What are the rules for the jury?**
Examples of non-protected speech include: Credible threats of physical harm Words or imagery that are demonstrable of actual malice Publishing others' private information such as a physical or electronic address, without explicit permission
**What is the burden of proof required?**
In order to meet the standard and prove something by clear and convincing evidence, a party must prove that it is substantially more likely than not that it is true.
**Who determines the process?**
The rules of conduct and discourse shall be determined by party members themselves. The responsibility of party leadership begins and ends at authorising the use of such outcomes based on the verdict arrived at by the jury. It must never be the responsibility of party leadership to determine whether conduct is acceptable or not within the public realm, or in other any place.
**What rights do you posses?**
You have the right to a representative. Representatives will be called upon to volunteer to represent your case. Should no one volunteer to represent you a representative will be called upon based on current availability and random ballot. You may choose to represent yourself, or may choose no representation at all.
To Do:
The nature of the jury is not yet enshrined. The right to call upon a witness is not yet enshrined. The right to come forward as a witness is not yet enshrined. The right to appeal is not yet enshrined. The extent of penalties or prosecution guidelines are not yet enshrined.

I'll respond below with mine, I just wanted to make a version that was coherent rather than broken up by the old version.

**Comment by Autumn-Leah** [comment]
**Statement of Purpose**

This code of conduct aims to detail the nature of improper conduct and explain how the complaints process works.

**Who can file a complaint and how does the complaints procedure account for seriousness?**

All have the right to file a complaint regardless of position or status, however the position or status of a member within the party may be taken into account in the complaints procedure, as those revered will likely receive favourable bias and those disliked or despised for whatever reason will likely receive the reverse, and thus steps must be taken to reasonably ensure a lack of bias for or against within the process and those involved in it in a punitive capacity. 

Additionally those with high levels of power or status within the party, such as party leaders or candidates, will have complaints made against them processed and decided on at the earliest possible moment as these can seriously affect the outlook of the electorate on the party and it's method.

Those with multiple or more serious complaints made against them will be dealt with sooner than others with less or less serious complaints made against them, so that people within the party who are universally unpleasant and unreasonable can be dealt with, hopefully, before any major damage can be done either to the individuals involved or to the party as a whole.

Those who blatantly and clearly abuse the complaints procedure to harass or discriminate against individuals or groups may be subject to a reversal of inquiry, where the complainants intentions and honestly will need to be examined, any action arising from such a reversal would require this decision to be made public irrevocably (within the current bounds of law) along with the reasoning for the punitive measure taken, and then the hosting platform must and will provide the ability for a supermajority of the party to reverse the punitive action, and to (separately) re-enter the complaint back into the complaints process.

**How does the complaint process begin?**

To make a complaint, a resolution process must be attempted for infringements considered minor, whereas major infringement will skip the resolution process and be received by those on a given complaints jury as soon as possible.

Minor infringement will be defined thus: Infringements which are not constant, not illegal, nor arguably equivalent to abuse, bullying, blackmail, or any illegal act.

Ex: Jill sent John a response on the Something New Discourse saying "you suck and I hate you" once, this is not illegal, nor would it constitute serious emotional or psychological abuse, nor is it constant. It may however be against the rules of the party, which could at that time state that contributions to discussions that do nothing but attack the character of the other person in an irrelevant fashion to the existing conversation, or solely involve ad hominems and thus to not present a legitimate critique of their character, as opposed to attacking their argument, are not allowed.

Major infringement will be defined thus: Infringements which are not illegal, and which are constant and/or arguably equivalent to abuse, bullying, blackmail, or any other illegal act without strictly falling under the jurisdiction of courts.

Ex: Bob sent Phil several responses on the Something New Discourse explaining how he was going to systematically ruin Phil's life. Phil reports this to the police or does research on the illegality of the action. Regardless of the outcome of the research or decision of the relevant police forces, this is arguably equivalent to psychological abuse if Phil is constantly worried that something bad will happen due to these threats, despite potentially not convincing those in the judiciary or police forces of the region, the psychological harm can still occur. Thus these criteria are met.

Legality-level infringements will be defined thus: Infringements which are almost certainly illegal in the relevant regions of the dispute, which may or may not be constant and *aren't* arguably equivalent to abuse, bullying, blackmail, or any other illegal act without strictly falling under the jurisdiction of courts (on the basis that the matter does infact fall under the jurisdiction of courts, not on the basis that abuse, bullying, blackmail, or any other illegal act wouldn't be dealt with within this process and band of complaint.

Ex: Someone high ranking in the party committed a serious offence such as voting fraud, campaign corruption via illegal donations, or sexual harassment towards another member of the party, and you are the victim, witness, or confessed accomplice, leader, or accused practitioner, and thus you would like to have the accused removed from their position as soon as possible to avoid damaging publicity to the party, the role that they hold, or the mental, emotional, and physical state of the victim and/or complainant.

Don't worry, there's more to come.

**Comment by Autumn-Leah** [comment]
The resolution process will involve a direct system of messaging between the involved members/groups, in an attempt to resolve the dispute. If those involved wish to escalate the dispute to the complaints jury, they must simply use the request function built into the platform, and include any relevant evidence that would aid in proving the point that the resolution is going nowhere in their view. This request will be visible to the other members/groups involved in the dispute, and they may raise counterpoints and point out misrepresentations or lies, and include their own evidence. After 5 days of a request to escalate being visible, and it not being retracted by the person that issued it, the minor issue will be escalated to the complaints jury.

If the accused was not present for the resolution, then escalation is dependant on evidence that they were present in other party matters and thus were not absent, and that you or others made attempts directly, or made request for others to do so, to show them how to use the dispute resolution system. If you or others made no attempt to explain to them how the resolution system worked, and they were provably not absent, then that will be explained to them so that they are aware of how it functions, and the process will begin again. If attempts or no attempts were made, and it's either unproven that they were not absent or it's certain that they were in fact absent, the resolution process will be delayed for up to 3 months to allow for their return to a fair complaints procedure (during which they maintain all their abilities to function within the party), or, if their leave of absence is a time period known to members of the party not exceeding 6 months but more than 3, they will be allowed the maximum leave of 6 months up until they provably return.

If the accused has not provably returned after 6 months of inactivity, the punitive measure will be taken despite their absence, with the complainant allowed to state their case as per the usual process, and thus they may not be allowed to periodically drop in and contribute without first dealing with the accusations against them; and thus they are forced to be either provably present or absent constantly.

If/once the accused returns, the situation will be explained to them by Dispute Resolution Manager, and they will have the ability to contest the punitive measure if still valid (for example someone banned from the Something New Discourse for 6 weeks, after having 6 months leave, wouldn't not receive a reapplication of the measure and thus would not be required to go through the dispute resolution process unless they wished to challenge the legitimacy of the measure taken in their absence) taken against them after a week of having returned and been provably present (equivalent to signing into a service every other day for a week). At which point the punitive measure, if applicable, will be temporarily lifted subject to their participation in the resolution process beginning within the month from the point at which they returned, and thus those who have accusations against them which have unfinished punitive measures are encouraged to only return if they have at minimum a short quantity of time within that month to deal with a significant part of the accusations. If the accused returns and has to leave again for whatever reason, the punitive measure will be reapplied if still valid, but if not completed the week wait-time to challenge the decision will stay at the number of days completed so far.

If a member of the party repeatedly leaves the resolution process more than 5 times for a span of over a month per leave of absence, and if their total leave of absence from the resolution process totals more than a year, presuming that the punitive measure is still valid or that they wished to challenge it, they must explain their circumstances to the party as a whole within a month of the 5th month-or-over long leave ending and a referendum will be taken on the reasons for absence as to whether that member should retain membership of the party due to potentially abusing the complaints process.

*there's more*

**Comment by Autumn-Leah** [comment]
**The Functions of the Complaints Jury**

If the original infringement was classified as minor infringement, then the first act of the complaints jury will be to seek solutions to the issues raised which led to the escalation of the matter to the complaints jury initially, so that interpersonal and intergroup dispute resolution can continue without their involvement. If it is judged that the effectiveness of dispute resolution on that level is insufficient or impossible, or the initial infringement was not classified as minor, then it will move on to hear both the case of the accused and the case of the complainant. If either have representatives that wish to bring up matters relevant to the complaint, they may do so. The complaints jury will then decide whether the complaint is valid and actionable given the rules of the party and the cases for each representative and individual/group involved, within the dispute resolution process.

**The Role and Powers of a Dispute Resolution Manager and Party Officials**

A dispute resolution manager is a member of the party that volunteers for the position at tri-monthly elections. If the position is contested by another member at the tri-monthly elections of the dispute resolution manager, the members of the party are supposed to vote for the member standing that they believe has the time, energy, enthusiasm, unbiased nature, and competence to assist those who have returned from a leave mid dispute as to how to regain their abilities within the party. If more than 2 members contest the position the election is held through an STV voting system. If there are 2 members then it is held via the FPTP system due to the nature of 2 candidate elections. If there are no members contesting the position (but also if there is) members of the party have the ability to vote for "refreshing the candidates", which allows another 2 weeks for more candidates to stand. In the meantime, the incumbent DRM continues their role. If there is no incumbent DRM, and only one member stands, after a weeks worth of campaigning, and then the vote, if "refreshing the candidates" was voted for by the majority, the only candidate in the running would necessarily have to take the place of the absent or non existent incumbent to allow the party to function as intended. Once this occurs, another election must occur ASAP. If 3 major infringement cases or 1 legality-level infringement is brought against the DRM and succeeds, then a referendum of the party occurs in which the matter of the incumbent continuing in that role is voted on, and if the party is against it, another election is called and that member is banned from holding party office or political office as a candidate for the party. Depending on the nature of the illegal act, the leader of the party has the executive power to call another DRM election provided that the 1 legality-level infringement has actually occurred, but not the power to permanently ban them from office. This same election methodology shall apply to every other party official up to and including the party leader.

**Comment by Autumn-Leah** [comment]
there's more but cba I've gotta sleep or somethin

**Comment by geeksareforlife** [comment]
Something New already has a separate Code of Conduct - https://somethingnew.org.uk/about/code_of_conduct.html

Whilst I agree with improving the code of conduct, this seems to be trying to enforce a code of conduct on parties that choose to use this manifesto (such as Something New), Additionally, what about independents that decide to stand under this manifesto but don't join Something New (or another, yet to be founded, party)?

Personally, I think that the code of conduct here should apply only to how we treat each other when contributing to the manifesto and for that reason I'm afraid I have to vote no.

Vote: ❎

**Comment by Floppy** [comment]
Yes, as @geeksareforlife mentions, this is definitely separate from (though currently in line with) the Something New code of conduct, so anything here should refer to "the project" or something similar that can be defined as any activity on the https://github.com/openpolitics/manifesto repository and associated sites such as https://votebot.openpolitics.org.uk. I wouldn't want it to constrain anything else. Something New has a bunch of legal requirements, officially-appointed officers, and so on that this project doesn't, so the context is different.

I need to read through the various proposals and edits properly to get a clear view on what's being proposed, but at the moment this feels way to heavy for an open source project at this age, though I agree something else may be needed in future.

Can I ask someone to explain simply a situation in which the outcome or operation of this policy would be different from the existing one? As a sort of case study to help people understand?

Voting no *for now*, until we can clarify the scope to just this project, and I can internalise it all a bit more to understand the differences. But, I want to be clear that it's not a vote against the concept of improving the CoC, or against this effort in general.

Vote: ❎

**Pull request closed without merging**
