### PR TITLE
Introduce a "right to health"

### PR DESCRIPTION
**Pull request by Floppy**
Make health a basic right for UK residents.

This right is intended as a fundamental underpinning for the NHS or equivalent system, and to make it part of the governments' core duties to ensure the health of citizens.

### CODE REVIEW

**Comment by Floppy** [comment]
If this flies, I will be looking to codify other basic [maslow-hierarchy](https://en.wikipedia.org/wiki/Maslow's_hierarchy_of_needs) needs into "rights", such as shelter. I figure that the government should have a duty to ensure citizens' most basic needs, at least at the physiological and safety levels.

**Comment by philipjohn** [comment]
Good idea :+1:

**Comment by andrewdwilliams** [comment]
:+1:

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are a [contributor](https://votebot.openpolitics.org.uk/proposals/) to this repository (and not the proposer), you may vote on whether or not it is accepted. 

      ## How to vote
      Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

      |vote|symbol|type this|points|
      |--|--|--|--|
      |Agree|:thumbsup:|`:thumbsup:`|1|
      |Abstain|:hand:|`:hand:`|-1|
      |Block|:thumbsdown:|`:thumbsdown:`|-1000|

      Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 7 days, but will be closed if the proposal is not accepted after 90.

      Votes are counted [automatically here](https://votebot.openpolitics.org.uk/proposals/405), and results are set in the merge status checks below.

      ## Changes

      If the proposer makes a change to the proposal, no votes cast before that change will be counted.

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are a [contributor](https://votebot.openpolitics.org.uk/proposals/) to this repository (and not the proposer), you may vote on whether or not it is accepted. 

      ## How to vote
      Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

      |vote|symbol|type this|points|
      |--|--|--|--|
      |Agree|:thumbsup:|`:thumbsup:`|1|
      |Abstain|:hand:|`:hand:`|-1|
      |Block|:thumbsdown:|`:thumbsdown:`|-1000|

      Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 7 days, but will be closed if the proposal is not accepted after 90.

      Votes are counted [automatically here](https://votebot.openpolitics.org.uk/proposals/405), and results are set in the merge status checks below.

      ## Changes

      If the proposer makes a change to the proposal, no votes cast before that change will be counted.

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are a [contributor](https://votebot.openpolitics.org.uk/proposals/) to this repository (and not the proposer), you may vote on whether or not it is accepted. 

## How to vote
Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

|vote|symbol|type this|points|
|--|--|--|--|
|Agree|:thumbsup:|`:thumbsup:`|1|
|Abstain|:hand:|`:hand:`|-1|
|Block|:thumbsdown:|`:thumbsdown:`|-1000|

Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 7 days, but will be closed if the proposal is not accepted after 90.

Votes are counted [automatically here](https://votebot.openpolitics.org.uk/proposals/405), and results are set in the merge status checks below.

## Changes

If the proposer makes a change to the proposal, no votes cast before that change will be counted.

**Comment by Floppy** [comment]
testing something out

**Pull request merged**
