### PR TITLE
egalitarianism 

### PR DESCRIPTION
**Pull request by LeilaCCG**

### CODE REVIEW

**Comment by iconoclast86** [comment]
:hand:

**Comment by yellowgopher** [comment]
I think I am ok with this - it's difficult to implement; extremely so... by :+1:

**Comment by philipjohn** [comment]
This is great as a principle, which should perhaps go on the front page but I feel like we should have more specific policy aims here.

How do you propose we can make society more equal?

**Comment by Floppy** [comment]
Agree with including this; in fact, it should definitely be a principle on the front page; equality before the law, and promoted as a goal of society in general. I suggest we accept this and then move it to the front page under another PR. :+1:

**Comment by PaulJRobinson** [comment]
:+1:

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are a [contributor](https://votebot.openpolitics.org.uk/proposals/) to this repository (and not the proposer), you may vote on whether or not it is accepted. 

## How to vote
Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

|vote|symbol|type this|points|
|--|--|--|--|
|Agree|:thumbsup:|`:thumbsup:`|1|
|Abstain|:hand:|`:hand:`|-1|
|Block|:thumbsdown:|`:thumbsdown:`|-1000|

Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 7 days, but will be closed if the proposal is not accepted after 90.

Votes are counted [automatically here](https://votebot.openpolitics.org.uk/proposals/345), and results are set in the merge status checks below.

## Changes

If the proposer makes a change to the proposal, no votes cast before that change will be counted.

**Pull request merged**
