### PR TITLE
Update economy.md

### PR DESCRIPTION
**Pull request by pallan51**

### CODE REVIEW

**Comment by Floppy** [comment]
@pallan51 I'm not sure from that link what the Three Pillars actually *are*. Can you elaborate?

**Comment by pallan51** [comment]
> @pallan51 I'm not sure from that link what the Three Pillars actually _are_. Can you elaborate?


National Dividend (ND) - a payment to all citizen-residents, paid for by a tax on the commons

National Income Supplement (NIS) - distributing all income taxes back to income earners, which would allow all income brackets to benefit from each others' success, and amplify their earnings (and underwrite labour costs)

Assisted Savings Program (ASP) - mandatory long-term savings/investment, and distributing all capital gains taxes to ASP accounts, ensuring savers benefit from each others' success, and amplify their savings. 

Returning tax revenues to citizens through these programs is enabled by a shift to a form of Land Value Tax (called a ULT) for general revenues and could be an alternative model for a minimum wage and bankrupt paygo pension systems.

**Comment by BEllis** [comment]
Can we add that to the change?

**Comment by pallan51** [comment]
https://en.wikipedia.org/wiki/List_of_basic_income_models

Three Pillars Model:

National Dividend (ND) - a payment to all citizen-residents, paid for by a
tax on the commons
National Income Supplement (NIS) - distributing all income taxes back to
income earners, which would allow all income brackets to benefit from each
others' success, and amplify their earnings (and underwrite labour costs).

Assisted Savings Program (ASP) - mandatory long-term savings/investment,
and distributing all capital gains taxes to ASP accounts, ensuring savers
benefit from each others' success, and amplify their savings.

Returning tax revenues to citizens through these programs is enabled by a
shift to a form of Land Value Tax (called a ULT) for general revenues. The
Three Pillars would also replace the minimum wage and state-run pensions.

**Pull request closed without merging**
