### PR TITLE
Added a new section that requires the use of open source software and services where available

### LINKED ISSUE #290: Use of proprietary software / services in the public sector
Just wondering what people's opinions were on the use of proprietary software / services in the public sector. Is there any data we can use to see how much we are spending on such software / services?

[There was news from last year about the UK government spending £5.5 billion on expanding the support for Windows XP.](http://www.theguardian.com/technology/2014/apr/07/uk-government-microsoft-windows-xp-public-sector)

I dare not dream just how much money we waste so people can use Microsoft Windows / Office in the public sector. There are open source alternatives that would make us more cost efficient and progressive as a society.

Anyone have some thoughts they would like to share on this? I was going to create a pull request, but not sure where this would go / what specifics people would want to put in the manifesto.

### PR DESCRIPTION
**Pull request by TheRyanHowell**
This is an attempt at adding to the manifesto and resolve #290.

### CODE REVIEW

**Comment by Floppy** [comment]
:+1:

**Comment by PaulJRobinson** [comment]
Defo :+1:

**Comment by philipjohn** [comment]
:+1: Make it so

**Comment by Floppy** [comment]
This should be ready to merge now... yay!

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are a [contributor](https://votebot.openpolitics.org.uk/proposals/) to this repository (and not the proposer), you may vote on whether or not it is accepted. 

## How to vote
Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

|vote|symbol|type this|points|
|--|--|--|--|
|Agree|:thumbsup:|`:thumbsup:`|1|
|Abstain|:hand:|`:hand:`|-1|
|Block|:thumbsdown:|`:thumbsdown:`|-1000|

Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 7 days, but will be closed if the proposal is not accepted after 90.

Votes are counted [automatically here](https://votebot.openpolitics.org.uk/proposals/291), and results are set in the merge status checks below.

## Changes

If the proposer makes a change to the proposal, no votes cast before that change will be counted.

**Pull request merged**
