### PR TITLE
updated the living wage figure (outside London) (added to no tax on tampons, other hygiene products)

### PR DESCRIPTION
**Pull request by LudovicD**
- updated the living wage figure (from outside London, living wage fondation) (also added mention of London figure, hour & year)
- added to no tax on tampons, other basic hygiene products (in the interest of hygiene in the whole society)

### CODE REVIEW

**Comment by Floppy** [comment]
Thanks for updating the figures! There's nothing here I disagree with, but could I ask you to separate it into separate proposals? There's a couple of bits to discuss in each, that I think would be worth doing separately.

**Comment by LudovicD** [comment]
How do i separate it now ? ( with this git hub, proposal, which is new to me )
(1. the figures, 
2 the addition (of other hygiene products) to no tax on tampons
3 the ownership (man-made) )
( i think the definition for me of the commons include all natural resources, so Land, that are not human-made, which is why the logical way of specifying ownership as private is to be explicit with qualifying the something to be bought-sold [->transfered to private ownership] as human-made ).

**Comment by Floppy** [comment]
Best way is to go back to the page you edited and do a new suggestion, one for each separate part. Then we can close this one. Does that make sense?

**Comment by LudovicD** [comment]
yes, a bit the long way, but i will do that.

**Comment by LudovicD** [comment]
done, split, so when the 3 are seen available for vote, we could close this one.

**Comment by Floppy** [comment]
Thanks, this is now split into #560 #559 and #558. Closing this one early :)

**Pull request closed without merging**
