### PR TITLE
Suggestions for the future of the BBC

### PR DESCRIPTION
**Pull request by dartiss**
General taxation for the licence fee, non-government control but tight budgets, keeping close to the original aims of the BBC and providing an emphasis on unique and quality programming.

### CODE REVIEW

**Comment by Floppy** [comment]
In general I'm OK with this, though I think that the diversity of the BBC's output is what lets it fulfil that public service role. Could you elaborate a litle on what the reduction in channels and radio stations would mean? I wouldn't want to lose CBeebies, for instance, even though there are many commercial kids' TV channels.

**Comment by Xyleneb** [comment]
It's an insulting waste of public money to offer subsidies in whole to the media. South Korea does it and "Gangnam Style" is the best that they've produced by it.

I don't think I'd ever vote for anything short of abolition.
Vote: :negative_squared_cross_mark:

**Comment by Autumn-Leah** [comment]
I'd vote for it but I don't agree with the proposed solution.

> By ensuring emphasis is given to the original aims of the BBC (that is, to provide quality programmes of the like that you wouldn't get on commercial channels) and of bringing forward new talent, budgets should be kept to a minimum, through a reduction in TV channels and radio stations and by less emphasis on established but expensive TV personalities.

should be

> Emphasis is given to the original aims of the BBC (that is, to provide quality programmes of the like that you wouldn't get on commercial channels) and of bringing forward new talent, by less emphasis on established but expensive TV personalities.

Vote: ❎

**Comment by philipjohn** [comment]
I like this in general. The third paragraph does kinda contradict with the second paragraph though I think - it can't be independent if we're saying we'll change what it does :) Would you be open to slimming it down to just the first two?

Vote: ✅

**Pull request closed without merging**
