### PR TITLE
Local hustings for general elections

### PR DESCRIPTION
**Pull request by philipjohn**

### CODE REVIEW

**Comment by Floppy** [comment]
:+1: definitely. There should be some official hustings hosted by the organisation running the vote.

**Comment by PaulJRobinson** [comment]
:+1:

**Comment by tmtmtmtm** [comment]
Is this a responsibility to ensure that at least one public husting takes place? I'm not sure the current wording says that (You can enable something without it actually happening.)

**Comment by Floppy** [comment]
Perhaps it should be a "duty to ensure that at least one independent public hustings takes place and is promoted to all constituents". That way they have the option to work with other organisations if that's more effective.

**Comment by Floppy** [comment]
I've followed this up with #292 which refines the wording slightly.

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are a [contributor](https://votebot.openpolitics.org.uk/proposals/) to this repository (and not the proposer), you may vote on whether or not it is accepted. 

## How to vote
Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

|vote|symbol|type this|points|
|--|--|--|--|
|Agree|:thumbsup:|`:thumbsup:`|1|
|Abstain|:hand:|`:hand:`|-1|
|Block|:thumbsdown:|`:thumbsdown:`|-1000|

Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 7 days, but will be closed if the proposal is not accepted after 90.

Votes are counted [automatically here](https://votebot.openpolitics.org.uk/proposals/272), and results are set in the merge status checks below.

## Changes

If the proposer makes a change to the proposal, no votes cast before that change will be counted.

**Pull request merged**
