### PR TITLE
Creating a British Overseas Territories section

### PR DESCRIPTION
**Pull request by andrewdwilliams**
Created a British Overseas Territories section, putting the stuff on BIOT in the section. I also added a little bit on Montserrat and the Sovereign Base Areas.

### CODE REVIEW

**Comment by PaulJRobinson** [comment]
:+1:

**Comment by Floppy** [comment]
:+1:

The diff is a bit wrong here, unfortunately not everything is new to this PR. The relevant parts are the sections on BIOT, Montserrat, and Akrotiri.

**Comment by h2g2bob** [comment]
:+1: The Chagos Archipelago is a long-running scandal; the other territories I agree need help too.

**Comment by Floppy** [comment]
This should be OK to merge now...

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are a [contributor](https://votebot.openpolitics.org.uk/proposals/) to this repository (and not the proposer), you may vote on whether or not it is accepted. 

## How to vote
Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

|vote|symbol|type this|points|
|--|--|--|--|
|Agree|:thumbsup:|`:thumbsup:`|1|
|Abstain|:hand:|`:hand:`|-1|
|Block|:thumbsdown:|`:thumbsdown:`|-1000|

Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 7 days, but will be closed if the proposal is not accepted after 90.

Votes are counted [automatically here](https://votebot.openpolitics.org.uk/proposals/368), and results are set in the merge status checks below.

## Changes

If the proposer makes a change to the proposal, no votes cast before that change will be counted.

**Pull request merged**
