### PR TITLE
Reform the HoL Reform policy

### PR DESCRIPTION
**Pull request by philipjohn**
Adds a commitment to imcremental reform of the House of Lords, given the citizen-panel based reform is quite a big ask and won't happen immediately. End goal copied straight from the previous page.

Also restructures to give HoL reform it's own page for neatness.

### CODE REVIEW

**Comment by tmtmtmtm** [comment]
> No ministerial should be held by an unelected politician

Aside from the missing word, this is slightly ambiguous. I'm assuming this should simply say that Ministers can only be appointed from sitting Members of the House of Commons?

I'm curious, though, as to what this proposal would also mean for the Leader of the House of Lords.

**Comment by philipjohn** [comment]
Thanks for the feedback - I've clarified that sentence about ministerial appointments.

> I'm curious, though, as to what this proposal would also mean for the Leader of the House of Lords.

I reckon we're okay on that one, as the policy only stops *new* appointments to the House of Lords (i.e. new Lords). Happy to make that clearer if you think it needs to be?

**Comment by tmtmtmtm** [comment]
I meant that the Leader of the House of Lords is currently a ministerial position, as the point of the role is to represent the government's interest in the House. Abolishing that connection seems like it could be problematic.

**Comment by PaulJRobinson** [comment]
:+1:

**Comment by Floppy** [comment]
@tmtmtmtm I think that implementation of the plan would work out a solution to that problem, so I'm not opposed on those grounds. :+1:

I am a little concerned that this will give undue prominence to Lords reform in the site structure, but that's not a policy issue, so I'll upvote this, and merge when I have a minute to work on the structure after merge to make sure it still works.

**Comment by philipjohn** [comment]
@tmtmtmtm Any chance of a vote from you on this one?

**Comment by Floppy** [comment]
I'm in the process of merging it, but I'm going to split the democracy page in two a slightly different way, if thats OK. I'll take care of it during the merge though.

**Comment by Floppy** [comment]
OK, all done. We now have an "elections" page and a "democracy" page, which balances out the massive democracy page a bit.

**Comment by philipjohn** [comment]
Yeah that's cool

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are a [contributor](https://votebot.openpolitics.org.uk/proposals/) to this repository (and not the proposer), you may vote on whether or not it is accepted. 

## How to vote
Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

|vote|symbol|type this|points|
|--|--|--|--|
|Agree|:thumbsup:|`:thumbsup:`|1|
|Abstain|:hand:|`:hand:`|-1|
|Block|:thumbsdown:|`:thumbsdown:`|-1000|

Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 7 days, but will be closed if the proposal is not accepted after 90.

Votes are counted [automatically here](https://votebot.openpolitics.org.uk/proposals/285), and results are set in the merge status checks below.

## Changes

If the proposer makes a change to the proposal, no votes cast before that change will be counted.

**Pull request merged**
