### PR TITLE
student president should be non-voting member on governing body

### PR DESCRIPTION
**Pull request by yellowgopher**
School Governance.  Advise student president should be a co-opted (non-voting) member on governing body to avoid any legal issues surrounding liability etc.

### CODE REVIEW

**Comment by philipjohn** [comment]
Could you expand on the ramifications for the student president being a vote-wielding member? I'm genuinely unsure and as the original author of this bit of policy I'm keen to see it stay in with the intended effect (that of introducing students to genuine, effective democracy).

I'm worried that a non-voting role just wouldn't have the right clout, but it sounds like there might be big issues with that?

**Comment by PaulJRobinson** [comment]
Happy with this. But a co-opted member isn't necessarily a non-voting member. If that's your intention with this proposal I think it should be explicitly stated in the text.

**Comment by yellowgopher** [comment]
Generally co-opted members do not have formal voting rights but, you are correct, it would be up to the articles of the body in question whether this would be the case.  It can be stipulated if you think this needs to be clarified.

**Comment by philipjohn** [comment]
If the intention *is* to make the student president a non-voting member I think that would take away the reason for this proposal in the first place - of introducing students to a tangible democratic process that gives them a voice.

Without having a vote, there's no point in the student president at all, nor the democratic system around it.

**Comment by yellowgopher** [comment]
My concern would be potential issues surrounding liability of the student president being a full member of the governing body and able to have a final say in what happens.  Also there are issues that are dealt with by a governing body that may or may not be age appropriate for the student president - disciplinary hearings, abuse, headteachers' performance and pay etc etc.  If we decide to remove these areas from the student president's remit we then have "classes" of governor which goes against a key definition that each full governor is equal.  So, although I appreciate the reasons behind the proposal for the student president to be a full vote wielding governor, I think it is far better (and safer) to have them as a co-opted member that should be consulted on areas that are age appropriate (we may have to specify they must be consulted on a specific list of areas).  They will be introduced to the democratic process, governing bodies may be willing to give them a vote on limited areas (but this shouldn't be the law); it covers the main part of what is wanted but continues to protect the student president who would be a minor.

**Comment by yellowgopher** [comment]
Ok, I think I have somehow managed to re-request this!  I have added a section about requiring the GB to consult a student president on certain matters - does this help?  Let me know if I can close this off...!?

**Comment by philipjohn** [comment]
> able to have a final say in what happens
Why is that a bad thing?

> Also there are issues that are dealt with by a governing body that may or may not be age appropriate for the student president - disciplinary hearings, abuse, headteachers' performance and pay etc etc.
All of which is implementation-specific, and would be dealt with by the relevant department when consulting before implementing such a system, as such, isn't something we should get bogged down in when creating this vision.

> should be consulted
...and inevitably ignored, introducing the students to a democratic system that ignores them, setting them up for a life of political apathy, not engagement.

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are a [contributor](https://votebot.openpolitics.org.uk/proposals/) to this repository (and not the proposer), you may vote on whether or not it is accepted. 

## How to vote
Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

|vote|symbol|type this|points|
|--|--|--|--|
|Agree|:thumbsup:|`:thumbsup:`|1|
|Abstain|:hand:|`:hand:`|-1|
|Block|:thumbsdown:|`:thumbsdown:`|-1000|

Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 7 days, but will be closed if the proposal is not accepted after 90.

Votes are counted [automatically here](https://votebot.openpolitics.org.uk/proposals/260), and results are set in the merge status checks below.

## Changes

If the proposer makes a change to the proposal, no votes cast before that change will be counted.

**Pull request closed without merging**
