### PR TITLE
Decentralisation of taxation

### PR DESCRIPTION
**Pull request by areteh**
At present on ~5% of taxation is in the hands of local authorities. This creates a situation where central government tax rates and spending may benefit one local community but benefit another. In contrast is Switzerland, where the population of 4 million are spread across 26 cantons - each with the power to set rates and spend according to local needs (and only a small fraction being collected as a "federal tax").  This proposal supports a move in that direction for the benefit of both thriving and deprived parts of the UK.

### CODE REVIEW

**Comment by Floppy** [comment]
Yep, this is in line with a similar statement in https://openpolitics.org.uk/manifesto/democracy.html#devolution on federal and local taxation.

Vote: ✅

**Comment by Autumn-Leah** [comment]
Vote: ✅

**Comment by RobertWootton** [comment]
I think that perhaps to qualify for a personal tax allowance, a person must be a member of their local Residents Association that is registered with the local authority. If there was not an already existing R.A. a person must start an association. A person who lived "Offshore" would not be eligible for any tax allowances.

**Comment by areteh** [comment]
Please note that this proposal is not about an allowance but rather who sets the actual tax rate in the first place. It is about decentralising those tax rate decisions

**Comment by RobertWootton** [comment]
My personal view is that the existing taxes paid by an electorate should be paid directly to the local parish/town council and a percentage of that amount paid to the district council and a percentage of their receipts paid to the County Council and a percentage of their receipts paid to Central Government of the UK. Who decides on the percentages is open to debate.

**Pull request merged**
