### PR TITLE
Re-evaluation of policy on the PKK

### PR DESCRIPTION
**Pull request by Autumn-Leah**
Whilst the acts committed by the PKK are not things I would attempt to justify, the systematic erasure of Kurdish culture and lifestyles is abhorrent, and as such I believe that the Turkish government must do a lot more to both compensate for previous actions and to advance the rights of Kurdish people before it can expect any form of peaceful resolution.

### CODE REVIEW

**Comment by philipjohn** [comment]
This sentence has a couple of grammar quirks, probably just cause they were part of the original;

> With a view to peace in the region, the PKK should it commit itself to disarming in Turkey and re-engaging in the peace process

**Comment by Floppy** [comment]
Also I think there is a footnote missing, 'mp-arrested-speaking-kurdish'? But yes, good expansion.

Vote: ✅

**Comment by Autumn-Leah** [comment]
@philipjohn Do you have any intention to vote on this or?

**Comment by philipjohn** [comment]
Vote: ✅

**Pull request merged**
