### PR TITLE
Removed Egalitarianism section

### PR DESCRIPTION
**Pull request by Autumn-Leah**
I removed it as part of a process I'm going through atm. I'm going to attempt to make a new page for gender related issues, which is especially topical as diversity in the party is something I know @Floppy has been interested in, in recent discussions. Either way, the section didn't state much of anything, so if it does remain, it'll have to be redone for fear of it being seen as what it is; largely pointless manifesto fodder stating the award winning opinion that we support gender identity and sex (biological sex, not the activity) equality.

### CODE REVIEW

**Comment by Autumn-Leah** [comment]
See: https://votebot.openpolitics.org.uk/proposals/485 for the other change that pairs with this one

**Comment by Floppy** [comment]
Yes, that line doesn't say much at all. I'll withhold a yes vote for now, until we get #485 in, but as long as that goes in, I'll vote yes here to remove this. Don't want to remove it until we do though :)

**Comment by Autumn-Leah** [comment]
Yeah, that's sensible.

**Comment by philipjohn** [comment]
#485 passed and merged

Vote: ✅

**Comment by Floppy** [comment]
Vote: ✅

**Pull request merged**
