### PR TITLE
end SACREs, modified percentage of non-religious (50-62) and percentage of faith schools (30%)

### PR DESCRIPTION
**Pull request by andrewedmondson**

### CODE REVIEW

**Comment by philipjohn** [comment]
Agree with most of this but where is the 30% figure from?

**Comment by andrewedmondson** [comment]
From the BHA. It's approximate. It might be up to 35% but certainly not 
50%. The religious character of free schools is not recorded, as far as 
I am aware.

**Comment by philipjohn** [comment]
Okay, but is that more valid than the government figures already linked to, and still referenced but the footnote?

**Comment by andrewedmondson** [comment]
No. The British Social Attitudes Survey is the most in depth. However, 
research has shown that people often state religious affiliation on 
spurious grounds, e.g. my parents were religious, I got married in a 
church, I was baptised.

Of course, the phrasing of survey questions is crucial and a very 
difficult thing to get right.

I think it is safe to say that at least 50% of the population is 
non-religious.

Delete the 62% reference if you think it is misleading. But it is 
referenced. Perhaps somone can find a recent independent poll that shows 
less than 50% are religious? In that case, add this too.

**Comment by philipjohn** [comment]
Okay, forgive me if I'm getting confused, but this is what I see in the proposal...

> but over half of all state funded schools have a religious character[^2]

gets changed to

> and yet around 30% of state funded schools have a religious character[^2]

So the figure goes from >50% to 30%, but references the same source.

**Comment by andrewedmondson** [comment]
Well if you add up the percentages in the source, it comes to around 33.8%.

On 19/04/2015 21:36, philipjohn wrote:
>
> Okay, forgive me if I'm getting confused, but this is what I see in 
> the proposal...
>
>     but over half of all state funded schools have a religious
>     character[^2]
>
> gets changed to
>
>     and yet around 30% of state funded schools have a religious
>     character[^2]
>
> So the figure goes from >50% to 30%, but references the same source.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/openpolitics/manifesto/pull/325#issuecomment-94311007>.
>

-- 
Andrew Edmondson

079 3450 8671
West Sussex Humanists <http://www.westsussexhumanists.org.uk>
BHA logo <http://www.humanism.org.uk/>

**Comment by philipjohn** [comment]
That percentage excludes academies thought, which are still state funded, which makes the statement inaccurate.

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are a [contributor](https://votebot.openpolitics.org.uk/proposals/) to this repository (and not the proposer), you may vote on whether or not it is accepted. 

## How to vote
Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

|vote|symbol|type this|points|
|--|--|--|--|
|Agree|:thumbsup:|`:thumbsup:`|1|
|Abstain|:hand:|`:hand:`|-1|
|Block|:thumbsdown:|`:thumbsdown:`|-1000|

Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 7 days, but will be closed if the proposal is not accepted after 90.

Votes are counted [automatically here](https://votebot.openpolitics.org.uk/proposals/325), and results are set in the merge status checks below.

## Changes

If the proposer makes a change to the proposal, no votes cast before that change will be counted.

**Pull request closed without merging**
