### PR TITLE
Parishes and CCs as the seat of LA policy making

### PR DESCRIPTION
**Pull request by digitalWestie**
I'm a fan of confederalism (http://www.inclusivedemocracy.org/dn/vol1/bookchin_confederalism.htm), perhaps this is how it could start off in the UK ?

### CODE REVIEW

**Comment by philipjohn** [comment]
Could you expand a bit on how this would work in practice? I'm not entirely understanding it at the moment.

**Comment by Floppy** [comment]
Same here, I don't quite understand what would actually happen (though I like the idea of pushing policymaking out to the edges, obviously)

**Comment by Floppy** [comment]
:hand: for now.

Note this is also over the time limit, so unless you do want to push it forward @digitalWestie, it will probably be closed soonish.

**Comment by digitalWestie** [comment]
Yep still chewing this one over, since proposing I've found more sources from which to develop this further so will put something down eventually. Again this might become multiple proposals so will close for now. NB If you want to know what I'm on about, I'm aiming at a proposal that comprises some of the ideas / practices such as libertarian municipalism, citizen juries, citizen assemblies, and participatory budgeting.

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are a [contributor](https://votebot.openpolitics.org.uk/proposals/) to this repository (and not the proposer), you may vote on whether or not it is accepted. 

## How to vote
Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

|vote|symbol|type this|points|
|--|--|--|--|
|Agree|:thumbsup:|`:thumbsup:`|1|
|Abstain|:hand:|`:hand:`|-1|
|Block|:thumbsdown:|`:thumbsdown:`|-1000|

Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 7 days, but will be closed if the proposal is not accepted after 90.

Votes are counted [automatically here](https://votebot.openpolitics.org.uk/proposals/236), and results are set in the merge status checks below.

## Changes

If the proposer makes a change to the proposal, no votes cast before that change will be counted.

**Pull request closed without merging**
