### PR TITLE
Support the Public Service Users Bill

### PR DESCRIPTION
**Pull request by philipjohn**
Background: http://weownit.org.uk/public-service-users-bill

### CODE REVIEW

**Comment by philipjohn** [comment]
"We Own It" are putting out a call to all parties to support this. Given that [Something New](http://somethingnew.org.uk) have adopted this manifesto, it's a good opportunity to raise the profile of the manifesto so getting this in would be good.

@PaulJRobinson @frankieroberto @digitalWestie @timcowlishaw @mjnaber @stringfellow @mikera Any of you folks able to help out with a vote?

**Comment by clarkdavison** [comment]
Signed and tweeted

**Comment by Floppy** [comment]
This one is out of time, but as the rule only came in recently and I think the direction of travel is right, I will leave it open for a little while to gather more votes. @PaulJRobinson, what do you think?

**Comment by philipjohn** [comment]
This seems like such a no-brainer it'd be a shame if it failed. No pressure @PaulJRobinson ;)

**Comment by philipjohn** [comment]
@clarkdavison @PaulJRobinson Any chance of a vote on this?

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are a [contributor](https://votebot.openpolitics.org.uk/proposals/) to this repository (and not the proposer), you may vote on whether or not it is accepted. 

## How to vote
Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

|vote|symbol|type this|points|
|--|--|--|--|
|Agree|:thumbsup:|`:thumbsup:`|1|
|Abstain|:hand:|`:hand:`|-1|
|Block|:thumbsdown:|`:thumbsdown:`|-1000|

Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 7 days, but will be closed if the proposal is not accepted after 90.

Votes are counted [automatically here](https://votebot.openpolitics.org.uk/proposals/249), and results are set in the merge status checks below.

## Changes

If the proposer makes a change to the proposal, no votes cast before that change will be counted.

**Pull request closed without merging**
