### PR TITLE
Multiple Changes

### PR DESCRIPTION
**Pull request by Polygon48k**
Fiscal studies are already part of the curriculum. encourage learners to learn when they are ready, and encourage those that have completed studies to not take advantage of the state. removed free uniform. Should probably of split this.

### CODE REVIEW

**Comment by Autumn-Leah** [comment]
Definite should have split this. Removing funding for uni is a terrible idea, and if it's not as bad as it sounds then it definitely needs clarification before I can vote it through. Free uniform is a policy proposal I've already created, and thus it'd be redundant to have another one, if you want it changed, go vote my change through since we seem to agree. Fiscal studies isn't actually part of the core curriculum yet, and if you can point me to the bit of legislation on gov.uk that says that I'll be delighted because it means that the government did something vaguely correct and justified for once.

Vote: ❎

**Comment by Polygon48k** [comment]
Yeah, its a bit all over, I support free Higher Education(Uni), but not pressure into it. And a cap on the Further Education system (College). i  was looking at https://www.pfeg.org/about-us/about-pfeg but after some investigating, although being delivered in many schools now, it is not on the National Curriculum. Perhaps we could agree on commiting to the PFEG's goals.

**Comment by Floppy** [comment]
There's some stuff here that would go straight in, and some which will need more discussion. So that we can discuss each in turn, can you please resubmit them as separate edits @Polygon48k?

**Comment by philipjohn** [comment]
Removing funding for FE and the free school uniform are both a big no from me in any case, I'm afraid.

Vote: ❎

**Comment by LudovicD** [comment]
yes to both,
all general education should be from general taxation. (Further education should be with grant on the understanding of exercising in the UK for a full decade, post-grad, is actually mostly doctors, research/engineering, lawers anyway, which all bring value to the country) (& research/development UK budgets need to be multplied anyway)
for uniform, they should allow small variation(s) per county council/city council.

**Pull request closed without merging**
