### PR TITLE
Overseas Territories section update

### PR DESCRIPTION
**Pull request by andrewdwilliams**
Updated some stuff, added a little more, just general expansion.

### CODE REVIEW

**Comment by philipjohn** [comment]
:+1:

**Comment by OliverJackson1** [comment]
@andrewdwilliams are we comfortable enough with the actions of President Erdoğan to agree to simple de-listing of the PKK? Would we potentially be better calling for a Kurdish state as a form of peace agreements out of concessions from Iraq and Syria. Not sure that we should really mention the PKK at all just forward devloution and non-intervention. Something like "We wish to pursue an evenhanded foreign policy and in light of violence from both the Turkish state and the Kurdish Rebels we condemn both sides. We believe in the establishment of a Kurdish State in the North East and North West Regions of Syria and Iraq, respectively, where there are effective military campaigns against Daesh (ISIS). We believe this will establish peace and we aim to see this new state provisioned with peacekeepers until such a time as peace is secured."

The fear is that otherwise we validate the violence of one side and not the other. Additionally, this conflict will run for decades without an evenhanded approach that recognizes the Kurdish desire for a free state.

**Comment by Floppy** [comment]
@OliverJackson1 the only thing that changed in the PKK section is the footnote numbering, not the policy, so if we want to discuss it, let's do it under a separate change before we get offtopic here :)

**Comment by andrewdwilliams** [comment]
@OliverJackson1 That wasn't my original addition to the manifesto, as @Floppy pointed out the only bit I altered in the PKK section was the footnote numbering. But if you want to change the PKK section, feel free to start a new pull request and I'll give it a look over.

**Comment by andrewdwilliams** [comment]
@Floppy @OliverJackson1 Could you look at this and give it a thumbs up or not, so we can get this passed?

**Comment by Floppy** [comment]
👍

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are a [contributor](https://votebot.openpolitics.org.uk/proposals/) to this repository (and not the proposer), you may vote on whether or not it is accepted. 

## How to vote
Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

|vote|symbol|type this|points|
|--|--|--|--|
|Agree|:thumbsup:|`:thumbsup:`|1|
|Abstain|:hand:|`:hand:`|-1|
|Block|:thumbsdown:|`:thumbsdown:`|-1000|

Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 7 days, but will be closed if the proposal is not accepted after 90.

Votes are counted [automatically here](https://votebot.openpolitics.org.uk/proposals/387), and results are set in the merge status checks below.

## Changes

If the proposer makes a change to the proposal, no votes cast before that change will be counted.

**Pull request merged**
