### PR TITLE
Stronger Reform of Copyright Law

### PR DESCRIPTION
**Pull request by Xyleneb**
**Admin note: The "media retraction" section is not included in this proposal - it's a bug in the system.**

Unless the life expectancy of "creative-types" drops to <55 years, this system represents better value for creative redistribution. It allows authors who either aren't interested in copyright renewal or who live a very long time to witness their works' adoption into the public domain. It also brings copyright law back into the more general good faith that existed prior 1950's.

### CODE REVIEW

**Comment by Xyleneb** [comment]
Reminder: change line 15 to: "Lobby other states for a worldwide further reduction to "life + 25 years" or to "40 + 40 years".

**Comment by philipjohn** [comment]
Thanks for the proposal!

My reading of the proposal is that is has an inconsistency. Maybe I'm wrong and you can explain it to me though :) The proposal changes the term to "two 40 year terms" but then says we should lobby other countries for "life + 25 years". Why are we lobbying other countries for a different term to what we have?

It may be that I just don't understand the context, but I don't know what this bit is for, or what it does:

> Make the necessary preparations for a general case within the World Trade Organization's Dispute Settlement Body, regarding UK conformity with the Berne Convention

Could you elaborate on that a little bit please?

**Comment by Floppy** [comment]
Definitely agree on the media retractions section. On the first, I echo @philipjohn's points, but also note that two 40-year terms would actually allow *longer* copyright protection than currently. What would be the requirement for renewal? How hard would it be, given large media corporations with lots of lawyers? Are we just protecting Disney even longer?

**Comment by Xyleneb** [comment]
>Why are we lobbying other countries for a different term to what we have?

>Could you elaborate on that [WTO's Berne Convention] a little bit please?
https://en.wikipedia.org/wiki/Berne_Convention#Copyright_term is the problem, and perhaps reason for an international lobbying 'duality'. Regardless of which system you pick ("life+25" or "40+40") another country may drag yours before the WTO's court with a dispute saying that you are no longer honouring the treaties you've agreed to. If that happens and you lose the dispute, then they can order your country to pay fines or to exit the WTO.

If a dispute does happen, then you would have to make the case that "life+25" or "40+40" is defensible and respectful of the law as set out in the treaty or somehow repeal backwards to an older version of the treaty (if that's possible). Failing that, you're either to give up on your own sovereign laws in compliance or exit the WTO.

>On the first, I echo @philipjohn's points, but also note that two 40-year terms would actually allow longer copyright protection than currently.
If your "creative" makes some art and dies that same year, then yes it's potentially 30 years longer than "life+50" and 55 years longer than "life+25" (if the renewal is claimed, which will likely happen if it's still deemed commercially viable after 40 years). 

But if your author lives 30 years after publishing, then life+50 leaves you worse off. If your author lives 55 years after publishing, then life+25 leaves you worse off (again, this is if you do count the renewal). 

People tend to produce works relatively early in life, and people are living for an extraordinarily long time (though there are exceptions; Cobain, Tolkein etc). I think maths-wise the proposal is alright.

>What would be the requirement for renewal?
The history of copyright law is based upon having two terms, originally (in the US) 14+14 years. If you were granted the copyright initially, then you'll generally be granted it a second time as long as you renew and pay the fees.

>How hard would it be, given large media corporations with lots of lawyers? Are we just protecting Disney even longer?
Disney made Mickey Mouse aged 27 and died aged 65. "Life+50" would be 8 years longer than 40+40. "Life+25" would be 17 years shorter than "40+40".

"Dumbo" is perhaps a more extreme example. It came out when Disney was 40. "40+40" is in this case 5 years longer than "Life+50". "Life+25" is 30 years less sole monetization of "Dumbo" than "40+40" provides. Disney's ripe old age of 65 wasn't much when compared to today though.

You must bear in mind as well the academic journals who would have to pay the renewal fees to Britain's coffers just to stop people from getting hold of a cheap copy of their 2nd editions, when they're busy trying to screw people for their 8th consecutive edition. Money that you could spend on perhaps greater accessibility?

**Comment by Xyleneb** [comment]
>Why are we lobbying other countries for a different term to what we have?

>Could you elaborate on that [WTO's Berne Convention] a little bit please?

    https://en.wikipedia.org/wiki/Berne_Convention#Copyright_term is the problem, and perhaps reason for an international lobbying 'duality'. Regardless of which system you pick ("life+25" or "40+40") another country may drag yours before the WTO's court with a dispute saying that you are no longer honouring the treaties you've agreed to. If that happens and you lose the dispute, then they can order your country to pay fines or to exit the WTO.

If a dispute does happen, then you would have to make the case that "life+25" or "40+40" is defensible and respectful of the law as set out in the treaty or somehow repeal backwards to an older version of the treaty (if that's possible). Failing that, you're either to give up on your own sovereign laws in compliance or exit the WTO.

>On the first, I echo @philipjohn's points, but also note that two 40-year terms would actually allow longer copyright protection than currently.

    If your "creative" makes some art and dies that same year, then yes it's potentially 30 years longer than "life+50" and 55 years longer than "life+25" (if the renewal is claimed, which will likely happen if it's still deemed commercially viable after 40 years).

But if your author lives 30 years after publishing, then life+50 leaves you worse off. If your author lives 55 years after publishing, then life+25 leaves you worse off (again, this is if you do count the renewal).

People tend to produce works relatively early in life, and people are living for an extraordinarily long time (though there are exceptions; Cobain, Tolkein etc). I think maths-wise the proposal is alright.

>What would be the requirement for renewal?

    The history of copyright law is based upon having two terms, originally (in the US) 14+14 years. If you were granted the copyright initially, then you'll generally be granted it a second time as long as you renew and pay the fees.

>How hard would it be, given large media corporations with lots of lawyers? Are we just protecting Disney even longer?

    Disney made Mickey Mouse aged 27 and died aged 65. "Life+50" would be 8 years longer than 40+40. "Life+25" would be 17 years shorter than "40+40".

"Dumbo" is perhaps a more extreme example. It came out when Disney was 40. "40+40" is in this case 5 years longer than "Life+50". "Life+25" is 30 years less sole monetization of "Dumbo" than "40+40" provides. Disney's ripe old age of 65 wasn't much when compared to today though.

You must bear in mind as well the academic journals who would have to pay the renewal fees to Britain's coffers just to stop people from getting hold of a cheap copy of their 2nd editions, when they're busy trying to screw people for their 8th consecutive edition. Money that you could spend on perhaps greater accessibility?

**Comment by Xyleneb** [comment]
>Why are we lobbying other countries for a different term to what we have?

>Could you elaborate on that [WTO's Berne Convention] a little bit please?

https://en.wikipedia.org/wiki/Berne_Convention#Copyright_term is the problem, and perhaps reason for an international lobbying 'duality'. Regardless of which system you pick ("life+25" or "40+40") another country may drag yours before the WTO's court with a dispute saying that you are no longer honouring the treaties you've agreed to. If that happens and you lose the dispute, then they can order your country to pay fines or to exit the WTO.

If a dispute does happen, then you would have to make the case that "life+25" or "40+40" is defensible and respectful of the law as set out in the treaty or somehow repeal backwards to an older version of the treaty (if that's possible). Failing that, you're either to give up on your own sovereign laws in compliance or exit the WTO.

>On the first, I echo @philipjohn's points, but also note that two 40-year terms would actually allow longer copyright protection than currently.

If your "creative" makes some art and dies that same year, then yes it's potentially 30 years longer than "life+50" and 55 years longer than "life+25" (if the renewal is claimed, which will likely happen if it's still deemed commercially viable after 40 years).

But if your author lives 30 years after publishing, then life+50 leaves you worse off. If your author lives 55 years after publishing, then life+25 leaves you worse off (again, this is if you do count the renewal).

People tend to produce works relatively early in life, and people are living for an extraordinarily long time (though there are exceptions; Cobain, Tolkein etc). I think maths-wise the proposal is alright.

>What would be the requirement for renewal?

The history of copyright law is based upon having two terms, originally (in the US) 14+14 years. If you were granted the copyright initially, then you'll generally be granted it a second time as long as you renew and pay the fees.

>How hard would it be, given large media corporations with lots of lawyers? Are we just protecting Disney even longer?

Disney made Mickey Mouse aged 27 and died aged 65. "Life+50" would be 8 years longer than 40+40. "Life+25" would be 17 years shorter than "40+40".

"Dumbo" is perhaps a more extreme example. It came out when Disney was 40. "40+40" is in this case 5 years longer than "Life+50". "Life+25" is 30 years less sole monetization of "Dumbo" than "40+40" provides. Disney's ripe old age of 65 wasn't much when compared to today though.

You must bear in mind as well the academic journals who would have to pay the renewal fees to Britain's coffers just to stop people from getting hold of a cheap copy of their 2nd editions, when they're busy trying to screw people for their 8th consecutive edition. Money that you could spend on perhaps greater accessibility?

**Comment by philipjohn** [comment]
I have some clarifying questions about that last comment...

> If that happens and you lose the dispute

In this sentence does "you" mean "the state"?

> then life+25 leaves you worse off

Who is the "you" in this sentence? Earlier in this paragraph there is the phrase "your creative" so I'm not sure who the "you" is if not the creative and how the length of copyright makes "you" worse off (presumably financially).

> If you were granted the copyright initially

Am I right to assume that "you" in this sentence means the copyright owner?

Thanks!

**Comment by Xyleneb** [comment]
>"If that happens and you lose the dispute"

You being the British state, or government of the day.

>"your creative"

Any creative-type person ("your" being someone who's applied for copyright recognition in your country)

>"then life+25 leaves you worse off"

People of your country, subjects, citizens, etc.

>Who is the "you" in this sentence? Earlier in this paragraph there is the phrase "your creative" so I'm not sure who the "you" is if not the creative and how the length of copyright makes "you" worse off (presumably financially).

Your citizens are worse off, in terms of reproduction and derivative rights, so they can't reproduce the work without permission.

>Am I right to assume that "you" in this sentence means the copyright owner?

Yes. Sorry, this is why I'm not a writer...

In this policy I tried not only to explain "this is what we will do" but the responsibility involved and the means to that end (for example if the Berne convention becomes a problem). I'm not sure if that was the right approach or not.

In the end it comes down to whether you think Life+25 or 40+40 is "better". I like 40+40 because everything that's not considered commercially viable after 40 years; their copyrights could end early and allow the redistribution and derivative rights to transfer to public domain. Life+25 seems less radical in that regard.

**Comment by Xyleneb** [comment]
Oh and I hold the view that "more radical" is a plus in this case because I get the impression that most of the public dislikes copyright law and doesn't take it seriously, and that they may therefore view "life+25" as "not going far enough". I could be wrong though. In cases of late creativity and shortened life expectancy, life+25 could in some cases leave the public (who I assume want redistribution rights) markedly better off.

**Comment by Floppy** [comment]
Ah, right, I misread the edit as "life + 40 + 40". As the copyright term would now be based on the work and when it should pass into the public domain, not the vagaries of lifetime, I'm in. :+1:

**Comment by Floppy** [comment]
I think there are some minor edits that could be made to make that clearer, but we can do that as a separate PR after. For instance, I'd say explicitly adding "two 40-year terms from the date of production of the work" would avoid the mistake I made in reading.

**Comment by Floppy** [comment]
I'd also suggest we add something to the Berne Convention bit on lobbying to get that changed to match (such as we could, as a single country).

**Comment by philipjohn** [comment]
> Sorry, this is why I'm not a writer...

No problem! Just want to make sure we're understanding your intention :)

Okay, let's get this in and tweak it a bit later :+1:

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are a [contributor](https://votebot.openpolitics.org.uk/proposals/) to this repository (and not the proposer), you may vote on whether or not it is accepted. 

## How to vote
Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

|vote|symbol|type this|points|
|--|--|--|--|
|Agree|:thumbsup:|`:thumbsup:`|1|
|Abstain|:hand:|`:hand:`|-1|
|Block|:thumbsdown:|`:thumbsdown:`|-1000|

Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 7 days, but will be closed if the proposal is not accepted after 90.

Votes are counted [automatically here](https://votebot.openpolitics.org.uk/proposals/423), and results are set in the merge status checks below.

## Changes

If the proposer makes a change to the proposal, no votes cast before that change will be counted.

**Pull request merged**
