### PR TITLE
Add equality statement to main page

### PR DESCRIPTION
**Pull request by Floppy**
Just realised it wasn't there!

### CODE REVIEW

**Comment by Floppy** [comment]
Test failures are transient network issues, no problem in this PR itself. Will fix those separately.

**Comment by philipjohn** [comment]
Awesome :+1: Could we add "...or any other [thing]" replacing "thing" with something that makes sense that I can't think of right know 'cause I'm knackered :)

**Comment by Floppy** [comment]
I was trying to do exactly that when I wrote it, but couldn't come up with the wording. The dictionary uses "category", does that work? I am very aware that my own status means that me choosing wording on this isn't great.

**Comment by Floppy** [comment]
The wording in the [contributor covenant](http://contributor-covenant.org/version/1/4/) is probably better:

> regardless of age, body size, disability, ethnicity, gender identity and expression, level of experience, nationality, personal appearance, race, religion, or sexual identity and orientation.

But it still doesn't include a catchall.

**Comment by philipjohn** [comment]
Yeah, it's difficult. It's also just occurred to me, in thinking about this again that we should consider expanding "equality" to "equality and diversity" too.

**Comment by Floppy** [comment]
Well, the statement is about individual rights and the law, so equality is the relevant part here (I think?). We could have a similar statement in the previous section that a more diverse culture (with the same axes of diversity) is a stronger one. Or make sure we include it elsewhere in the manifesto.

**Comment by andrewdwilliams** [comment]
:+1: Looks good to me.

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are a [contributor](https://votebot.openpolitics.org.uk/proposals/) to this repository (and not the proposer), you may vote on whether or not it is accepted. 

## How to vote
Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

|vote|symbol|type this|points|
|--|--|--|--|
|Agree|:thumbsup:|`:thumbsup:`|1|
|Abstain|:hand:|`:hand:`|-1|
|Block|:thumbsdown:|`:thumbsdown:`|-1000|

Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 7 days, but will be closed if the proposal is not accepted after 90.

Votes are counted [automatically here](https://votebot.openpolitics.org.uk/proposals/425), and results are set in the merge status checks below.

## Changes

If the proposer makes a change to the proposal, no votes cast before that change will be counted.

**Pull request merged**
