### PR TITLE
Provision for calling constitutional convention

### PR DESCRIPTION
**Pull request by andrewdwilliams**
A half-baked idea, but one I didn't want to have kicking round in my head. I'm not sure whether a constitutional convention should be how the constitution is first made, instead of a citizens' panel (not the same thing), or whether it should only exist for the purpose of making amendments.

### CODE REVIEW

**Comment by Floppy** [comment]
Could be both - one idea in the manifesto at the moment is that we start with a blank-slate constitution, and make everything an amendment. :)

**Comment by andrewdwilliams** [comment]
I spotted that. It's an interesting one. I would imagine constitutional conventions would be rarities only called when there are a number of things to add or change. So maybe the constitution should be a blank slate but we should then add things first time round with a constitutional convention. And I definitely think that regardless, provision should exist for a constitutional convention anyway, as we don't know what constitutional crises may arise in the future.

**Comment by EdCaplen** [comment]
I like the idea of a constitution. The convention, much like the American ones should very much be ran based off of mutual compromise to ensure that all are represented.

**Comment by OliverJackson1** [comment]
I've got an idea on this, why not work with the South African approach and ask every citizen directly what they need, starting from blank slate (country name even? Would probably lead to Britty McBritface, so perhaps not - joke does not work with the word country.). 

We would implement a provisional constitution of our own design but only for so long as consultation occurs with all citizens. For the South Africans this was two years. For a country the size of the UK it would probably be one rotation of parliament. 

A constitution needs to be the direct product of the people to create the feeling of citizenship: all citizens should have there say, both in its creation, ratification (ref: 50:50) and amendment (ref: 60:40). As democracy protects the minority from the power of the majority, asking all directly is the only way of securing that every minority is covered, the smallest minority, is the minority of 1.

**Comment by philipjohn** [comment]
I like the idea of calling the constitutional convention, though I'd prefer that it were a citizen panel. We might say "non-partisan" but the reality is that it'll be political/celebrity figures with the funds to launch a campaign that will be elected and I don't think self-selecting people who are likely to be unrepresentative of the population should be deciding on constitutional amendments.

**Comment by Floppy** [comment]
There are things here I'd change (how the convention members are chosen mainly), but it's a useful addition to the constitution proposal, so I'm going to upvote and then submit changes to a sortition-based system later on. 👍

**Comment by philipjohn** [comment]
That's very pragmatic @floppy :) I'll agree with that! :+1:

**Comment by andrewdwilliams** [comment]
@Floppy Can this be merged?

**Comment by Floppy** [comment]
It can! Thanks for the reminder. I really should make this automatic soon.

**Comment by Floppy** [comment]
pinging the votebot, which hasn't removed this. Please ignore this comment! :)

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are a [contributor](https://votebot.openpolitics.org.uk/proposals/) to this repository (and not the proposer), you may vote on whether or not it is accepted. 

## How to vote
Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

|vote|symbol|type this|points|
|--|--|--|--|
|Agree|:thumbsup:|`:thumbsup:`|1|
|Abstain|:hand:|`:hand:`|-1|
|Block|:thumbsdown:|`:thumbsdown:`|-1000|

Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 7 days, but will be closed if the proposal is not accepted after 90.

Votes are counted [automatically here](https://votebot.openpolitics.org.uk/proposals/389), and results are set in the merge status checks below.

## Changes

If the proposer makes a change to the proposal, no votes cast before that change will be counted.

**Pull request merged**
