### PR TITLE
Prime Minister line of succession

### PR DESCRIPTION
**Pull request by andrewdwilliams**

### CODE REVIEW

**Comment by Floppy** [comment]
Another horrible editor clash is breaking the diff here. The relevant text for reviewers is:

## Line of succession

Introduce legislation setting out the line of succession for the Prime Minister in the unlikely but
possible event that they are incapacitated and unable to govern, in a similar style to that of the
Presidential Line of Succession in the United States. We could, for instance, introduce a variation
on the [Prime Minister (Replacement) Bill](http://www.publications.parliament.uk/pa/bills/cbill/2013-2014/0059/14059.pdf).

**Comment by Floppy** [comment]
So, this seems sensible, and something you would have in a constitution (the core OS of the country), perhaps. My question is, do we not have this at the moment?

**Comment by andrewdwilliams** [comment]
No, we don't. Our constitution is very much a make-it-up-as-you-go-along arrangement, which would be precisely what we would do in this situation.

I was just thinking, though, if this would be better going under the constitutional convention section, as something like: "during the convention we would consider the introduction of a codified line of succession for the PM in case they are incapacitated."

**Comment by Floppy** [comment]
I'm a :+1: on adding this, btw. Sorry, forgot to vote.

**Comment by Floppy** [comment]
Oh, sorry, I renamed the branch and it auto-closed this request. Can you resubmit it? Sorry about that.

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are a [contributor](https://votebot.openpolitics.org.uk/proposals/) to this repository (and not the proposer), you may vote on whether or not it is accepted. 

## How to vote
Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

|vote|symbol|type this|points|
|--|--|--|--|
|Agree|:thumbsup:|`:thumbsup:`|1|
|Abstain|:hand:|`:hand:`|-1|
|Block|:thumbsdown:|`:thumbsdown:`|-1000|

Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 7 days, but will be closed if the proposal is not accepted after 90.

Votes are counted [automatically here](https://votebot.openpolitics.org.uk/proposals/374), and results are set in the merge status checks below.

## Changes

If the proposer makes a change to the proposal, no votes cast before that change will be counted.

**Pull request closed without merging**
