### PR TITLE
secular chaplaincy in the military

### PR DESCRIPTION
**Pull request by andrewedmondson**

### CODE REVIEW

**Comment by philipjohn** [comment]
:hand: as with the other, similar, proposal as I don't think there should be a chaplaincy service.

**Comment by andrewedmondson** [comment]
This is probably the position of the national secular society, on 
funding grounds. I don't know if there is a real need for secular 
chaplaincy. That would need some independent research.

**Comment by philipjohn** [comment]
> I don't know if there is a real need for secular chaplaincy.

Indeed, and state funds shouldn't be used for religious services.

**Comment by PaulJRobinson** [comment]
I'm not quite sure what this means. What is the 'chaplaincy service'? We are voting elsewhere on a proposal for a secular state/society and disestablishing the CofE. Doesn't that cover everything? Could you explain this in more detail?

**Comment by andrewedmondson** [comment]
The chaplaincy service is funded by the government and traditionally 
provided Christian chaplains to minister to the spiritual needs of 
patients in the NHS, prisoners and members of the armed forces.

The latter two categories are pretty much the same as they have always been.

The NHS has been forced to accept that non-religious and non-Christian 
patients also have a right to chaplaincy. This begs the question of what 
a chaplain is for. Religious chaplains can adminster last rights, 
arrange funerals, pray with patients, friends and family, hold services, 
etc. But most of their time is spent listening.

As far as I am aware, the only chaplains that are paid are religious 
chaplains. There are virtually no Humanist/non-religious chaplains. This 
is partly because that most people don't know what a Humanist is or that 
there can be a non-religious chaplain, thanks to the biased system.

Non-religious patients usually find someone else to listen to them, e.g. 
friends, families, co-patients, cleaners, other staff.

**Comment by iconoclast86** [comment]
:hand:

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are a [contributor](https://votebot.openpolitics.org.uk/proposals/) to this repository (and not the proposer), you may vote on whether or not it is accepted. 

## How to vote
Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

|vote|symbol|type this|points|
|--|--|--|--|
|Agree|:thumbsup:|`:thumbsup:`|1|
|Abstain|:hand:|`:hand:`|-1|
|Block|:thumbsdown:|`:thumbsdown:`|-1000|

Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 7 days, but will be closed if the proposal is not accepted after 90.

Votes are counted [automatically here](https://votebot.openpolitics.org.uk/proposals/329), and results are set in the merge status checks below.

## Changes

If the proposer makes a change to the proposal, no votes cast before that change will be counted.

**Pull request closed without merging**
