### PR TITLE
Common sense practical policies that can be implemented.

### PR DESCRIPTION
**Pull request by barriebenson**
From what I've read this isn't a new party it's a carbon copy of the liberal party.

### CODE REVIEW

**Comment by Floppy** [comment]
@barriebenson thanks for the suggestions, but considering that everything here is diametrically opposed to existing policy, and violates the core principles...

Vote: 🚫

**Comment by Autumn-Leah** [comment]
Not that I disagree, but it *is* on you to state which principles of the party the policy breaks, as per the rules that you wrote @Floppy

**Comment by Autumn-Leah** [comment]
@barriebenson Even if I wanted to vote this through, which I don't, you need a major formatting change since you've put all the proposals in the the titles of the given sections. Voting against until this happens, then I'm open to further discussion.

Vote: ❎

**Comment by Autumn-Leah** [comment]
@barriebenson also, this party is definitely *not* a carbon copy of the liberal party XD

**Comment by philipjohn** [comment]
> STOP ANYONE USING THE NHS WHO DOESN'T HAVE AN NI NUMBER AND PROOF OF ADDRESS AND COUNCIL TAX PAYMENT.

and

> REMOVE UK CITIZENSHIP FROM NATURALISED CITIZENS WHO COMMIT CRIMINAL OFFENCES OR JOIN ANY ORGANISATION THAT FIGHTS THE UK's ARMED FORCES WHO ARE FIGHTING TO PROTECT CITIZENS OF THE UK, DEPORT ALL ILLEGAL IMMIGRANTS AND SEIZE ALL THEIR UK ASSETS.

both violate:

> Be treated equally by the law, regardless of gender identity, sex, romantic orientation, sexual orientation, ethnicity, race, perceived ethnicity and/or race, age, religious and/or spiritual belief, occupation (current or previous), status of union membership (including the type of union and what union), marital status, or disability.

Words cannot describe my utter contempt for the idea that capital punishment should be re-introduced.

Vote: 🚫

**Pull request closed without merging**
