### PR TITLE
Tidying up

### PR DESCRIPTION
**Pull request by geeksareforlife**
A header was missing, and a tiny grammatical error

### CODE REVIEW

**Comment by Floppy** [comment]
Vote: ✅

**Comment by andrewdwilliams** [comment]
Vote: ✅

**Comment by philipjohn** [comment]
Vote: ✅

**Comment by Floppy** [comment]
For some reason the times aren't being updated correctly in the statuses, but if I comment, it should. Then I will merge :)

**Comment by geeksareforlife** [comment]
Now that this is merged, should I show up on here: https://votebot.openpolitics.org.uk/users ?

**Comment by Floppy** [comment]
Yes, should do - if you’re not there, it might be not updating something… I’ll check.

**Pull request merged**
