### PR TITLE
Reforming magistrate courts

### PR DESCRIPTION
**Pull request by Autumn-Leah**
My motivation for this policy is my utter disgust at the idea that you may merely bribe, coerce, or otherwise convince 3 people of the supremacy of conviction over not, or of the persons guilt through legitimate means or not, and thereby ruin somebodies life, whether that be temporarily or permanently is beside the point.

### CODE REVIEW

**Comment by philipjohn** [comment]
Vote: ✅

**Comment by Xyleneb** [comment]
I'm sure there is an economic argument to be had here (and it'll cost a lot of money) but I'm not especially interested in it. Trial by jury is one of the few things we have that's worth holding on to.

Vote: :white_check_mark:

**Comment by Floppy** [comment]
It should certainly always be an option.

Vote: ✅

**Comment by andrewdwilliams** [comment]
I've not thought about it too much, but this appears to defeat the point of magistrates courts. Either restrict further the gravity of cases that go before magistrates courts or abolish them altogether, so that cases on go in front of trained judges (and juries where appropriate).

**Pull request merged**
