### PR TITLE
remove bishops from house of lords, disestablish the church of England, create a secular state, 

### PR DESCRIPTION
**Pull request by andrewedmondson**

### CODE REVIEW

**Comment by Floppy** [comment]
Thanks for the additions! Pretty sure we have these two things in elsewhere; let me find them...

**Comment by Floppy** [comment]
Yep, here we go:

Disestablishment: http://openpolitics.org.uk/manifesto/society.html#secularism

Looks like the bishops wording (which we did have before) has been replaced with a more general reform, but we could have it back in.

**Comment by andrewedmondson** [comment]
Thanks James. No harm in repeting them in overlapping sections. I'm sure 
there are quite a few other changes I could mek. Running out of time now.

Regards

Andrew

**Comment by Floppy** [comment]
True that. We can always cross-link after. :+1:

**Comment by yellowgopher** [comment]
My two penny's worth (although I KNOW I am in the minority here) - I would be very careful about explicitly naming groups or individuals in these things because there is a risk that you could end up missing someone or something off the list!  I am actually for the disestablishment of the CofE (I know, shock horror) as I think it is actually a chain around the CofE's neck and a fundamentally unfair position over the multitude of different groups that exist in the religious sector and beyond.  

It may shock the secular majority here that some bishops are actually worth their position in the Lords - but we'd want to reform the Lords anyway... ;-)

**Comment by andrewedmondson** [comment]
It is valid to name the C of E because it is part of the government.

**Comment by yellowgopher** [comment]
Not sure what you are getting at here.  I would create a general framework for a new Lords - removes the issue of particular groups being over represented etc.  But I think we should allow any capable person to serve - regardless of their opinion on God!

**Comment by andrewedmondson** [comment]
Yes I agree. No reason why a bishop shouldn't be there; just not by right.

**Comment by yellowgopher** [comment]
Fair point and agreed - anyone can serve as long as they get there on merit.

**Comment by philipjohn** [comment]
Not sure I like the idea of duplicating stuff. If it really needs to be in two sections, it should just be linked.

**Comment by PaulJRobinson** [comment]
Get's my vote :+1:

**Comment by iconoclast86** [comment]
:hand:

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are a [contributor](https://votebot.openpolitics.org.uk/proposals/) to this repository (and not the proposer), you may vote on whether or not it is accepted. 

## How to vote
Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

|vote|symbol|type this|points|
|--|--|--|--|
|Agree|:thumbsup:|`:thumbsup:`|1|
|Abstain|:hand:|`:hand:`|-1|
|Block|:thumbsdown:|`:thumbsdown:`|-1000|

Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 7 days, but will be closed if the proposal is not accepted after 90.

Votes are counted [automatically here](https://votebot.openpolitics.org.uk/proposals/324), and results are set in the merge status checks below.

## Changes

If the proposer makes a change to the proposal, no votes cast before that change will be counted.

**Pull request closed without merging**
