### PR TITLE
No killer robots please

### PR DESCRIPTION
**Pull request by Floppy**
Having a second try at submitting this one. This is coming ever closer, with auto-firing drones and so on starting to pop up in the news.

### CODE REVIEW

**Comment by philipjohn** [comment]
I want to question the premise that "machines [have] the power to decide who lives and dies".

What machines currently have the power to decide who lives and dies, without human intervention?

Does any machine have the ability, on it's own, to circumvent international rules on warfare?

Is it possible (legally speaking) for a machine to, without human intervention, identify and kill human beings legally?

**Comment by Floppy** [comment]
They don't yet. This is pre-emptive, because it ain't far off.

**Comment by andrewdwilliams** [comment]
:+1: I approve

**Comment by Floppy** [comment]
@philipjohn Check out:

* http://sputniknews.com/science/20150529/1022685733.html
* http://spectrum.ieee.org/automaton/robotics/military-robots/autonomous-weapons-could-be-developed-for-use-within-years

The point is that it's coming, and we should be deciding ahead of time if we want it to.

**Comment by Floppy** [comment]
@philipjohn this is the other one I was looking for: https://medium.com/insurge-intelligence/the-pentagon-is-building-a-self-aware-killer-robot-army-fueled-by-social-media-bd1b55944298#.2hte96n4z

**Comment by Floppy** [comment]
@philipjohn this is the other one I was looking for: https://medium.com/insurge-intelligence/the-pentagon-is-building-a-self-aware-killer-robot-army-fueled-by-social-media-bd1b55944298#.2hte96n4z

**Comment by Floppy** [comment]
More: http://www.popsci.com/ai-pilot-beats-air-combat-expert-in-dogfight?src=SOC&dom=tw

**Comment by Floppy** [comment]
cmoooooon I will only resubmit this again if it's not accepted - @philipjohn? :D

**Comment by Floppy** [comment]
Closing as long-overdue and I should follow the rules. I will be resubmitting though!

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are a [contributor](https://votebot.openpolitics.org.uk/proposals/) to this repository (and not the proposer), you may vote on whether or not it is accepted. 

## How to vote
Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

|vote|symbol|type this|points|
|--|--|--|--|
|Agree|:thumbsup:|`:thumbsup:`|1|
|Abstain|:hand:|`:hand:`|-1|
|Block|:thumbsdown:|`:thumbsdown:`|-1000|

Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 7 days, but will be closed if the proposal is not accepted after 90.

Votes are counted [automatically here](https://votebot.openpolitics.org.uk/proposals/375), and results are set in the merge status checks below.

## Changes

If the proposer makes a change to the proposal, no votes cast before that change will be counted.

**Pull request closed without merging**
