### PR TITLE
Remove charity status from private schools

### PR DESCRIPTION
**Pull request by Floppy**

### CODE REVIEW

**Comment by philipjohn** [comment]
Vote: ✅

**Comment by Xyleneb** [comment]
Do you mind if I one-up this?

"Every paid-for student must in turn completely cover the bursary of a poor student, and in so doing maintain the anonymity of their benefactors, thus cementing the ratio of rich to poor students at 50:50."

If they can still make a surplus after that, they can have it untaxed.

**Comment by Floppy** [comment]
hah, feel free to one-up later, but I'll keep it simple for now :)

(For context, I suggest this as someone who went to a private school, so I've got direct experience)

**Comment by Xyleneb** [comment]
Vote: :white_check_mark:

My school had an "optional donation" every month where the teachers would grill you in front of the rest of the class if you didn't pay up, as if you were taking food out of their mouths and causing a shitty education for everybody.

These exclusive clubs won't work as well once half of the classes are subsidised.

**Pull request merged**
