### PR TITLE
Added "Austerity Act"

### PR DESCRIPTION
**Pull request by hiltona**
There are many companies that have made a lot of money out of the taxpayer in recent years. I have tried to apply the same approach to companies that has been applied to benefit recipients.  Alex

### CODE REVIEW

**Comment by philipjohn** [comment]
@hiltona This will pass once you click the beautfiul big blue button at https://www.clahub.com/agreements/openpolitics/manifesto

**Comment by tmtmtmtm** [comment]
it shouldn't though — as I've a :-1: on it that the vote bot isn't picking up on for some reason...

**Comment by philipjohn** [comment]
Hmm that's weird. You should have voting rights because of #226 but Votebot doesn't seem to be picking that up. I'll flag that as an issue...

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are a [contributor](https://votebot.openpolitics.org.uk/proposals/) to this repository (and not the proposer), you may vote on whether or not it is accepted. 

## How to vote
Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

|vote|symbol|type this|points|
|--|--|--|--|
|Agree|:thumbsup:|`:thumbsup:`|1|
|Abstain|:hand:|`:hand:`|-1|
|Block|:thumbsdown:|`:thumbsdown:`|-1000|

Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 7 days, but will be closed if the proposal is not accepted after 90.

Votes are counted [automatically here](https://votebot.openpolitics.org.uk/proposals/238), and results are set in the merge status checks below.

## Changes

If the proposer makes a change to the proposal, no votes cast before that change will be counted.

**Pull request closed without merging**
