### PR TITLE
Fair Use

### PR DESCRIPTION
**Pull request by Autumn-Leah**

### CODE REVIEW

**Comment by Floppy** [comment]
Is there a reference we can add, or a little more explanation on what this would mean? I'm not familiar with the term "Fair Dealing".

**Comment by Floppy** [comment]
(obviously I can look it up, just channeling the new readers' point of view :) )

**Comment by Floppy** [comment]
Oh, interesting, I wasn't aware of the differences, and that "fair use" is just a US thing. https://en.wikipedia.org/wiki/Fair_dealing#United_Kingdom

I think this is a good thing, but it needs a bit more explanation of why it's in there.

Vote: ✅

**Comment by Autumn-Leah** [comment]
I'll edit it to include links

**Comment by philipjohn** [comment]
Vote: ✅

**Comment by Xyleneb** [comment]
Vote: :white_check_mark:

**Comment by Floppy** [comment]
Vote: ✅

**Pull request merged**
