### PR TITLE
Repealing mass surveillance

### PR DESCRIPTION
**Pull request by Autumn-Leah**
I don't think I need to add much here.

### CODE REVIEW

**Comment by Floppy** [comment]
Vote: ✅

**Comment by philipjohn** [comment]
Vote: ✅

**Comment by Xyleneb** [comment]
It's all gold except for the interception warrant bit. I don't wish to bar security from *targeted* interception, so long as they have obtained the applicable warrant from a judge. Can you explain what the interception warrant is and why is it's existence is contentious?

**Comment by Autumn-Leah** [comment]
@Xyleneb You misread it.

>  and to prevent the existence of interception warrants and any data collected from being revealed in court.

means that *the warrant can't be revealed in court* not that interception warrants are banned or otherwise, it makes no statement on the legality of interception warrants. The policy proposal would allow these warrants to be submitted in court, which can't currently happen due to the Regulation of Investigatory Powers Act 2000, which this would repeal.

**Pull request merged**
