### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by philipjohn**
Too many members :)

### CODE REVIEW

**Comment by philipjohn** [comment]
Ugh. I did it the wrong way round :facepalm:

**Comment by Autumn-Leah** [comment]
lol @phillipjohn might wanna go on github and edit that

**Comment by Floppy** [comment]
Vote: ✅

**Comment by philipjohn** [comment]
That's better - it looks less like I'm a moron now :D

**Comment by Autumn-Leah** [comment]
Vote: ✅

**Pull request merged**
